// Class: ReadMLPBFGS
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLPBFGS
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.24/02       [399362]
Creator        : markm
Date           : Sun Nov 28 13:33:38 2021
Host           : Linux Manjaro-Desktop 5.10.52-1-MANJARO #1 SMP PREEMPT Tue Jul 20 20:32:02 UTC 2021 x86_64 GNU/Linux
Dir            : /home/markm/Documents/research/vbsTMVA
Training events: 27488
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TrainingMethod: "BFGS" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 15
bos_PuppiAK8_m_sd0_corr       bos_PuppiAK8_m_sd0_corr       bos_PuppiAK8_m_sd0_corr       bos_PuppiAK8_m_sd0_corr                                         'F'    [65.0625,104.9375]
bos_PuppiAK8_tau2tau1         bos_PuppiAK8_tau2tau1         bos_PuppiAK8_tau2tau1         bos_PuppiAK8_tau2tau1                                           'F'    [0.0682255253196,0.549910068512]
lep1_eta                      lep1_eta                      lep1_eta                      lep1_eta                                                        'F'    [-2.498046875,2.49951171875]
nJet30f                       nJet30f                       nJet30f                       nJet30f                                                         'F'    [2,11]
vbf1_AK4_eta                  vbf1_AK4_eta                  vbf1_AK4_eta                  vbf1_AK4_eta                                                    'F'    [-4.66796875,5.01953125]
vbf1_AK4_pt                   vbf1_AK4_pt                   vbf1_AK4_pt                   vbf1_AK4_pt                                                     'F'    [50.0678367615,1970.49926758]
vbf1_AK4_qgid                 vbf1_AK4_qgid                 vbf1_AK4_qgid                 vbf1_AK4_qgid                                                   'F'    [-1,1]
vbf2_AK4_eta                  vbf2_AK4_eta                  vbf2_AK4_eta                  vbf2_AK4_eta                                                    'F'    [-5.0771484375,5.0888671875]
vbf2_AK4_pt                   vbf2_AK4_pt                   vbf2_AK4_pt                   vbf2_AK4_pt                                                     'F'    [50.0047340393,1175.74890137]
vbf2_AK4_qgid                 vbf2_AK4_qgid                 vbf2_AK4_qgid                 vbf2_AK4_qgid                                                   'F'    [-1,1]
vbf_deta                      vbf_deta                      vbf_deta                      vbf_deta                                                        'F'    [2.50006103516,9.2822265625]
vbf_eta                       vbf_eta                       vbf_eta                       vbf_eta                                                         'F'    [-7.53327178955,7.36832284927]
vbf_m                         vbf_m                         vbf_m                         vbf_m                                                           'F'    [500.026428223,7649.34521484]
zeppHad                       zeppHad                       zeppHad                       zeppHad                                                         'F'    [-4.53909301758,4.37330627441]
zeppLep                       zeppLep                       zeppLep                       zeppLep                                                         'F'    [-6.87152099609,6.03112888336]
NSpec 50
bos_AK4AK4_eta                bos_AK4AK4_eta                bos_AK4AK4_eta                bos_AK4AK4_eta                                                  'F'    [-999,-999]
bos_AK4AK4_m                  bos_AK4AK4_m                  bos_AK4AK4_m                  bos_AK4AK4_m                                                    'F'    [-999,-999]
bos_AK4AK4_pt                 bos_AK4AK4_pt                 bos_AK4AK4_pt                 bos_AK4AK4_pt                                                   'F'    [-999,-999]
bosCent                       bosCent                       bosCent                       bosCent                                                         'F'    [-4.82135009766,3.74968290329]
bos_j1_AK4_eta                bos_j1_AK4_eta                bos_j1_AK4_eta                bos_j1_AK4_eta                                                  'F'    [-999,-999]
bos_j1_AK4_pt                 bos_j1_AK4_pt                 bos_j1_AK4_pt                 bos_j1_AK4_pt                                                   'F'    [-999,-999]
bos_j2_AK4_eta                bos_j2_AK4_eta                bos_j2_AK4_eta                bos_j2_AK4_eta                                                  'F'    [-999,-999]
bos_j2_AK4_pt                 bos_j2_AK4_pt                 bos_j2_AK4_pt                 bos_j2_AK4_pt                                                   'F'    [-999,-999]
bos_PuppiAK8_eta              bos_PuppiAK8_eta              bos_PuppiAK8_eta              bos_PuppiAK8_eta                                                'F'    [-2.3994140625,2.39892578125]
bos_PuppiAK8_m_sd0            bos_PuppiAK8_m_sd0            bos_PuppiAK8_m_sd0            bos_PuppiAK8_m_sd0                                              'F'    [65.0625,104.9375]
bos_PuppiAK8_phi              bos_PuppiAK8_phi              bos_PuppiAK8_phi              bos_PuppiAK8_phi                                                'F'    [-3.1416015625,3.1416015625]
bos_PuppiAK8_pt               bos_PuppiAK8_pt               bos_PuppiAK8_pt               bos_PuppiAK8_pt                                                 'F'    [200.125,2586]
btagWeight_loose              btagWeight_loose              btagWeight_loose              btagWeight_loose                                                'F'    [0.707488656044,1.77973711491]
dibos_eta                     dibos_eta                     dibos_eta                     dibos_eta                                                       'F'    [-5.70251989365,5.60779333115]
dibos_m                       dibos_m                       dibos_m                       dibos_m                                                         'F'    [142.427078247,4868.22753906]
dibos_mt                      dibos_mt                      dibos_mt                      dibos_mt                                                        'F'    [293.477203369,4877.96289062]
dibos_phi                     dibos_phi                     dibos_phi                     dibos_phi                                                       'F'    [-3.14108610153,3.14141798019]
dibos_pt                      dibos_pt                      dibos_pt                      dibos_pt                                                        'F'    [3.8788087368,2055.06591797]
dilep_eta                     dilep_eta                     dilep_eta                     dilep_eta                                                       'F'    [-5.64239501953,5.94346761703]
dilep_m                       dilep_m                       dilep_m                       dilep_m                                                         'F'    [2.12073945999,982.819946289]
dilep_mt                      dilep_mt                      dilep_mt                      dilep_mt                                                        'F'    [55.7104530334,2287.56933594]
dilep_phi                     dilep_phi                     dilep_phi                     dilep_phi                                                       'F'    [-3.14107394218,3.14104056358]
dilep_pt                      dilep_pt                      dilep_pt                      dilep_pt                                                        'F'    [0.475926727057,2284.8972168]
evt                           evt                           evt                           evt                                                             'F'    [417,233661504]
genWeight                     genWeight                     genWeight                     genWeight                                                       'F'    [-303.359375,316.46875]
gid                           gid                           gid                           gid                                                             'F'    [1,15]
L1PFWeight                    L1PFWeight                    L1PFWeight                    L1PFWeight                                                      'F'    [0.183705121279,1]
lep1_iso                      lep1_iso                      lep1_iso                      lep1_iso                                                        'F'    [0,0.136843934655]
lep1_m                        lep1_m                        lep1_m                        lep1_m                                                          'F'    [0.000510999991093,0.000510999991093]
lep1_phi                      lep1_phi                      lep1_phi                      lep1_phi                                                        'F'    [-3.14111328125,3.1416015625]
lep1_pt                       lep1_pt                       lep1_pt                       lep1_pt                                                         'F'    [25.0132808685,1195.63085938]
lep1_q                        lep1_q                        lep1_q                        lep1_q                                                          'F'    [-1,1]
lep2_eta                      lep2_eta                      lep2_eta                      lep2_eta                                                        'F'    [-999,-999]
lep2_pt                       lep2_pt                       lep2_pt                       lep2_pt                                                         'F'    [-999,-999]
mcWeight                      mcWeight                      mcWeight                      mcWeight                                                        'F'    [9.15913211941e-09,1.40398815347e-05]
MET                           MET                           MET                           MET                                                             'F'    [30.0022945404,1751.86328125]
MET_phi                       MET_phi                       MET_phi                       MET_phi                                                         'F'    [-3.14136505127,3.14145612717]
nBtag_loose                   nBtag_loose                   nBtag_loose                   nBtag_loose                                                     'F'    [0,0]
nBtag_medium                  nBtag_medium                  nBtag_medium                  nBtag_medium                                                    'F'    [0,0]
neu_pz_type0                  neu_pz_type0                  neu_pz_type0                  neu_pz_type0                                                    'F'    [-999,-999]
nJet30                        nJet30                        nJet30                        nJet30                                                          'F'    [2,11]
nJet50                        nJet50                        nJet50                        nJet50                                                          'F'    [2,10]
nPV                           nPV                           nPV                           nPV                                                             'F'    [1,57]
puWeight                      puWeight                      puWeight                      puWeight                                                        'F'    [0,1.20750808716]
run                           run                           run                           run                                                             'F'    [1,1]
sid                           sid                           sid                           sid                                                             'F'    [100,1100]
vbf1_AK4_phi                  vbf1_AK4_phi                  vbf1_AK4_phi                  vbf1_AK4_phi                                                    'F'    [-3.1416015625,3.1416015625]
vbf2_AK4_phi                  vbf2_AK4_phi                  vbf2_AK4_phi                  vbf2_AK4_phi                                                    'F'    [-3.1416015625,3.14111328125]
vbf_phi                       vbf_phi                       vbf_phi                       vbf_phi                                                         'F'    [-3.14150476456,3.14155673981]
vbf_pt                        vbf_pt                        vbf_pt                        vbf_pt                                                          'F'    [2.19970178604,2025.51708984]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLPBFGS : public IClassifierReader {

 public:

   // constructor
   ReadMLPBFGS( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadMLPBFGS" ),
        fNvars( 15 )
   {
      // the training input variables
      const char* inputVars[] = { "bos_PuppiAK8_m_sd0_corr", "bos_PuppiAK8_tau2tau1", "lep1_eta", "nJet30f", "vbf1_AK4_eta", "vbf1_AK4_pt", "vbf1_AK4_qgid", "vbf2_AK4_eta", "vbf2_AK4_pt", "vbf2_AK4_qgid", "vbf_deta", "vbf_eta", "vbf_m", "zeppHad", "zeppLep" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;
      fVmin[11] = -1;
      fVmax[11] = 1;
      fVmin[12] = -1;
      fVmax[12] = 0.99999988079071;
      fVmin[13] = -1;
      fVmax[13] = 1;
      fVmin[14] = -1;
      fVmax[14] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLPBFGS() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fOff_1[3][15];
   double fScal_1[3][15];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[15];
   double fVmax[15];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[15];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   double fWeightMatrix0to1[21][16];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][21];   // weight matrix from layer 1 to 2

};

inline void ReadMLPBFGS::Initialize()
{
   // build network structure
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -1.21666490909127;
   fWeightMatrix0to1[1][0] = 6.29761508530485;
   fWeightMatrix0to1[2][0] = -1.45234927835728;
   fWeightMatrix0to1[3][0] = 5.05093227255938;
   fWeightMatrix0to1[4][0] = -2.1997872770227;
   fWeightMatrix0to1[5][0] = -1.08306589629328;
   fWeightMatrix0to1[6][0] = -5.01042357245908;
   fWeightMatrix0to1[7][0] = -0.422900935542089;
   fWeightMatrix0to1[8][0] = -1.21654912891517;
   fWeightMatrix0to1[9][0] = -0.406211116800592;
   fWeightMatrix0to1[10][0] = 0.514132500338472;
   fWeightMatrix0to1[11][0] = -0.655901096090976;
   fWeightMatrix0to1[12][0] = -2.40296784426593;
   fWeightMatrix0to1[13][0] = -1.9641189898949;
   fWeightMatrix0to1[14][0] = -6.20336867484035;
   fWeightMatrix0to1[15][0] = -0.858839375823934;
   fWeightMatrix0to1[16][0] = 1.2181345308604;
   fWeightMatrix0to1[17][0] = 4.16784226838514;
   fWeightMatrix0to1[18][0] = 0.242645476153444;
   fWeightMatrix0to1[19][0] = 2.2089537369801;
   fWeightMatrix0to1[0][1] = 2.07225059042951;
   fWeightMatrix0to1[1][1] = 3.37185575772617;
   fWeightMatrix0to1[2][1] = 1.68492435782788;
   fWeightMatrix0to1[3][1] = 3.29127598312033;
   fWeightMatrix0to1[4][1] = -0.60524949927034;
   fWeightMatrix0to1[5][1] = -0.990719014241469;
   fWeightMatrix0to1[6][1] = 7.86519542686993;
   fWeightMatrix0to1[7][1] = -3.82677536791803;
   fWeightMatrix0to1[8][1] = 3.62018467835429;
   fWeightMatrix0to1[9][1] = -0.908520843977381;
   fWeightMatrix0to1[10][1] = 1.73941826983248;
   fWeightMatrix0to1[11][1] = 0.438699032084974;
   fWeightMatrix0to1[12][1] = 2.55272946880659;
   fWeightMatrix0to1[13][1] = 1.16772255672792;
   fWeightMatrix0to1[14][1] = 2.74598162980575;
   fWeightMatrix0to1[15][1] = -1.17626930189508;
   fWeightMatrix0to1[16][1] = -0.175320164693614;
   fWeightMatrix0to1[17][1] = 4.0579067495548;
   fWeightMatrix0to1[18][1] = -0.391879645213554;
   fWeightMatrix0to1[19][1] = 3.68496718148272;
   fWeightMatrix0to1[0][2] = -0.419020147524523;
   fWeightMatrix0to1[1][2] = 2.31049122021136;
   fWeightMatrix0to1[2][2] = 6.52057774107947;
   fWeightMatrix0to1[3][2] = -0.275492780739877;
   fWeightMatrix0to1[4][2] = -0.773051665974421;
   fWeightMatrix0to1[5][2] = -0.50345474190456;
   fWeightMatrix0to1[6][2] = -8.57523260189908;
   fWeightMatrix0to1[7][2] = 6.50767668117648;
   fWeightMatrix0to1[8][2] = 6.15017417800008;
   fWeightMatrix0to1[9][2] = 2.76045319783451;
   fWeightMatrix0to1[10][2] = 3.03562980844624;
   fWeightMatrix0to1[11][2] = 4.75894650495727;
   fWeightMatrix0to1[12][2] = -8.62775551804253;
   fWeightMatrix0to1[13][2] = 7.24656910755034;
   fWeightMatrix0to1[14][2] = -8.11692150024965;
   fWeightMatrix0to1[15][2] = 1.71993281269213;
   fWeightMatrix0to1[16][2] = -2.41004078448626;
   fWeightMatrix0to1[17][2] = 5.14810267073139;
   fWeightMatrix0to1[18][2] = 0.514120914365879;
   fWeightMatrix0to1[19][2] = -1.65608182579679;
   fWeightMatrix0to1[0][3] = -0.233506111525404;
   fWeightMatrix0to1[1][3] = 1.87859279305471;
   fWeightMatrix0to1[2][3] = 6.22266752975956;
   fWeightMatrix0to1[3][3] = 11.7101310100044;
   fWeightMatrix0to1[4][3] = 2.22188591012438;
   fWeightMatrix0to1[5][3] = 0.915115553568896;
   fWeightMatrix0to1[6][3] = 1.12629330251688;
   fWeightMatrix0to1[7][3] = -0.604049319790926;
   fWeightMatrix0to1[8][3] = 10.482080707982;
   fWeightMatrix0to1[9][3] = 1.25671591533331;
   fWeightMatrix0to1[10][3] = -4.649711799707;
   fWeightMatrix0to1[11][3] = -1.02072618187252;
   fWeightMatrix0to1[12][3] = 0.501238703673494;
   fWeightMatrix0to1[13][3] = 2.0052241872931;
   fWeightMatrix0to1[14][3] = 3.55019888057093;
   fWeightMatrix0to1[15][3] = 0.148345648985493;
   fWeightMatrix0to1[16][3] = -2.47848600335336;
   fWeightMatrix0to1[17][3] = 0.444288786837496;
   fWeightMatrix0to1[18][3] = -3.15833408053465;
   fWeightMatrix0to1[19][3] = 4.80247927243559;
   fWeightMatrix0to1[0][4] = 8.54083983556418;
   fWeightMatrix0to1[1][4] = -4.39435278402998;
   fWeightMatrix0to1[2][4] = 6.59832402846336;
   fWeightMatrix0to1[3][4] = -3.23545900971568;
   fWeightMatrix0to1[4][4] = -2.98768139685169;
   fWeightMatrix0to1[5][4] = 0.383027697583968;
   fWeightMatrix0to1[6][4] = 2.37530004196604;
   fWeightMatrix0to1[7][4] = -7.79076941106301;
   fWeightMatrix0to1[8][4] = -2.08840910591847;
   fWeightMatrix0to1[9][4] = -3.86785377304914;
   fWeightMatrix0to1[10][4] = -0.073677026240688;
   fWeightMatrix0to1[11][4] = -6.50644242994107;
   fWeightMatrix0to1[12][4] = 10.5543908799888;
   fWeightMatrix0to1[13][4] = -3.69491291252461;
   fWeightMatrix0to1[14][4] = 0.242429153524791;
   fWeightMatrix0to1[15][4] = 8.11288441668116;
   fWeightMatrix0to1[16][4] = 5.46565239450848;
   fWeightMatrix0to1[17][4] = -1.19199378879926;
   fWeightMatrix0to1[18][4] = -10.5560280201347;
   fWeightMatrix0to1[19][4] = 0.332511633614831;
   fWeightMatrix0to1[0][5] = -0.743192903451688;
   fWeightMatrix0to1[1][5] = -3.69608630551517;
   fWeightMatrix0to1[2][5] = -7.43869027292171;
   fWeightMatrix0to1[3][5] = 1.9041558505067;
   fWeightMatrix0to1[4][5] = -5.12807389491007;
   fWeightMatrix0to1[5][5] = 2.98132226605298;
   fWeightMatrix0to1[6][5] = -2.16119668737021;
   fWeightMatrix0to1[7][5] = -4.10321725860307;
   fWeightMatrix0to1[8][5] = 0.860474944907336;
   fWeightMatrix0to1[9][5] = 5.64609503609336;
   fWeightMatrix0to1[10][5] = -3.7490958683983;
   fWeightMatrix0to1[11][5] = -0.234225944113296;
   fWeightMatrix0to1[12][5] = 2.79581253783458;
   fWeightMatrix0to1[13][5] = 4.36251398793736;
   fWeightMatrix0to1[14][5] = -3.26780581332531;
   fWeightMatrix0to1[15][5] = 2.1700259243506;
   fWeightMatrix0to1[16][5] = -2.08332435231985;
   fWeightMatrix0to1[17][5] = -7.05873016315434;
   fWeightMatrix0to1[18][5] = 4.55621040744031;
   fWeightMatrix0to1[19][5] = 3.25213491689811;
   fWeightMatrix0to1[0][6] = 0.320380903876062;
   fWeightMatrix0to1[1][6] = -1.61900910910277;
   fWeightMatrix0to1[2][6] = -3.53564881175212;
   fWeightMatrix0to1[3][6] = 2.59179150955028;
   fWeightMatrix0to1[4][6] = -2.18438850720212;
   fWeightMatrix0to1[5][6] = -1.04069446031943;
   fWeightMatrix0to1[6][6] = 0.410672210292837;
   fWeightMatrix0to1[7][6] = 1.93177387870243;
   fWeightMatrix0to1[8][6] = -4.5502263338081;
   fWeightMatrix0to1[9][6] = -1.50557683107148;
   fWeightMatrix0to1[10][6] = 1.53750604019754;
   fWeightMatrix0to1[11][6] = 0.848763632115072;
   fWeightMatrix0to1[12][6] = -0.515789150209998;
   fWeightMatrix0to1[13][6] = -0.0787911912741753;
   fWeightMatrix0to1[14][6] = -3.25510597716479;
   fWeightMatrix0to1[15][6] = 0.909698524583614;
   fWeightMatrix0to1[16][6] = 2.06802107409894;
   fWeightMatrix0to1[17][6] = -3.59097299078098;
   fWeightMatrix0to1[18][6] = 0.757765048585421;
   fWeightMatrix0to1[19][6] = 1.98212831042888;
   fWeightMatrix0to1[0][7] = 6.56221473114349;
   fWeightMatrix0to1[1][7] = -4.00812886347328;
   fWeightMatrix0to1[2][7] = -5.95199945998625;
   fWeightMatrix0to1[3][7] = 1.6920969644444;
   fWeightMatrix0to1[4][7] = -4.1727730184224;
   fWeightMatrix0to1[5][7] = 0.934893357268342;
   fWeightMatrix0to1[6][7] = 2.7484276986761;
   fWeightMatrix0to1[7][7] = -0.19385286838641;
   fWeightMatrix0to1[8][7] = 0.151314589212608;
   fWeightMatrix0to1[9][7] = -3.63183295351419;
   fWeightMatrix0to1[10][7] = -1.52091366504608;
   fWeightMatrix0to1[11][7] = -5.96834306759241;
   fWeightMatrix0to1[12][7] = 4.46039068272155;
   fWeightMatrix0to1[13][7] = -5.64462555263665;
   fWeightMatrix0to1[14][7] = -0.447730281088172;
   fWeightMatrix0to1[15][7] = -7.09032948970736;
   fWeightMatrix0to1[16][7] = 6.36008720874304;
   fWeightMatrix0to1[17][7] = 1.9546520037125;
   fWeightMatrix0to1[18][7] = -1.02175957606929;
   fWeightMatrix0to1[19][7] = -0.458486730930243;
   fWeightMatrix0to1[0][8] = -2.12946766594069;
   fWeightMatrix0to1[1][8] = 10.6768398295161;
   fWeightMatrix0to1[2][8] = -1.3452381707647;
   fWeightMatrix0to1[3][8] = -1.89572715124549;
   fWeightMatrix0to1[4][8] = 7.77375719867237;
   fWeightMatrix0to1[5][8] = 0.721812953345293;
   fWeightMatrix0to1[6][8] = 1.09807966430911;
   fWeightMatrix0to1[7][8] = -3.6479020208073;
   fWeightMatrix0to1[8][8] = -3.06775211910134;
   fWeightMatrix0to1[9][8] = -1.03741201389342;
   fWeightMatrix0to1[10][8] = 1.18213145298553;
   fWeightMatrix0to1[11][8] = 4.36007415359039;
   fWeightMatrix0to1[12][8] = 1.64608984779813;
   fWeightMatrix0to1[13][8] = 0.679101026136412;
   fWeightMatrix0to1[14][8] = 3.41063500581297;
   fWeightMatrix0to1[15][8] = 0.919173199050387;
   fWeightMatrix0to1[16][8] = -4.26200385025487;
   fWeightMatrix0to1[17][8] = -1.80789526735574;
   fWeightMatrix0to1[18][8] = -0.897516876172746;
   fWeightMatrix0to1[19][8] = -3.90358690695657;
   fWeightMatrix0to1[0][9] = 1.19853636464905;
   fWeightMatrix0to1[1][9] = -0.264314831002028;
   fWeightMatrix0to1[2][9] = 6.94406708189631;
   fWeightMatrix0to1[3][9] = -5.63991929436236;
   fWeightMatrix0to1[4][9] = -0.256330932198081;
   fWeightMatrix0to1[5][9] = -0.910449182802306;
   fWeightMatrix0to1[6][9] = -0.800160961139813;
   fWeightMatrix0to1[7][9] = 0.533528712944959;
   fWeightMatrix0to1[8][9] = 0.458398484493978;
   fWeightMatrix0to1[9][9] = 0.671260696459464;
   fWeightMatrix0to1[10][9] = -1.22268874571292;
   fWeightMatrix0to1[11][9] = 0.0839042941755509;
   fWeightMatrix0to1[12][9] = 2.00561238807682;
   fWeightMatrix0to1[13][9] = 1.16799839279289;
   fWeightMatrix0to1[14][9] = 5.60568002397235;
   fWeightMatrix0to1[15][9] = 3.21935794106508;
   fWeightMatrix0to1[16][9] = 0.172276858336349;
   fWeightMatrix0to1[17][9] = -0.668543755457975;
   fWeightMatrix0to1[18][9] = -0.2342452698173;
   fWeightMatrix0to1[19][9] = -0.899162530120075;
   fWeightMatrix0to1[0][10] = 1.67291021810147;
   fWeightMatrix0to1[1][10] = -1.95829690175116;
   fWeightMatrix0to1[2][10] = 3.95580558552794;
   fWeightMatrix0to1[3][10] = -8.05484057208029;
   fWeightMatrix0to1[4][10] = 1.03980668154123;
   fWeightMatrix0to1[5][10] = 0.546499519507571;
   fWeightMatrix0to1[6][10] = -0.768401373402113;
   fWeightMatrix0to1[7][10] = 1.19221318119199;
   fWeightMatrix0to1[8][10] = 5.6782185728752;
   fWeightMatrix0to1[9][10] = 4.60848101817269;
   fWeightMatrix0to1[10][10] = -0.363136716532246;
   fWeightMatrix0to1[11][10] = -1.93902026532258;
   fWeightMatrix0to1[12][10] = -1.94322357163913;
   fWeightMatrix0to1[13][10] = 2.69051795541475;
   fWeightMatrix0to1[14][10] = 9.6390707876556;
   fWeightMatrix0to1[15][10] = -2.27478848997667;
   fWeightMatrix0to1[16][10] = -1.97300525643494;
   fWeightMatrix0to1[17][10] = -3.47588817059802;
   fWeightMatrix0to1[18][10] = -2.57009396156452;
   fWeightMatrix0to1[19][10] = -7.22956186018128;
   fWeightMatrix0to1[0][11] = -8.78774231123662;
   fWeightMatrix0to1[1][11] = 1.02686773837293;
   fWeightMatrix0to1[2][11] = 5.87941833290013;
   fWeightMatrix0to1[3][11] = -3.33224931587536;
   fWeightMatrix0to1[4][11] = 3.87467288013979;
   fWeightMatrix0to1[5][11] = -1.09557613282376;
   fWeightMatrix0to1[6][11] = 4.35580219907042;
   fWeightMatrix0to1[7][11] = -0.17582247875719;
   fWeightMatrix0to1[8][11] = -3.5242301548136;
   fWeightMatrix0to1[9][11] = 0.876714672114458;
   fWeightMatrix0to1[10][11] = 1.21357857840311;
   fWeightMatrix0to1[11][11] = 3.89745882539538;
   fWeightMatrix0to1[12][11] = -0.388417274338363;
   fWeightMatrix0to1[13][11] = -2.72276250804297;
   fWeightMatrix0to1[14][11] = 0.912315952622515;
   fWeightMatrix0to1[15][11] = -5.88340396049825;
   fWeightMatrix0to1[16][11] = -0.943125359226142;
   fWeightMatrix0to1[17][11] = 2.67198500095481;
   fWeightMatrix0to1[18][11] = 0.532534072615176;
   fWeightMatrix0to1[19][11] = -2.11541932416874;
   fWeightMatrix0to1[0][12] = -10.7290783067374;
   fWeightMatrix0to1[1][12] = -4.25218906689624;
   fWeightMatrix0to1[2][12] = -2.31213126224253;
   fWeightMatrix0to1[3][12] = -6.62542702015566;
   fWeightMatrix0to1[4][12] = -10.2373263825782;
   fWeightMatrix0to1[5][12] = 1.14752894809897;
   fWeightMatrix0to1[6][12] = -2.80984038047512;
   fWeightMatrix0to1[7][12] = 8.35171908703778;
   fWeightMatrix0to1[8][12] = 5.10613148802609;
   fWeightMatrix0to1[9][12] = -3.96130038250622;
   fWeightMatrix0to1[10][12] = -1.47432431620485;
   fWeightMatrix0to1[11][12] = -4.65875303388115;
   fWeightMatrix0to1[12][12] = 0.979044572038665;
   fWeightMatrix0to1[13][12] = 3.68899071781407;
   fWeightMatrix0to1[14][12] = 7.87426405728687;
   fWeightMatrix0to1[15][12] = -3.25031585171882;
   fWeightMatrix0to1[16][12] = 2.29699549422063;
   fWeightMatrix0to1[17][12] = -6.66381029167813;
   fWeightMatrix0to1[18][12] = 0.361871108210962;
   fWeightMatrix0to1[19][12] = -3.1561992304764;
   fWeightMatrix0to1[0][13] = 1.8043099871341;
   fWeightMatrix0to1[1][13] = 0.267150657892961;
   fWeightMatrix0to1[2][13] = 6.87773570582728;
   fWeightMatrix0to1[3][13] = 0.97943260137976;
   fWeightMatrix0to1[4][13] = -2.85383874984908;
   fWeightMatrix0to1[5][13] = -0.183176424458314;
   fWeightMatrix0to1[6][13] = -10.3353672997963;
   fWeightMatrix0to1[7][13] = 7.04477565036934;
   fWeightMatrix0to1[8][13] = -2.35034743925083;
   fWeightMatrix0to1[9][13] = -1.51872023172737;
   fWeightMatrix0to1[10][13] = -0.256881136032808;
   fWeightMatrix0to1[11][13] = 0.843487047419352;
   fWeightMatrix0to1[12][13] = -4.47173026887324;
   fWeightMatrix0to1[13][13] = -1.59835640717434;
   fWeightMatrix0to1[14][13] = -5.11739599320054;
   fWeightMatrix0to1[15][13] = -3.28040943884071;
   fWeightMatrix0to1[16][13] = 9.58715333350709;
   fWeightMatrix0to1[17][13] = -0.371685339320192;
   fWeightMatrix0to1[18][13] = -1.7475314479859;
   fWeightMatrix0to1[19][13] = 0.348751192906553;
   fWeightMatrix0to1[0][14] = 0.150198027045581;
   fWeightMatrix0to1[1][14] = -3.76491116921763;
   fWeightMatrix0to1[2][14] = 1.14474602341779;
   fWeightMatrix0to1[3][14] = -4.00486332900738;
   fWeightMatrix0to1[4][14] = 4.91487295784065;
   fWeightMatrix0to1[5][14] = -0.996451840008465;
   fWeightMatrix0to1[6][14] = -2.8039006013137;
   fWeightMatrix0to1[7][14] = 4.11066546442811;
   fWeightMatrix0to1[8][14] = -1.6581911721634;
   fWeightMatrix0to1[9][14] = 3.16502974659824;
   fWeightMatrix0to1[10][14] = -1.49586687680015;
   fWeightMatrix0to1[11][14] = 1.51015794158997;
   fWeightMatrix0to1[12][14] = -3.28143503119106;
   fWeightMatrix0to1[13][14] = 5.11593269413512;
   fWeightMatrix0to1[14][14] = -0.759990638118613;
   fWeightMatrix0to1[15][14] = -7.72242461913857;
   fWeightMatrix0to1[16][14] = -3.9266399586368;
   fWeightMatrix0to1[17][14] = 0.792943724523525;
   fWeightMatrix0to1[18][14] = -2.45735528833433;
   fWeightMatrix0to1[19][14] = -1.68800716017051;
   fWeightMatrix0to1[0][15] = -10.8746479300572;
   fWeightMatrix0to1[1][15] = 1.66269421529705;
   fWeightMatrix0to1[2][15] = 4.48380486083177;
   fWeightMatrix0to1[3][15] = 1.59308164223927;
   fWeightMatrix0to1[4][15] = -3.66902041494072;
   fWeightMatrix0to1[5][15] = -1.69575420846696;
   fWeightMatrix0to1[6][15] = -3.27688387424069;
   fWeightMatrix0to1[7][15] = -4.09259219074295;
   fWeightMatrix0to1[8][15] = -1.87408371510311;
   fWeightMatrix0to1[9][15] = 3.53199639633774;
   fWeightMatrix0to1[10][15] = 2.20868154415873;
   fWeightMatrix0to1[11][15] = -5.32997438035718;
   fWeightMatrix0to1[12][15] = -3.9010724063296;
   fWeightMatrix0to1[13][15] = 0.0563872970340297;
   fWeightMatrix0to1[14][15] = -2.50039619305373;
   fWeightMatrix0to1[15][15] = -5.71324868456916;
   fWeightMatrix0to1[16][15] = -5.07933290418845;
   fWeightMatrix0to1[17][15] = 1.44145923729762;
   fWeightMatrix0to1[18][15] = -4.92849485284382;
   fWeightMatrix0to1[19][15] = 7.49528253188181;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.701227577668038;
   fWeightMatrix1to2[0][1] = -0.622776661955494;
   fWeightMatrix1to2[0][2] = 0.844510422943427;
   fWeightMatrix1to2[0][3] = -0.457780763652049;
   fWeightMatrix1to2[0][4] = -0.809836358428171;
   fWeightMatrix1to2[0][5] = 2.83018432564895;
   fWeightMatrix1to2[0][6] = -0.438808001060369;
   fWeightMatrix1to2[0][7] = 0.666186037791165;
   fWeightMatrix1to2[0][8] = -11.5257211898389;
   fWeightMatrix1to2[0][9] = -1.13292844301322;
   fWeightMatrix1to2[0][10] = -3.31118529526167;
   fWeightMatrix1to2[0][11] = -0.821708515786315;
   fWeightMatrix1to2[0][12] = -0.757445657899617;
   fWeightMatrix1to2[0][13] = -1.32923106661431;
   fWeightMatrix1to2[0][14] = -1.2138665680251;
   fWeightMatrix1to2[0][15] = 0.808909904426998;
   fWeightMatrix1to2[0][16] = -0.8494127998532;
   fWeightMatrix1to2[0][17] = -1.55384519492258;
   fWeightMatrix1to2[0][18] = 1.07937717651475;
   fWeightMatrix1to2[0][19] = -6.94259227083985;
   fWeightMatrix1to2[0][20] = -2.75915500423305;
}

inline double ReadMLPBFGS::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)15) {
      std::cout << "Input vector needs to be of size " << 15 << std::endl;
      return 0;
   }

   std::array<double, 21> fWeights1 {{}};
   std::array<double, 1> fWeights2 {{}};
   fWeights1.back() = 1.;

   // layer 0 to 1
   for (int o=0; o<20; o++) {
      std::array<double, 16> buffer; // no need to initialise
      for (int i = 0; i<16 - 1; i++) {
         buffer[i] = fWeightMatrix0to1[o][i] * inputValues[i];
      } // loop over i
      buffer.back() = fWeightMatrix0to1[o][15];
      for (int i=0; i<16; i++) {
         fWeights1[o] += buffer[i];
      } // loop over i
    } // loop over o
   for (int o=0; o<20; o++) {
      fWeights1[o] = ActivationFnc(fWeights1[o]);
   } // loop over o
   // layer 1 to 2
   for (int o=0; o<1; o++) {
      std::array<double, 21> buffer; // no need to initialise
      for (int i=0; i<21; i++) {
         buffer[i] = fWeightMatrix1to2[o][i] * fWeights1[i];
      } // loop over i
      for (int i=0; i<21; i++) {
         fWeights2[o] += buffer[i];
      } // loop over i
    } // loop over o
   for (int o=0; o<1; o++) {
      fWeights2[o] = OutputActivationFnc(fWeights2[o]);
   } // loop over o

   return fWeights2[0];
}

double ReadMLPBFGS::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLPBFGS::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}

// Clean up
inline void ReadMLPBFGS::Clear()
{
}
inline double ReadMLPBFGS::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         std::vector<double> iV(inputValues);
         Transform( iV, -1 );
         retval = GetMvaValue__( iV );
   }

   return retval;
}

//_______________________________________________________________________
inline void ReadMLPBFGS::InitTransform_1()
{
   double fMin_1[3][15];
   double fMax_1[3][15];
   // Normalization transformation, initialisation
   fMin_1[0][0] = 65.125;
   fMax_1[0][0] = 104.9375;
   fScal_1[0][0] = 2.0/(fMax_1[0][0]-fMin_1[0][0]);
   fOff_1[0][0] = fMin_1[0][0]*fScal_1[0][0]+1.;
   fMin_1[1][0] = 65.0625;
   fMax_1[1][0] = 104.9375;
   fScal_1[1][0] = 2.0/(fMax_1[1][0]-fMin_1[1][0]);
   fOff_1[1][0] = fMin_1[1][0]*fScal_1[1][0]+1.;
   fMin_1[2][0] = 65.0625;
   fMax_1[2][0] = 104.9375;
   fScal_1[2][0] = 2.0/(fMax_1[2][0]-fMin_1[2][0]);
   fOff_1[2][0] = fMin_1[2][0]*fScal_1[2][0]+1.;
   fMin_1[0][1] = 0.0703273266554;
   fMax_1[0][1] = 0.548578202724;
   fScal_1[0][1] = 2.0/(fMax_1[0][1]-fMin_1[0][1]);
   fOff_1[0][1] = fMin_1[0][1]*fScal_1[0][1]+1.;
   fMin_1[1][1] = 0.0682255253196;
   fMax_1[1][1] = 0.549910068512;
   fScal_1[1][1] = 2.0/(fMax_1[1][1]-fMin_1[1][1]);
   fOff_1[1][1] = fMin_1[1][1]*fScal_1[1][1]+1.;
   fMin_1[2][1] = 0.0682255253196;
   fMax_1[2][1] = 0.549910068512;
   fScal_1[2][1] = 2.0/(fMax_1[2][1]-fMin_1[2][1]);
   fOff_1[2][1] = fMin_1[2][1]*fScal_1[2][1]+1.;
   fMin_1[0][2] = -2.494140625;
   fMax_1[0][2] = 2.470703125;
   fScal_1[0][2] = 2.0/(fMax_1[0][2]-fMin_1[0][2]);
   fOff_1[0][2] = fMin_1[0][2]*fScal_1[0][2]+1.;
   fMin_1[1][2] = -2.498046875;
   fMax_1[1][2] = 2.49951171875;
   fScal_1[1][2] = 2.0/(fMax_1[1][2]-fMin_1[1][2]);
   fOff_1[1][2] = fMin_1[1][2]*fScal_1[1][2]+1.;
   fMin_1[2][2] = -2.498046875;
   fMax_1[2][2] = 2.49951171875;
   fScal_1[2][2] = 2.0/(fMax_1[2][2]-fMin_1[2][2]);
   fOff_1[2][2] = fMin_1[2][2]*fScal_1[2][2]+1.;
   fMin_1[0][3] = 2;
   fMax_1[0][3] = 8;
   fScal_1[0][3] = 2.0/(fMax_1[0][3]-fMin_1[0][3]);
   fOff_1[0][3] = fMin_1[0][3]*fScal_1[0][3]+1.;
   fMin_1[1][3] = 2;
   fMax_1[1][3] = 11;
   fScal_1[1][3] = 2.0/(fMax_1[1][3]-fMin_1[1][3]);
   fOff_1[1][3] = fMin_1[1][3]*fScal_1[1][3]+1.;
   fMin_1[2][3] = 2;
   fMax_1[2][3] = 11;
   fScal_1[2][3] = 2.0/(fMax_1[2][3]-fMin_1[2][3]);
   fOff_1[2][3] = fMin_1[2][3]*fScal_1[2][3]+1.;
   fMin_1[0][4] = -4.2705078125;
   fMax_1[0][4] = 4.6123046875;
   fScal_1[0][4] = 2.0/(fMax_1[0][4]-fMin_1[0][4]);
   fOff_1[0][4] = fMin_1[0][4]*fScal_1[0][4]+1.;
   fMin_1[1][4] = -4.66796875;
   fMax_1[1][4] = 5.01953125;
   fScal_1[1][4] = 2.0/(fMax_1[1][4]-fMin_1[1][4]);
   fOff_1[1][4] = fMin_1[1][4]*fScal_1[1][4]+1.;
   fMin_1[2][4] = -4.66796875;
   fMax_1[2][4] = 5.01953125;
   fScal_1[2][4] = 2.0/(fMax_1[2][4]-fMin_1[2][4]);
   fOff_1[2][4] = fMin_1[2][4]*fScal_1[2][4]+1.;
   fMin_1[0][5] = 50.2703475952;
   fMax_1[0][5] = 1335.79541016;
   fScal_1[0][5] = 2.0/(fMax_1[0][5]-fMin_1[0][5]);
   fOff_1[0][5] = fMin_1[0][5]*fScal_1[0][5]+1.;
   fMin_1[1][5] = 50.0678367615;
   fMax_1[1][5] = 1970.49926758;
   fScal_1[1][5] = 2.0/(fMax_1[1][5]-fMin_1[1][5]);
   fOff_1[1][5] = fMin_1[1][5]*fScal_1[1][5]+1.;
   fMin_1[2][5] = 50.0678367615;
   fMax_1[2][5] = 1970.49926758;
   fScal_1[2][5] = 2.0/(fMax_1[2][5]-fMin_1[2][5]);
   fOff_1[2][5] = fMin_1[2][5]*fScal_1[2][5]+1.;
   fMin_1[0][6] = -1;
   fMax_1[0][6] = 0.99951171875;
   fScal_1[0][6] = 2.0/(fMax_1[0][6]-fMin_1[0][6]);
   fOff_1[0][6] = fMin_1[0][6]*fScal_1[0][6]+1.;
   fMin_1[1][6] = -1;
   fMax_1[1][6] = 1;
   fScal_1[1][6] = 2.0/(fMax_1[1][6]-fMin_1[1][6]);
   fOff_1[1][6] = fMin_1[1][6]*fScal_1[1][6]+1.;
   fMin_1[2][6] = -1;
   fMax_1[2][6] = 1;
   fScal_1[2][6] = 2.0/(fMax_1[2][6]-fMin_1[2][6]);
   fOff_1[2][6] = fMin_1[2][6]*fScal_1[2][6]+1.;
   fMin_1[0][7] = -4.830078125;
   fMax_1[0][7] = 4.822265625;
   fScal_1[0][7] = 2.0/(fMax_1[0][7]-fMin_1[0][7]);
   fOff_1[0][7] = fMin_1[0][7]*fScal_1[0][7]+1.;
   fMin_1[1][7] = -5.0771484375;
   fMax_1[1][7] = 5.0888671875;
   fScal_1[1][7] = 2.0/(fMax_1[1][7]-fMin_1[1][7]);
   fOff_1[1][7] = fMin_1[1][7]*fScal_1[1][7]+1.;
   fMin_1[2][7] = -5.0771484375;
   fMax_1[2][7] = 5.0888671875;
   fScal_1[2][7] = 2.0/(fMax_1[2][7]-fMin_1[2][7]);
   fOff_1[2][7] = fMin_1[2][7]*fScal_1[2][7]+1.;
   fMin_1[0][8] = 50.0087356567;
   fMax_1[0][8] = 656.952087402;
   fScal_1[0][8] = 2.0/(fMax_1[0][8]-fMin_1[0][8]);
   fOff_1[0][8] = fMin_1[0][8]*fScal_1[0][8]+1.;
   fMin_1[1][8] = 50.0047340393;
   fMax_1[1][8] = 1175.74890137;
   fScal_1[1][8] = 2.0/(fMax_1[1][8]-fMin_1[1][8]);
   fOff_1[1][8] = fMin_1[1][8]*fScal_1[1][8]+1.;
   fMin_1[2][8] = 50.0047340393;
   fMax_1[2][8] = 1175.74890137;
   fScal_1[2][8] = 2.0/(fMax_1[2][8]-fMin_1[2][8]);
   fOff_1[2][8] = fMin_1[2][8]*fScal_1[2][8]+1.;
   fMin_1[0][9] = -1;
   fMax_1[0][9] = 0.99951171875;
   fScal_1[0][9] = 2.0/(fMax_1[0][9]-fMin_1[0][9]);
   fOff_1[0][9] = fMin_1[0][9]*fScal_1[0][9]+1.;
   fMin_1[1][9] = -1;
   fMax_1[1][9] = 1;
   fScal_1[1][9] = 2.0/(fMax_1[1][9]-fMin_1[1][9]);
   fOff_1[1][9] = fMin_1[1][9]*fScal_1[1][9]+1.;
   fMin_1[2][9] = -1;
   fMax_1[2][9] = 1;
   fScal_1[2][9] = 2.0/(fMax_1[2][9]-fMin_1[2][9]);
   fOff_1[2][9] = fMin_1[2][9]*fScal_1[2][9]+1.;
   fMin_1[0][10] = 2.50122070312;
   fMax_1[0][10] = 8.2470703125;
   fScal_1[0][10] = 2.0/(fMax_1[0][10]-fMin_1[0][10]);
   fOff_1[0][10] = fMin_1[0][10]*fScal_1[0][10]+1.;
   fMin_1[1][10] = 2.50006103516;
   fMax_1[1][10] = 9.2822265625;
   fScal_1[1][10] = 2.0/(fMax_1[1][10]-fMin_1[1][10]);
   fOff_1[1][10] = fMin_1[1][10]*fScal_1[1][10]+1.;
   fMin_1[2][10] = 2.50006103516;
   fMax_1[2][10] = 9.2822265625;
   fScal_1[2][10] = 2.0/(fMax_1[2][10]-fMin_1[2][10]);
   fOff_1[2][10] = fMin_1[2][10]*fScal_1[2][10]+1.;
   fMin_1[0][11] = -5.84900569916;
   fMax_1[0][11] = 6.13960266113;
   fScal_1[0][11] = 2.0/(fMax_1[0][11]-fMin_1[0][11]);
   fOff_1[0][11] = fMin_1[0][11]*fScal_1[0][11]+1.;
   fMin_1[1][11] = -7.53327178955;
   fMax_1[1][11] = 7.36832284927;
   fScal_1[1][11] = 2.0/(fMax_1[1][11]-fMin_1[1][11]);
   fOff_1[1][11] = fMin_1[1][11]*fScal_1[1][11]+1.;
   fMin_1[2][11] = -7.53327178955;
   fMax_1[2][11] = 7.36832284927;
   fScal_1[2][11] = 2.0/(fMax_1[2][11]-fMin_1[2][11]);
   fOff_1[2][11] = fMin_1[2][11]*fScal_1[2][11]+1.;
   fMin_1[0][12] = 500.611633301;
   fMax_1[0][12] = 7465.87548828;
   fScal_1[0][12] = 2.0/(fMax_1[0][12]-fMin_1[0][12]);
   fOff_1[0][12] = fMin_1[0][12]*fScal_1[0][12]+1.;
   fMin_1[1][12] = 500.026428223;
   fMax_1[1][12] = 7649.34521484;
   fScal_1[1][12] = 2.0/(fMax_1[1][12]-fMin_1[1][12]);
   fOff_1[1][12] = fMin_1[1][12]*fScal_1[1][12]+1.;
   fMin_1[2][12] = 500.026428223;
   fMax_1[2][12] = 7649.34521484;
   fScal_1[2][12] = 2.0/(fMax_1[2][12]-fMin_1[2][12]);
   fOff_1[2][12] = fMin_1[2][12]*fScal_1[2][12]+1.;
   fMin_1[0][13] = -3.64942932129;
   fMax_1[0][13] = 4.19094085693;
   fScal_1[0][13] = 2.0/(fMax_1[0][13]-fMin_1[0][13]);
   fOff_1[0][13] = fMin_1[0][13]*fScal_1[0][13]+1.;
   fMin_1[1][13] = -4.53909301758;
   fMax_1[1][13] = 4.37330627441;
   fScal_1[1][13] = 2.0/(fMax_1[1][13]-fMin_1[1][13]);
   fOff_1[1][13] = fMin_1[1][13]*fScal_1[1][13]+1.;
   fMin_1[2][13] = -4.53909301758;
   fMax_1[2][13] = 4.37330627441;
   fScal_1[2][13] = 2.0/(fMax_1[2][13]-fMin_1[2][13]);
   fOff_1[2][13] = fMin_1[2][13]*fScal_1[2][13]+1.;
   fMin_1[0][14] = -4.21001291275;
   fMax_1[0][14] = 4.69680309296;
   fScal_1[0][14] = 2.0/(fMax_1[0][14]-fMin_1[0][14]);
   fOff_1[0][14] = fMin_1[0][14]*fScal_1[0][14]+1.;
   fMin_1[1][14] = -6.87152099609;
   fMax_1[1][14] = 6.03112888336;
   fScal_1[1][14] = 2.0/(fMax_1[1][14]-fMin_1[1][14]);
   fOff_1[1][14] = fMin_1[1][14]*fScal_1[1][14]+1.;
   fMin_1[2][14] = -6.87152099609;
   fMax_1[2][14] = 6.03112888336;
   fScal_1[2][14] = 2.0/(fMax_1[2][14]-fMin_1[2][14]);
   fOff_1[2][14] = fMin_1[2][14]*fScal_1[2][14]+1.;
}

//_______________________________________________________________________
inline void ReadMLPBFGS::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 15;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) {
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
      indicesGet.push_back( 11);
      indicesGet.push_back( 12);
      indicesGet.push_back( 13);
      indicesGet.push_back( 14);
   }
   if ( indicesPut.empty() ) {
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
      indicesPut.push_back( 11);
      indicesPut.push_back( 12);
      indicesPut.push_back( 13);
      indicesPut.push_back( 14);
   }

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<15;ivar++) {
      double offset = fOff_1[cls][ivar];
      double scale  = fScal_1[cls][ivar];
      iv[indicesPut.at(ivar)] = scale*dv[ivar]-offset;
   }
}

//_______________________________________________________________________
inline void ReadMLPBFGS::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLPBFGS::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
