// Class: ReadFisher
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : Fisher::Fisher
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.24/02       [399362]
Creator        : markm
Date           : Fri Dec  3 11:11:37 2021
Host           : Linux Manjaro-Desktop 5.10.52-1-MANJARO #1 SMP PREEMPT Tue Jul 20 20:32:02 UTC 2021 x86_64 GNU/Linux
Dir            : /home/markm/Documents/research/vbsTMVA
Training events: 40895496
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
CreateMVAPdfs: "True" [Create PDFs for classifier outputs (signal and background)]
Method: "Fisher" [Discrimination method]
# Default:
VerbosityLevel: "Default" [Verbosity level]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 15
bos_PuppiAK8_m_sd0_corr       bos_PuppiAK8_m_sd0_corr       bos_PuppiAK8_m_sd0_corr       bos_PuppiAK8_m_sd0_corr                                         'F'    [-999,150]
bos_PuppiAK8_tau2tau1         bos_PuppiAK8_tau2tau1         bos_PuppiAK8_tau2tau1         bos_PuppiAK8_tau2tau1                                           'F'    [-999,0.975631773472]
lep1_eta                      lep1_eta                      lep1_eta                      lep1_eta                                                        'F'    [-2.5,2.5]
nJet30f                       nJet30f                       nJet30f                       nJet30f                                                         'F'    [0,26]
vbf1_AK4_eta                  vbf1_AK4_eta                  vbf1_AK4_eta                  vbf1_AK4_eta                                                    'F'    [-6.5361328125,8.474609375]
vbf1_AK4_pt                   vbf1_AK4_pt                   vbf1_AK4_pt                   vbf1_AK4_pt                                                     'F'    [26.5299701691,4225.88134766]
vbf1_AK4_qgid                 vbf1_AK4_qgid                 vbf1_AK4_qgid                 vbf1_AK4_qgid                                                   'F'    [-1,1]
vbf2_AK4_eta                  vbf2_AK4_eta                  vbf2_AK4_eta                  vbf2_AK4_eta                                                    'F'    [-7.259765625,8.572265625]
vbf2_AK4_pt                   vbf2_AK4_pt                   vbf2_AK4_pt                   vbf2_AK4_pt                                                     'F'    [15.9609375,2962.71142578]
vbf2_AK4_qgid                 vbf2_AK4_qgid                 vbf2_AK4_qgid                 vbf2_AK4_qgid                                                   'F'    [-1,1]
vbf_deta                      vbf_deta                      vbf_deta                      vbf_deta                                                        'F'    [0.0010843873024,12.5283203125]
vbf_eta                       vbf_eta                       vbf_eta                       vbf_eta                                                         'F'    [-11.8072061539,11.371840477]
vbf_m                         vbf_m                         vbf_m                         vbf_m                                                           'F'    [500,20178.7988281]
zeppHad                       zeppHad                       zeppHad                       zeppHad                                                         'F'    [-10.5598869324,10.0429420471]
zeppLep                       zeppLep                       zeppLep                       zeppLep                                                         'F'    [-10.3560142517,9.88655757904]
NSpec 50
bos_AK4AK4_eta                bos_AK4AK4_eta                bos_AK4AK4_eta                bos_AK4AK4_eta                                                  'F'    [-999,10.3288640976]
bos_AK4AK4_m                  bos_AK4AK4_m                  bos_AK4AK4_m                  bos_AK4AK4_m                                                    'F'    [-999,150]
bos_AK4AK4_pt                 bos_AK4AK4_pt                 bos_AK4AK4_pt                 bos_AK4AK4_pt                                                   'F'    [-999,2413.82006836]
bosCent                       bosCent                       bosCent                       bosCent                                                         'F'    [-999,4.99509382248]
bos_j1_AK4_eta                bos_j1_AK4_eta                bos_j1_AK4_eta                bos_j1_AK4_eta                                                  'F'    [-999,2.39990234375]
bos_j1_AK4_pt                 bos_j1_AK4_pt                 bos_j1_AK4_pt                 bos_j1_AK4_pt                                                   'F'    [-999,2384.28466797]
bos_j2_AK4_eta                bos_j2_AK4_eta                bos_j2_AK4_eta                bos_j2_AK4_eta                                                  'F'    [-999,2.39990234375]
bos_j2_AK4_pt                 bos_j2_AK4_pt                 bos_j2_AK4_pt                 bos_j2_AK4_pt                                                   'F'    [-999,347.97845459]
bos_PuppiAK8_eta              bos_PuppiAK8_eta              bos_PuppiAK8_eta              bos_PuppiAK8_eta                                                'F'    [-999,2.39990234375]
bos_PuppiAK8_m_sd0            bos_PuppiAK8_m_sd0            bos_PuppiAK8_m_sd0            bos_PuppiAK8_m_sd0                                              'F'    [-999,150]
bos_PuppiAK8_phi              bos_PuppiAK8_phi              bos_PuppiAK8_phi              bos_PuppiAK8_phi                                                'F'    [-999,3.1416015625]
bos_PuppiAK8_pt               bos_PuppiAK8_pt               bos_PuppiAK8_pt               bos_PuppiAK8_pt                                                 'F'    [-999,5104]
btagWeight_loose              btagWeight_loose              btagWeight_loose              btagWeight_loose                                                'F'    [0.447307109833,13.2104187012]
dibos_eta                     dibos_eta                     dibos_eta                     dibos_eta                                                       'F'    [-11.4983072281,9.63391304016]
dibos_m                       dibos_m                       dibos_m                       dibos_m                                                         'F'    [58.2915344238,8954.79492188]
dibos_mt                      dibos_mt                      dibos_mt                      dibos_mt                                                        'F'    [93.8312911987,8979.48046875]
dibos_phi                     dibos_phi                     dibos_phi                     dibos_phi                                                       'F'    [-3.14159250259,3.14159250259]
dibos_pt                      dibos_pt                      dibos_pt                      dibos_pt                                                        'F'    [0.00839652307332,3803.23413086]
dilep_eta                     dilep_eta                     dilep_eta                     dilep_eta                                                       'F'    [-8.93682479858,8.14235591888]
dilep_m                       dilep_m                       dilep_m                       dilep_m                                                         'F'    [0.0201578587294,8670.07519531]
dilep_mt                      dilep_mt                      dilep_mt                      dilep_mt                                                        'F'    [19.9676761627,8688.1484375]
dilep_phi                     dilep_phi                     dilep_phi                     dilep_phi                                                       'F'    [-3.14159226418,3.14159250259]
dilep_pt                      dilep_pt                      dilep_pt                      dilep_pt                                                        'F'    [0.0267982333899,4062.7902832]
evt                           evt                           evt                           evt                                                             'F'    [1,388342784]
genWeight                     genWeight                     genWeight                     genWeight                                                       'F'    [-316.46875,393.6875]
gid                           gid                           gid                           gid                                                             'F'    [1,15]
L1PFWeight                    L1PFWeight                    L1PFWeight                    L1PFWeight                                                      'F'    [0.0185788460076,1]
lep1_iso                      lep1_iso                      lep1_iso                      lep1_iso                                                        'F'    [0,0.249999508262]
lep1_m                        lep1_m                        lep1_m                        lep1_m                                                          'F'    [0.000510999991093,0.105658374727]
lep1_phi                      lep1_phi                      lep1_phi                      lep1_phi                                                        'F'    [-3.1416015625,3.1416015625]
lep1_pt                       lep1_pt                       lep1_pt                       lep1_pt                                                         'F'    [19.4174823761,4569.44287109]
lep1_q                        lep1_q                        lep1_q                        lep1_q                                                          'F'    [-1,1]
lep2_eta                      lep2_eta                      lep2_eta                      lep2_eta                                                        'F'    [-999,2.5]
lep2_pt                       lep2_pt                       lep2_pt                       lep2_pt                                                         'F'    [-999,1498.7755127]
mcWeight                      mcWeight                      mcWeight                      mcWeight                                                        'F'    [3.87841064819e-10,0.000135022753966]
MET                           MET                           MET                           MET                                                             'F'    [0.0120055703446,4010.60888672]
MET_phi                       MET_phi                       MET_phi                       MET_phi                                                         'F'    [-3.14159226418,3.14159250259]
nBtag_loose                   nBtag_loose                   nBtag_loose                   nBtag_loose                                                     'F'    [0,10]
nBtag_medium                  nBtag_medium                  nBtag_medium                  nBtag_medium                                                    'F'    [0,7]
neu_pz_type0                  neu_pz_type0                  neu_pz_type0                  neu_pz_type0                                                    'F'    [-999,-999]
nJet30                        nJet30                        nJet30                        nJet30                                                          'F'    [0,26]
nJet50                        nJet50                        nJet50                        nJet50                                                          'F'    [0,14]
nPV                           nPV                           nPV                           nPV                                                             'F'    [1,141]
puWeight                      puWeight                      puWeight                      puWeight                                                        'F'    [0,46.9509277344]
run                           run                           run                           run                                                             'F'    [1,1]
sid                           sid                           sid                           sid                                                             'F'    [100,1100]
vbf1_AK4_phi                  vbf1_AK4_phi                  vbf1_AK4_phi                  vbf1_AK4_phi                                                    'F'    [-3.1416015625,3.1416015625]
vbf2_AK4_phi                  vbf2_AK4_phi                  vbf2_AK4_phi                  vbf2_AK4_phi                                                    'F'    [-3.1416015625,3.1416015625]
vbf_phi                       vbf_phi                       vbf_phi                       vbf_phi                                                         'F'    [-3.14159274101,3.14159250259]
vbf_pt                        vbf_pt                        vbf_pt                        vbf_pt                                                          'F'    [0.0176219400018,3886.2199707]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadFisher : public IClassifierReader {

 public:

   // constructor
   ReadFisher( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadFisher" ),
        fNvars( 15 )
   {
      // the training input variables
      const char* inputVars[] = { "bos_PuppiAK8_m_sd0_corr", "bos_PuppiAK8_tau2tau1", "lep1_eta", "nJet30f", "vbf1_AK4_eta", "vbf1_AK4_pt", "vbf1_AK4_qgid", "vbf2_AK4_eta", "vbf2_AK4_pt", "vbf2_AK4_qgid", "vbf_deta", "vbf_eta", "vbf_m", "zeppHad", "zeppLep" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadFisher() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[15];
   double fVmax[15];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[15];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   double              fFisher0;
   std::vector<double> fFisherCoefficients;
};

inline void ReadFisher::Initialize() 
{
   fFisher0 = -0.00250532661565;
   fFisherCoefficients.push_back( 0.00140537725396 );
   fFisherCoefficients.push_back( -0.0014567198198 );
   fFisherCoefficients.push_back( -0.000293386755084 );
   fFisherCoefficients.push_back( 0.0243499908575 );
   fFisherCoefficients.push_back( 0.000141027966516 );
   fFisherCoefficients.push_back( -0.000186647445634 );
   fFisherCoefficients.push_back( 0.0433421627493 );
   fFisherCoefficients.push_back( 0.000126516230223 );
   fFisherCoefficients.push_back( -0.000249026324164 );
   fFisherCoefficients.push_back( 0.0457422581703 );
   fFisherCoefficients.push_back( -0.0569053084664 );
   fFisherCoefficients.push_back( -4.00724464218e-05 );
   fFisherCoefficients.push_back( 0.000118765457879 );
   fFisherCoefficients.push_back( -4.21150192523e-05 );
   fFisherCoefficients.push_back( 0.000291145278655 );

   // sanity check
   if (fFisherCoefficients.size() != fNvars) {
      std::cout << "Problem in class \"" << fClassName << "\"::Initialize: mismatch in number of input values"
                << fFisherCoefficients.size() << " != " << fNvars << std::endl;
      fStatusIsClean = false;
   }         
}

inline double ReadFisher::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double retval = fFisher0;
   for (size_t ivar = 0; ivar < fNvars; ivar++) {
      retval += fFisherCoefficients[ivar]*inputValues[ivar];
   }

   return retval;
}

// Clean up
inline void ReadFisher::Clear() 
{
   // clear coefficients
   fFisherCoefficients.clear(); 
}
inline double ReadFisher::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         retval = GetMvaValue__( inputValues );
   }

   return retval;
}
