#ifndef vbsReducedTree_hpp
#define vbsReducedTree_hpp
//////////////////////////////////////////////////////////
// This class has been automatically generated on
// Sun May 30 15:13:58 EDT 2021
// from TTree Events
// found on file: DYJetsToLL_M-50_HT-100to200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_01.root
//////////////////////////////////////////////////////////
//VbsReducedEvent structure (keeps variables of the VbsAnalysisReduced ntuple)
typedef struct {
//Additional branches - to be added
   Int_t           gid;                  // - group  ID
   Int_t           sid;                  // - sample ID
   Float_t         mcWeight;             //== xsect/ngen 
//
   // Declaration of leaf types

Float_t AK4_jetjet_deltaeta;
Float_t AK4_jetjet_deltaphi;
Float_t AK4_jetjet_deltar;
Float_t AK4_jetjet_mass;
Float_t AK4_jetjet_pt;
Float_t AK8_e_gen;
Float_t AK8_eta_gen;
Float_t AK8_jetID_loose;
Float_t AK8_mass_gen;
Float_t AK8_phi_gen;
Float_t AK8_pruned_mass_gen;
Float_t AK8_pt_gen;
Float_t AK8_softdrop_mass_gen;
Float_t AK8_softdrop_pt_gen;
Float_t AK8jet_e2_sdb05;
Float_t AK8jet_e2_sdb1;
Float_t AK8jet_e2_sdb2;
Float_t AK8jet_e2_sdb4;
Float_t AK8jet_e3_b1;
Float_t AK8jet_e3_b2;
Float_t AK8jet_e3_sdb05;
Float_t AK8jet_e3_sdb1;
Float_t AK8jet_e3_sdb2;
Float_t AK8jet_e3_sdb4;
Float_t AK8jet_e3_v1_b1;
Float_t AK8jet_e3_v1_b2;
Float_t AK8jet_e3_v1_sdb05;
Float_t AK8jet_e3_v1_sdb1;
Float_t AK8jet_e3_v1_sdb2;
Float_t AK8jet_e3_v1_sdb4;
Float_t AK8jet_e3_v2_b1;
Float_t AK8jet_e3_v2_b2;
Float_t AK8jet_e3_v2_sdb05;
Float_t AK8jet_e3_v2_sdb1;
Float_t AK8jet_e3_v2_sdb2;
Float_t AK8jet_e3_v2_sdb4;
Float_t AK8jet_e4_v1_b1;
Float_t AK8jet_e4_v1_b2;
Float_t AK8jet_e4_v1_sdb05;
Float_t AK8jet_e4_v1_sdb1;
Float_t AK8jet_e4_v1_sdb2;
Float_t AK8jet_e4_v1_sdb4;
Float_t AK8jet_e4_v2_b1;
Float_t AK8jet_e4_v2_b2;
Float_t AK8jet_e4_v2_sdb05;
Float_t AK8jet_e4_v2_sdb1;
Float_t AK8jet_e4_v2_sdb2;
Float_t AK8jet_e4_v2_sdb4;
Float_t AK8jet_mass;
Float_t AK8jet_mass_fi;
Float_t AK8jet_mass_pr;
Float_t AK8jet_mass_so;
Float_t AK8jet_mass_tr;
Float_t AK8jet_pt_so;
Float_t AK8jet_qjet;
Float_t AK8jet_sj1_eta;
Float_t AK8jet_sj1_m;
Float_t AK8jet_sj1_phi;
Float_t AK8jet_sj1_pt;
Float_t AK8jet_sj1_q;
Float_t AK8jet_sj2_eta;
Float_t AK8jet_sj2_m;
Float_t AK8jet_sj2_phi;
Float_t AK8jet_sj2_pt;
Float_t AK8jet_sj2_q;
Float_t AK8jet_tau2tau1;
Float_t PuppiAK4_jetjet_deltaeta;
Float_t PuppiAK4_jetjet_deltaphi;
Float_t PuppiAK4_jetjet_deltar;
Float_t PuppiAK4_jetjet_mass;
Float_t PuppiAK4_jetjet_pt;
Float_t PuppiAK8_jetID_loose;
Float_t PuppiAK8_jet_mass;
Float_t PuppiAK8_jet_mass_fi;
Float_t PuppiAK8_jet_mass_pr;
Float_t PuppiAK8_jet_mass_so;
Float_t PuppiAK8_jet_mass_so_corr;
Float_t PuppiAK8_jet_mass_tr;
Float_t PuppiAK8_jet_pt_so;
Float_t PuppiAK8_jet_sj1_eta;
Float_t PuppiAK8_jet_sj1_m;
Float_t PuppiAK8_jet_sj1_phi;
Float_t PuppiAK8_jet_sj1_pt;
Float_t PuppiAK8_jet_sj1_q;
Float_t PuppiAK8_jet_sj2_eta;
Float_t PuppiAK8_jet_sj2_m;
Float_t PuppiAK8_jet_sj2_phi;
Float_t PuppiAK8_jet_sj2_pt;
Float_t PuppiAK8_jet_sj2_q;
Float_t PuppiAK8_jet_tau2tau1;
Float_t PuppiAK8jet_e2_sdb05;
Float_t PuppiAK8jet_e2_sdb1;
Float_t PuppiAK8jet_e2_sdb2;
Float_t PuppiAK8jet_e2_sdb4;
Float_t PuppiAK8jet_e3_b1;
Float_t PuppiAK8jet_e3_b2;
Float_t PuppiAK8jet_e3_sdb05;
Float_t PuppiAK8jet_e3_sdb1;
Float_t PuppiAK8jet_e3_sdb2;
Float_t PuppiAK8jet_e3_sdb4;
Float_t PuppiAK8jet_e3_v1_b1;
Float_t PuppiAK8jet_e3_v1_b2;
Float_t PuppiAK8jet_e3_v1_sdb05;
Float_t PuppiAK8jet_e3_v1_sdb1;
Float_t PuppiAK8jet_e3_v1_sdb2;
Float_t PuppiAK8jet_e3_v1_sdb4;
Float_t PuppiAK8jet_e3_v2_b1;
Float_t PuppiAK8jet_e3_v2_b2;
Float_t PuppiAK8jet_e3_v2_sdb05;
Float_t PuppiAK8jet_e3_v2_sdb1;
Float_t PuppiAK8jet_e3_v2_sdb2;
Float_t PuppiAK8jet_e3_v2_sdb4;
Float_t PuppiAK8jet_e4_v1_b1;
Float_t PuppiAK8jet_e4_v1_b2;
Float_t PuppiAK8jet_e4_v1_sdb05;
Float_t PuppiAK8jet_e4_v1_sdb1;
Float_t PuppiAK8jet_e4_v1_sdb2;
Float_t PuppiAK8jet_e4_v1_sdb4;
Float_t PuppiAK8jet_e4_v2_b1;
Float_t PuppiAK8jet_e4_v2_b2;
Float_t PuppiAK8jet_e4_v2_sdb05;
Float_t PuppiAK8jet_e4_v2_sdb1;
Float_t PuppiAK8jet_e4_v2_sdb2;
Float_t PuppiAK8jet_e4_v2_sdb4;
Float_t PuppiAK8jet_qjet;
Float_t WW_mT_gen;
Float_t WW_mass_gen;
Float_t WW_pT_gen;
Float_t W_pt_gen;
Float_t W_pz_gen;
Float_t W_rap_gen;
Float_t hadW_e_gen;
Float_t hadW_eta_gen;
Float_t hadW_m_gen;
Float_t hadW_phi_gen;
Float_t hadW_pt_gen;
Float_t lepW_e_gen;
Float_t lepW_eta_gen;
Float_t lepW_m_gen;
Float_t lepW_phi_gen;
Float_t lepW_pt_gen;
Float_t lep_eta_gen;
Float_t lep_pt_gen;
Float_t nu_eta_gen;
Float_t nu_phi_gen;
Float_t nu_pt_gen;
Float_t nu_pz_gen;
Float_t ttb_jet_mass_fi;
Float_t ttb_jet_mass_pr;
Float_t ttb_jet_mass_so;
Float_t ttb_jet_mass_tr;
Float_t ttb_jet_pt_so;
Float_t ttb_jet_tau2tau1;
Int_t		event;
Int_t		isPuppiVBF;
Int_t		isVBF;
Int_t		issignal;
Int_t		issignal_AK4jetjet;
Int_t		issignal_PuppiAK4jetjet;
Int_t		issignal_PuppiAK8;
Int_t		l_charge1;
Int_t		l_charge2;
Int_t		lumi;
Int_t		nBTagJetPuppi_loose;
Int_t		nBTagJetPuppi_loose_unmerged;
Int_t		nBTagJetPuppi_medium;
Int_t		nBTagJetPuppi_medium_unmerged;
Int_t		nBTagJetPuppi_tight;
Int_t		nBTagJetPuppi_tight_unmerged;
Int_t		nBTagJet_loose;
Int_t		nBTagJet_loose_unmerged;
Int_t		nBTagJet_medium;
Int_t		nBTagJet_medium_unmerged;
Int_t		nBTagJet_tight;
Int_t		nBTagJet_tight_unmerged;
Int_t		nEvents;
Int_t		nGoodAK8jets;
Int_t		nGoodPuppiAK8jets;
Int_t		nNegEvents;
Int_t		nPV;
Int_t		nTotEvents;
Int_t		nTotNegEvents;
Int_t		njets;
Int_t		njetsPuppi;
Int_t		njetsPuppi_unmerged;
Int_t		njets_unmerged;
Int_t		nu_pz_isre;
Int_t		nu_pz_run2_type;
Int_t		run;
Int_t		type;
Int_t		ungroomed_AK8jet_charge;
Int_t		ungroomed_PuppiAK8_jet_charge;
Int_t		vbf_maxpt_j1_charge;
Int_t		vbf_maxpt_j2_charge;
Float_t		AK4Puppi_DR_GENRECO_11;
Float_t		AK4Puppi_DR_GENRECO_12;
Float_t		AK4Puppi_DR_GENRECO_21;
Float_t		AK4Puppi_DR_GENRECO_22;
Float_t		AK4_1_e_gen;
Float_t		AK4_1_eta_gen;
Float_t		AK4_1_mass_gen;
Float_t		AK4_1_phi_gen;
Float_t		AK4_1_pt_gen;
Float_t		AK4_2_e_gen;
Float_t		AK4_2_eta_gen;
Float_t		AK4_2_mass_gen;
Float_t		AK4_2_phi_gen;
Float_t		AK4_2_pt_gen;
Float_t		AK4_DR_GENRECO_11;
Float_t		AK4_DR_GENRECO_12;
Float_t		AK4_DR_GENRECO_21;
Float_t		AK4_DR_GENRECO_22;
Float_t		AK4_jet1_e;
Float_t		AK4_jet1_eta;
Float_t		AK4_jet1_phi;
Float_t		AK4_jet1_pt;
Float_t		AK4_jet1_pt_jer;
Float_t		AK4_jet1_pt_jer_dn;
Float_t		AK4_jet1_pt_jer_up;
Float_t		AK4_jet1_pt_jes_dn;
Float_t		AK4_jet1_pt_jes_up;
Float_t		AK4_jet2_e;
Float_t		AK4_jet2_eta;
Float_t		AK4_jet2_phi;
Float_t		AK4_jet2_pt;
Float_t		AK4_jet2_pt_jer;
Float_t		AK4_jet2_pt_jer_dn;
Float_t		AK4_jet2_pt_jer_up;
Float_t		AK4_jet2_pt_jes_dn;
Float_t		AK4_jet2_pt_jes_up;
Float_t		AK4_jj_DeltaEta_gen;
Float_t		AK4_jj_mass_gen;
Float_t		AK8_closerjet_e;
Float_t		AK8_closerjet_eta;
Float_t		AK8_closerjet_phi;
Float_t		AK8_closerjet_pt;
Float_t		AK8jet_mass_pr_jer;
Float_t		AK8jet_mass_pr_jer_dn;
Float_t		AK8jet_mass_pr_jer_up;
Float_t		AK8jet_mass_pr_jes_dn;
Float_t		AK8jet_mass_pr_jes_up;
Float_t		BosonCentralityPuppi_run2;
Float_t		BosonCentralityPuppi_type0;
Float_t		BosonCentralityPuppi_type2;
Float_t		BosonCentrality_2Lep;
Float_t		BosonCentrality_2Lep_LEP_Down;
Float_t		BosonCentrality_2Lep_LEP_Up;
Float_t		BosonCentrality_2Lep_jes_dn;
Float_t		BosonCentrality_2Lep_jes_up;
Float_t		BosonCentrality_run2;
Float_t		BosonCentrality_type0;
Float_t		BosonCentrality_type0_LEP_Down;
Float_t		BosonCentrality_type0_LEP_Up;
Float_t		BosonCentrality_type0_jer_dn;
Float_t		BosonCentrality_type0_jer_up;
Float_t		BosonCentrality_type0_jes_dn;
Float_t		BosonCentrality_type0_jes_up;
Float_t		BosonCentrality_type2;
Float_t		HadWEta;
Float_t		HadWRapidity;
Float_t		L1_Prefweight;
Float_t		L1_PrefweightDown;
Float_t		L1_PrefweightUp;
Float_t		LHEWeight;
Float_t		LepWEta;
Float_t		LepWRapidity;
Float_t		LeptonProjectionPuppi_run2;
Float_t		LeptonProjectionPuppi_type0;
Float_t		LeptonProjectionPuppi_type2;
Float_t		LeptonProjection_2Lep;
Float_t		LeptonProjection_run2;
Float_t		LeptonProjection_type0;
Float_t		LeptonProjection_type2;
Float_t		PtBalancePuppi_run2;
Float_t		PtBalancePuppi_type0;
Float_t		PtBalancePuppi_type2;
Float_t		PtBalance_2Lep;
Float_t		PtBalance_run2;
Float_t		PtBalance_type0;
Float_t		PtBalance_type0_LEP_Down;
Float_t		PtBalance_type0_LEP_Up;
Float_t		PtBalance_type0_jer_dn;
Float_t		PtBalance_type0_jer_up;
Float_t		PtBalance_type0_jes_dn;
Float_t		PtBalance_type0_jes_up;
Float_t		PtBalance_type2;
Float_t		PuppiAK4_jet1_e;
Float_t		PuppiAK4_jet1_eta;
Float_t		PuppiAK4_jet1_phi;
Float_t		PuppiAK4_jet1_pt;
Float_t		PuppiAK4_jet1_pt_jer;
Float_t		PuppiAK4_jet1_pt_jer_dn;
Float_t		PuppiAK4_jet1_pt_jer_up;
Float_t		PuppiAK4_jet1_pt_jes_dn;
Float_t		PuppiAK4_jet1_pt_jes_up;
Float_t		PuppiAK4_jet2_e;
Float_t		PuppiAK4_jet2_eta;
Float_t		PuppiAK4_jet2_phi;
Float_t		PuppiAK4_jet2_pt;
Float_t		PuppiAK4_jet2_pt_jer;
Float_t		PuppiAK4_jet2_pt_jer_dn;
Float_t		PuppiAK4_jet2_pt_jer_up;
Float_t		PuppiAK4_jet2_pt_jes_dn;
Float_t		PuppiAK4_jet2_pt_jes_up;
Float_t		PuppiAK8_jet_mass_pr_jer;
Float_t		PuppiAK8_jet_mass_pr_jer_dn;
Float_t		PuppiAK8_jet_mass_pr_jer_up;
Float_t		PuppiAK8_jet_mass_pr_jes_dn;
Float_t		PuppiAK8_jet_mass_pr_jes_up;
Float_t		RpTPuppi_run2;
Float_t		RpTPuppi_type0;
Float_t		RpTPuppi_type2;
Float_t		RpT_2Lep;
Float_t		RpT_run2;
Float_t		RpT_type0;
Float_t		RpT_type2;
Float_t		VBSCentralityPuppi_run2;
Float_t		VBSCentralityPuppi_type0;
Float_t		VBSCentralityPuppi_type2;
Float_t		VBSCentrality_2Lep;
Float_t		VBSCentrality_run2;
Float_t		VBSCentrality_type0;
Float_t		VBSCentrality_type2;
Float_t		WWEta;
Float_t		WWEta_PuppiAK8;
Float_t		WWRapidity;
Float_t		WWRapidity_PuppiAK8;
Float_t		ZeppenfeldWH;
Float_t		ZeppenfeldWHPuppi;
Float_t		ZeppenfeldWH_jes_dn;
Float_t		ZeppenfeldWH_jes_up;
Float_t		ZeppenfeldWLPuppi_run2;
Float_t		ZeppenfeldWLPuppi_type0;
Float_t		ZeppenfeldWLPuppi_type2;
Float_t		ZeppenfeldWL_2Lep;
Float_t		ZeppenfeldWL_2Lep_LEP_Down;
Float_t		ZeppenfeldWL_2Lep_LEP_Up;
Float_t		ZeppenfeldWL_2Lep_jes_dn;
Float_t		ZeppenfeldWL_2Lep_jes_up;
Float_t		ZeppenfeldWL_run2;
Float_t		ZeppenfeldWL_type0;
Float_t		ZeppenfeldWL_type0_LEP_Down;
Float_t		ZeppenfeldWL_type0_LEP_Up;
Float_t		ZeppenfeldWL_type0_jer_dn;
Float_t		ZeppenfeldWL_type0_jer_up;
Float_t		ZeppenfeldWL_type0_jes_dn;
Float_t		ZeppenfeldWL_type0_jes_up;
Float_t		ZeppenfeldWL_type2;
Float_t		btag0Wgt;
Float_t		btag0WgtDownHF;
Float_t		btag0WgtDownLF;
Float_t		btag0WgtUpHF;
Float_t		btag0WgtUpLF;
Float_t		btag1Wgt;
Float_t		btag1WgtDownHF;
Float_t		btag1WgtDownLF;
Float_t		btag1WgtUpHF;
Float_t		btag1WgtUpLF;
Float_t		btag2Wgt;
Float_t		costheta1Puppi_run2;
Float_t		costheta1Puppi_type0;
Float_t		costheta1Puppi_type2;
Float_t		costheta1_2Lep;
Float_t		costheta1_run2;
Float_t		costheta1_type0;
Float_t		costheta1_type2;
Float_t		costheta2Puppi_run2;
Float_t		costheta2Puppi_type0;
Float_t		costheta2Puppi_type2;
Float_t		costheta2_2Lep;
Float_t		costheta2_run2;
Float_t		costheta2_type0;
Float_t		costheta2_type2;
Float_t		costhetastarPuppi_run2;
Float_t		costhetastarPuppi_type0;
Float_t		costhetastarPuppi_type2;
Float_t		costhetastar_2Lep;
Float_t		costhetastar_run2;
Float_t		costhetastar_type0;
Float_t		costhetastar_type2;
Float_t		deltaR_AK8_closestBtagJet;
Float_t		deltaR_AK8_closestBtagJet_loose;
Float_t		deltaR_VLepPuppiak8jet;
Float_t		deltaR_Wjet_GenReco;
Float_t		deltaR_l2Puppiak8jet;
Float_t		deltaR_lPuppiak4jetjet;
Float_t		deltaR_lPuppiak8jet;
Float_t		deltaR_lak4jetjet;
Float_t		deltaR_lak8jet;
Float_t		deltaphi_METPuppiak4jetjet;
Float_t		deltaphi_METPuppiak8jet;
Float_t		deltaphi_METak4jetjet;
Float_t		deltaphi_METak8jet;
Float_t		deltaphi_METmin;
Float_t		deltaphi_METvbfJ1;
Float_t		deltaphi_METvbfJ2;
Float_t		deltaphi_VPuppiak4jetjet;
Float_t		deltaphi_VPuppiak8jet;
Float_t		deltaphi_Vak4jetjet;
Float_t		deltaphi_Vak8jet;
Float_t		dilep_eta;
Float_t		dilep_eta_Down;
Float_t		dilep_eta_Up;
Float_t		dilep_m;
Float_t		dilep_m_Down;
Float_t		dilep_m_Up;
Float_t		dilep_phi;
Float_t		dilep_phi_Down;
Float_t		dilep_phi_Up;
Float_t		dilep_pt;
Float_t		dilep_pt_Down;
Float_t		dilep_pt_Up;
Float_t		energy_lvj_run2_PuppiAK8;
Float_t		energy_lvj_type0_PuppiAK8;
Float_t		energy_lvj_type2_PuppiAK8;
Float_t		eta_llj_PuppiAK8;
Float_t		eta_lvj_run2_PuppiAK8;
Float_t		eta_lvj_type0_PuppiAK8;
Float_t		eta_lvj_type2_PuppiAK8;
Float_t		genWeight;
Float_t		gen_top1_pt;
Float_t		gen_top2_pt;
Float_t		id_eff_Weight;
Float_t		id_eff_Weight2;
Float_t		id_eff_Weight2_Down;
Float_t		id_eff_Weight2_Up;
Float_t		id_eff_Weight_Down;
Float_t		id_eff_Weight_Up;
Float_t		isGen;
Float_t		jet2_btag;
Float_t		jet2_e;
Float_t		jet2_eta;
Float_t		jet2_phi;
Float_t		jet2_pt;
Float_t		jet3_btag;
Float_t		jet3_e;
Float_t		jet3_eta;
Float_t		jet3_phi;
Float_t		jet3_pt;
Float_t		l_e1;
Float_t		l_e2;
Float_t		l_eta1;
Float_t		l_eta1_Down;
Float_t		l_eta1_Up;
Float_t		l_eta2;
Float_t		l_iso1;
Float_t		l_iso2;
Float_t		l_phi1;
Float_t		l_phi2;
Float_t		l_pt1;
Float_t		l_pt1_Down;
Float_t		l_pt1_Up;
Float_t		l_pt2;
Float_t		l_pt2_Down;
Float_t		l_pt2_Up;
Float_t		mass_leptonic_closerjet;
Float_t		mass_llj_PuppiAK8;
Float_t		mass_llj_PuppiAK8_LEP_Down;
Float_t		mass_llj_PuppiAK8_LEP_Up;
Float_t		mass_llj_PuppiAK8_jes_dn;
Float_t		mass_llj_PuppiAK8_jes_up;
Float_t		mass_lvj_run2;
Float_t		mass_lvj_run2_PuppiAK8;
Float_t		mass_lvj_type0;
Float_t		mass_lvj_type0_PuppiAK8;
Float_t		mass_lvj_type0_PuppiAK8_LEP_Down;
Float_t		mass_lvj_type0_PuppiAK8_LEP_Up;
Float_t		mass_lvj_type0_PuppiAK8_jer_dn;
Float_t		mass_lvj_type0_PuppiAK8_jer_up;
Float_t		mass_lvj_type0_PuppiAK8_jes_dn;
Float_t		mass_lvj_type0_PuppiAK8_jes_up;
Float_t		mass_lvj_type0_met_PuppiAK8_jes_dn;
Float_t		mass_lvj_type0_met_PuppiAK8_jes_up;
Float_t		mass_lvj_type0_met_jer;
Float_t		mass_lvj_type0_met_jer_dn;
Float_t		mass_lvj_type0_met_jer_up;
Float_t		mass_lvj_type0_met_jes_dn;
Float_t		mass_lvj_type0_met_jes_up;
Float_t		mass_lvj_type2;
Float_t		mass_lvj_type2_PuppiAK8;
Float_t		mass_lvjj_run2_AK4;
Float_t		mass_lvjj_run2_PuppiAK4;
Float_t		mass_lvjj_type0_AK4;
Float_t		mass_lvjj_type0_PuppiAK4;
Float_t		mass_lvjj_type0_met_jes_dn_AK4;
Float_t		mass_lvjj_type0_met_jes_dn_PuppiAK4;
Float_t		mass_lvjj_type0_met_jes_up_AK4;
Float_t		mass_lvjj_type0_met_jes_up_PuppiAK4;
Float_t		mass_lvjj_type2_AK4;
Float_t		mass_lvjj_type2_PuppiAK4;
Float_t		mass_ungroomedjet_closerjet;
Float_t		mt_lvj_run2_PuppiAK8;
Float_t		mt_lvj_type0_PuppiAK8;
Float_t		mt_lvj_type2_PuppiAK8;
Float_t		nu_pz_run2;
Float_t		nu_pz_run2_oth;
Float_t		nu_pz_type0;
Float_t		nu_pz_type2;
Float_t		pfMET;
Float_t		pfMET_Corr;
Float_t		pfMET_Corr_Cov00;
Float_t		pfMET_Corr_Cov01;
Float_t		pfMET_Corr_Cov11;
Float_t		pfMET_Corr_jendn;
Float_t		pfMET_Corr_jenup;
Float_t		pfMET_Corr_jerdn;
Float_t		pfMET_Corr_jerup;
Float_t		pfMET_Corr_jrsdn;
Float_t		pfMET_Corr_jrsup;
Float_t		pfMET_Corr_phi;
Float_t		pfMET_Corr_phijendn;
Float_t		pfMET_Corr_phijenup;
Float_t		pfMET_Corr_phijerdn;
Float_t		pfMET_Corr_phijerup;
Float_t		pfMET_Corr_phijrsdn;
Float_t		pfMET_Corr_phijrsup;
Float_t		pfMET_Corr_phiuncdn;
Float_t		pfMET_Corr_phiuncup;
Float_t		pfMET_Corr_uncdn;
Float_t		pfMET_Corr_uncup;
Float_t		pfMET_Phi;
Float_t		pfMET_jes_dn;
Float_t		pfMET_jes_up;
Float_t		pfMETpuppi;
Float_t		pfMETpuppi_Corr;
Float_t		pfMETpuppi_Corr_Cov00;
Float_t		pfMETpuppi_Corr_Cov01;
Float_t		pfMETpuppi_Corr_Cov11;
Float_t		pfMETpuppi_Corr_phi;
Float_t		pfMETpuppi_Cov00;
Float_t		pfMETpuppi_Cov01;
Float_t		pfMETpuppi_Cov11;
Float_t		pfMETpuppi_Phi;
Float_t		pfMETpuppi_jer;
Float_t		pfMETpuppi_jer_dn;
Float_t		pfMETpuppi_jer_up;
Float_t		pfMETpuppi_jes_dn;
Float_t		pfMETpuppi_jes_up;
Float_t		phi1Puppi_run2;
Float_t		phi1Puppi_type0;
Float_t		phi1Puppi_type2;
Float_t		phi1_2Lep;
Float_t		phi1_run2;
Float_t		phi1_type0;
Float_t		phi1_type2;
Float_t		phiPuppi_run2;
Float_t		phiPuppi_type0;
Float_t		phiPuppi_type2;
Float_t		phi_2Lep;
Float_t		phi_llj_PuppiAK8;
Float_t		phi_lvj_run2_PuppiAK8;
Float_t		phi_lvj_type0_PuppiAK8;
Float_t		phi_lvj_type2_PuppiAK8;
Float_t		phi_run2;
Float_t		phi_type0;
Float_t		phi_type2;
Float_t		pt_llj_PuppiAK8;
Float_t		pt_lvj_run2_PuppiAK8;
Float_t		pt_lvj_type0_PuppiAK8;
Float_t		pt_lvj_type2_PuppiAK8;
Float_t		pu_Weight;
Float_t		pu_Weight_down;
Float_t		pu_Weight_up;
Float_t		rapidity_lvj_run2_PuppiAK8;
Float_t		rapidity_lvj_type0_PuppiAK8;
Float_t		rapidity_lvj_type2_PuppiAK8;
Float_t		top1_NNLO_Weight;
Float_t		top2_NNLO_Weight;
Float_t		totalEventWeight;
Float_t		totalEventWeight_2;
Float_t		totalEventWeight_2Lep;
Float_t		totalEventWeight_3;
Float_t		trig_eff_Weight;
Float_t		trig_eff_Weight2;
Float_t		trig_eff_Weight2_Down;
Float_t		trig_eff_Weight2_Up;
Float_t		trig_eff_Weight_Down;
Float_t		trig_eff_Weight_Up;
Float_t		ttb_deltaeta_lak8jet;
Float_t		ttb_ungroomed_jet_e;
Float_t		ttb_ungroomed_jet_eta;
Float_t		ttb_ungroomed_jet_phi;
Float_t		ttb_ungroomed_jet_pt;
Float_t		ungroomed_AK8jet_e;
Float_t		ungroomed_AK8jet_eta;
Float_t		ungroomed_AK8jet_eta_jes_dn;
Float_t		ungroomed_AK8jet_eta_jes_up;
Float_t		ungroomed_AK8jet_mass_jes_dn;
Float_t		ungroomed_AK8jet_mass_jes_up;
Float_t		ungroomed_AK8jet_phi;
Float_t		ungroomed_AK8jet_phi_jes_dn;
Float_t		ungroomed_AK8jet_phi_jes_up;
Float_t		ungroomed_AK8jet_pt;
Float_t		ungroomed_AK8jet_pt_jer;
Float_t		ungroomed_AK8jet_pt_jer_dn;
Float_t		ungroomed_AK8jet_pt_jer_up;
Float_t		ungroomed_AK8jet_pt_jes_dn;
Float_t		ungroomed_AK8jet_pt_jes_up;
Float_t		ungroomed_PuppiAK8_jet_e;
Float_t		ungroomed_PuppiAK8_jet_eta;
Float_t		ungroomed_PuppiAK8_jet_eta_jes_dn;
Float_t		ungroomed_PuppiAK8_jet_eta_jes_up;
Float_t		ungroomed_PuppiAK8_jet_mass_jes_dn;
Float_t		ungroomed_PuppiAK8_jet_mass_jes_up;
Float_t		ungroomed_PuppiAK8_jet_phi;
Float_t		ungroomed_PuppiAK8_jet_phi_jes_dn;
Float_t		ungroomed_PuppiAK8_jet_phi_jes_up;
Float_t		ungroomed_PuppiAK8_jet_pt;
Float_t		ungroomed_PuppiAK8_jet_pt_jer;
Float_t		ungroomed_PuppiAK8_jet_pt_jer_dn;
Float_t		ungroomed_PuppiAK8_jet_pt_jer_up;
Float_t		ungroomed_PuppiAK8_jet_pt_jes_dn;
Float_t		ungroomed_PuppiAK8_jet_pt_jes_up;
Float_t		v_eta_run2;
Float_t		v_eta_type0;
Float_t		v_eta_type0_jer_dn;
Float_t		v_eta_type0_jer_up;
Float_t		v_eta_type0_jes_dn;
Float_t		v_eta_type0_jes_up;
Float_t		v_eta_type2;
Float_t		v_mass_run2;
Float_t		v_mass_type0;
Float_t		v_mass_type0_jer_dn;
Float_t		v_mass_type0_jer_up;
Float_t		v_mass_type0_jes_dn;
Float_t		v_mass_type0_jes_up;
Float_t		v_mass_type2;
Float_t		v_mt_run2;
Float_t		v_mt_type0;
Float_t		v_mt_type0_jer_dn;
Float_t		v_mt_type0_jer_up;
Float_t		v_mt_type0_jes_dn;
Float_t		v_mt_type0_jes_up;
Float_t		v_mt_type2;
Float_t		v_phi;
Float_t		v_pt_run2;
Float_t		v_pt_type0;
Float_t		v_pt_type0_jer_dn;
Float_t		v_pt_type0_jer_up;
Float_t		v_pt_type0_jes_dn;
Float_t		v_pt_type0_jes_up;
Float_t		v_pt_type2;
Float_t		v_puppi_eta_run2;
Float_t		v_puppi_eta_type0;
Float_t		v_puppi_eta_type2;
Float_t		v_puppi_mass_run2;
Float_t		v_puppi_mass_type0;
Float_t		v_puppi_mass_type2;
Float_t		v_puppi_mt_run2;
Float_t		v_puppi_mt_type0;
Float_t		v_puppi_mt_type2;
Float_t		v_puppi_phi;
Float_t		v_puppi_pt_run2;
Float_t		v_puppi_pt_type0;
Float_t		v_puppi_pt_type2;
Float_t		vbfPuppi_maxpt_deltaR;
Float_t		vbfPuppi_maxpt_j1_ID;
Float_t		vbfPuppi_maxpt_j1_bDiscriminatorCSV;
Float_t		vbfPuppi_maxpt_j1_e;
Float_t		vbfPuppi_maxpt_j1_eta;
Float_t		vbfPuppi_maxpt_j1_eta_jer;
Float_t		vbfPuppi_maxpt_j1_eta_jer_dn;
Float_t		vbfPuppi_maxpt_j1_eta_jer_up;
Float_t		vbfPuppi_maxpt_j1_eta_jes_dn;
Float_t		vbfPuppi_maxpt_j1_eta_jes_up;
Float_t		vbfPuppi_maxpt_j1_phi;
Float_t		vbfPuppi_maxpt_j1_pt;
Float_t		vbfPuppi_maxpt_j1_pt_jer;
Float_t		vbfPuppi_maxpt_j1_pt_jer_dn;
Float_t		vbfPuppi_maxpt_j1_pt_jer_up;
Float_t		vbfPuppi_maxpt_j1_pt_jes_dn;
Float_t		vbfPuppi_maxpt_j1_pt_jes_up;
Float_t		vbfPuppi_maxpt_j2_ID;
Float_t		vbfPuppi_maxpt_j2_bDiscriminatorCSV;
Float_t		vbfPuppi_maxpt_j2_e;
Float_t		vbfPuppi_maxpt_j2_eta;
Float_t		vbfPuppi_maxpt_j2_eta_jer;
Float_t		vbfPuppi_maxpt_j2_eta_jer_dn;
Float_t		vbfPuppi_maxpt_j2_eta_jer_up;
Float_t		vbfPuppi_maxpt_j2_eta_jes_dn;
Float_t		vbfPuppi_maxpt_j2_eta_jes_up;
Float_t		vbfPuppi_maxpt_j2_phi;
Float_t		vbfPuppi_maxpt_j2_pt;
Float_t		vbfPuppi_maxpt_j2_pt_jer;
Float_t		vbfPuppi_maxpt_j2_pt_jer_dn;
Float_t		vbfPuppi_maxpt_j2_pt_jer_up;
Float_t		vbfPuppi_maxpt_j2_pt_jes_dn;
Float_t		vbfPuppi_maxpt_j2_pt_jes_up;
Float_t		vbfPuppi_maxpt_jj_Deta;
Float_t		vbfPuppi_maxpt_jj_eta;
Float_t		vbfPuppi_maxpt_jj_m;
Float_t		vbfPuppi_maxpt_jj_phi;
Float_t		vbfPuppi_maxpt_jj_pt;
Float_t		vbf_maxpt_deltaR;
Float_t		vbf_maxpt_j1_bDiscriminatorCSV;
Float_t		vbf_maxpt_j1_e;
Float_t		vbf_maxpt_j1_eta;
Float_t		vbf_maxpt_j1_eta_jer;
Float_t		vbf_maxpt_j1_eta_jer_dn;
Float_t		vbf_maxpt_j1_eta_jer_up;
Float_t		vbf_maxpt_j1_eta_jes_dn;
Float_t		vbf_maxpt_j1_eta_jes_up;
Float_t		vbf_maxpt_j1_mass;
Float_t		vbf_maxpt_j1_mass_jes_dn;
Float_t		vbf_maxpt_j1_mass_jes_up;
Float_t		vbf_maxpt_j1_phi;
Float_t		vbf_maxpt_j1_phi_jes_dn;
Float_t		vbf_maxpt_j1_phi_jes_up;
Float_t		vbf_maxpt_j1_pt;
Float_t		vbf_maxpt_j1_pt_jer;
Float_t		vbf_maxpt_j1_pt_jer_dn;
Float_t		vbf_maxpt_j1_pt_jer_up;
Float_t		vbf_maxpt_j1_pt_jes_dn;
Float_t		vbf_maxpt_j1_pt_jes_up;
Float_t		vbf_maxpt_j2_bDiscriminatorCSV;
Float_t		vbf_maxpt_j2_e;
Float_t		vbf_maxpt_j2_eta;
Float_t		vbf_maxpt_j2_eta_jer;
Float_t		vbf_maxpt_j2_eta_jer_dn;
Float_t		vbf_maxpt_j2_eta_jer_up;
Float_t		vbf_maxpt_j2_eta_jes_dn;
Float_t		vbf_maxpt_j2_eta_jes_up;
Float_t		vbf_maxpt_j2_mass;
Float_t		vbf_maxpt_j2_mass_jes_dn;
Float_t		vbf_maxpt_j2_mass_jes_up;
Float_t		vbf_maxpt_j2_phi;
Float_t		vbf_maxpt_j2_phi_jes_dn;
Float_t		vbf_maxpt_j2_phi_jes_up;
Float_t		vbf_maxpt_j2_pt;
Float_t		vbf_maxpt_j2_pt_jer;
Float_t		vbf_maxpt_j2_pt_jer_dn;
Float_t		vbf_maxpt_j2_pt_jer_up;
Float_t		vbf_maxpt_j2_pt_jes_dn;
Float_t		vbf_maxpt_j2_pt_jes_up;
Float_t		vbf_maxpt_jj_Deta;
Float_t		vbf_maxpt_jj_Deta_jes_dn;
Float_t		vbf_maxpt_jj_Deta_jes_up;
Float_t		vbf_maxpt_jj_eta;
Float_t		vbf_maxpt_jj_m;
Float_t		vbf_maxpt_jj_m_jes_dn;
Float_t		vbf_maxpt_jj_m_jes_up;
Float_t		vbf_maxpt_jj_phi;
Float_t		vbf_maxpt_jj_pt;
Float_t		vbf_maxpt_jj_pt_jes_dn;
Float_t		vbf_maxpt_jj_pt_jes_up;
Float_t		wSampleWeight;
} VbsReducedEvent;
//
//===================================================================================
void addBranches_vbsReducedTree(TTree* vbsTree, VbsReducedEvent& vbsEvent){
  // if(vbsTree->GetBranch( "gid")){
   cout << "Adding branches" << endl;
   vbsTree->Branch( "gid",                &vbsEvent.gid,              "gid/I");
   vbsTree->Branch( "sid",                &vbsEvent.sid,              "sid/I");
   vbsTree->Branch( "mcWeight",           &vbsEvent.mcWeight,         "mcWeight/F");
  //}
}
//=================================================================================== 
void arrange_vbsReducedTree(TTree* vbsTree, VbsReducedEvent& vbsEvent){
//Maps the vbsTree branches to members of local  vbsEvent structure
//Extra Branhes
//if(vbsTree->GetBranch( "gid") ) {
   cout << " Set extra branches" << endl;
      
    vbsTree->SetBranchAddress( "gid",                                      &vbsEvent.gid    );
    vbsTree->SetBranchAddress( "sid",                                      &vbsEvent.sid    );
    vbsTree->SetBranchAddress( "mcWeight",                                 &vbsEvent.mcWeight );
    cout << " Done Set extra branches" << endl;
	 vbsTree->SetBranchAddress( "AK4_jetjet_deltaeta", 	 &vbsEvent.AK4_jetjet_deltaeta );
	 vbsTree->SetBranchAddress( "AK4_jetjet_deltaphi", 	 &vbsEvent.AK4_jetjet_deltaphi );
	 vbsTree->SetBranchAddress( "AK4_jetjet_deltar", 	 &vbsEvent.AK4_jetjet_deltar );
	 vbsTree->SetBranchAddress( "AK4_jetjet_mass", 	 &vbsEvent.AK4_jetjet_mass );
	 vbsTree->SetBranchAddress( "AK4_jetjet_pt", 	 &vbsEvent.AK4_jetjet_pt );
	 vbsTree->SetBranchAddress( "AK8_e_gen", 	 &vbsEvent.AK8_e_gen );
	 vbsTree->SetBranchAddress( "AK8_eta_gen", 	 &vbsEvent.AK8_eta_gen );
	 vbsTree->SetBranchAddress( "AK8_jetID_loose", 	 &vbsEvent.AK8_jetID_loose );
	 vbsTree->SetBranchAddress( "AK8_mass_gen", 	 &vbsEvent.AK8_mass_gen );
	 vbsTree->SetBranchAddress( "AK8_phi_gen", 	 &vbsEvent.AK8_phi_gen );
	 vbsTree->SetBranchAddress( "AK8_pruned_mass_gen", 	 &vbsEvent.AK8_pruned_mass_gen );
	 vbsTree->SetBranchAddress( "AK8_pt_gen", 	 &vbsEvent.AK8_pt_gen );
	 vbsTree->SetBranchAddress( "AK8_softdrop_mass_gen", 	 &vbsEvent.AK8_softdrop_mass_gen );
	 vbsTree->SetBranchAddress( "AK8_softdrop_pt_gen", 	 &vbsEvent.AK8_softdrop_pt_gen );
	 vbsTree->SetBranchAddress( "AK8jet_e2_sdb05", 	 &vbsEvent.AK8jet_e2_sdb05 );
	 vbsTree->SetBranchAddress( "AK8jet_e2_sdb1", 	 &vbsEvent.AK8jet_e2_sdb1 );
	 vbsTree->SetBranchAddress( "AK8jet_e2_sdb2", 	 &vbsEvent.AK8jet_e2_sdb2 );
	 vbsTree->SetBranchAddress( "AK8jet_e2_sdb4", 	 &vbsEvent.AK8jet_e2_sdb4 );
	 vbsTree->SetBranchAddress( "AK8jet_e3_b1", 	 &vbsEvent.AK8jet_e3_b1 );
	 vbsTree->SetBranchAddress( "AK8jet_e3_b2", 	 &vbsEvent.AK8jet_e3_b2 );
	 vbsTree->SetBranchAddress( "AK8jet_e3_sdb05", 	 &vbsEvent.AK8jet_e3_sdb05 );
	 vbsTree->SetBranchAddress( "AK8jet_e3_sdb1", 	 &vbsEvent.AK8jet_e3_sdb1 );
	 vbsTree->SetBranchAddress( "AK8jet_e3_sdb2", 	 &vbsEvent.AK8jet_e3_sdb2 );
	 vbsTree->SetBranchAddress( "AK8jet_e3_sdb4", 	 &vbsEvent.AK8jet_e3_sdb4 );
	 vbsTree->SetBranchAddress( "AK8jet_e3_v1_b1", 	 &vbsEvent.AK8jet_e3_v1_b1 );
	 vbsTree->SetBranchAddress( "AK8jet_e3_v1_b2", 	 &vbsEvent.AK8jet_e3_v1_b2 );
	 vbsTree->SetBranchAddress( "AK8jet_e3_v1_sdb05", 	 &vbsEvent.AK8jet_e3_v1_sdb05 );
	 vbsTree->SetBranchAddress( "AK8jet_e3_v1_sdb1", 	 &vbsEvent.AK8jet_e3_v1_sdb1 );
	 vbsTree->SetBranchAddress( "AK8jet_e3_v1_sdb2", 	 &vbsEvent.AK8jet_e3_v1_sdb2 );
	 vbsTree->SetBranchAddress( "AK8jet_e3_v1_sdb4", 	 &vbsEvent.AK8jet_e3_v1_sdb4 );
	 vbsTree->SetBranchAddress( "AK8jet_e3_v2_b1", 	 &vbsEvent.AK8jet_e3_v2_b1 );
	 vbsTree->SetBranchAddress( "AK8jet_e3_v2_b2", 	 &vbsEvent.AK8jet_e3_v2_b2 );
	 vbsTree->SetBranchAddress( "AK8jet_e3_v2_sdb05", 	 &vbsEvent.AK8jet_e3_v2_sdb05 );
	 vbsTree->SetBranchAddress( "AK8jet_e3_v2_sdb1", 	 &vbsEvent.AK8jet_e3_v2_sdb1 );
	 vbsTree->SetBranchAddress( "AK8jet_e3_v2_sdb2", 	 &vbsEvent.AK8jet_e3_v2_sdb2 );
	 vbsTree->SetBranchAddress( "AK8jet_e3_v2_sdb4", 	 &vbsEvent.AK8jet_e3_v2_sdb4 );
	 vbsTree->SetBranchAddress( "AK8jet_e4_v1_b1", 	 &vbsEvent.AK8jet_e4_v1_b1 );
	 vbsTree->SetBranchAddress( "AK8jet_e4_v1_b2", 	 &vbsEvent.AK8jet_e4_v1_b2 );
	 vbsTree->SetBranchAddress( "AK8jet_e4_v1_sdb05", 	 &vbsEvent.AK8jet_e4_v1_sdb05 );
	 vbsTree->SetBranchAddress( "AK8jet_e4_v1_sdb1", 	 &vbsEvent.AK8jet_e4_v1_sdb1 );
	 vbsTree->SetBranchAddress( "AK8jet_e4_v1_sdb2", 	 &vbsEvent.AK8jet_e4_v1_sdb2 );
	 vbsTree->SetBranchAddress( "AK8jet_e4_v1_sdb4", 	 &vbsEvent.AK8jet_e4_v1_sdb4 );
	 vbsTree->SetBranchAddress( "AK8jet_e4_v2_b1", 	 &vbsEvent.AK8jet_e4_v2_b1 );
	 vbsTree->SetBranchAddress( "AK8jet_e4_v2_b2", 	 &vbsEvent.AK8jet_e4_v2_b2 );
	 vbsTree->SetBranchAddress( "AK8jet_e4_v2_sdb05", 	 &vbsEvent.AK8jet_e4_v2_sdb05 );
	 vbsTree->SetBranchAddress( "AK8jet_e4_v2_sdb1", 	 &vbsEvent.AK8jet_e4_v2_sdb1 );
	 vbsTree->SetBranchAddress( "AK8jet_e4_v2_sdb2", 	 &vbsEvent.AK8jet_e4_v2_sdb2 );
	 vbsTree->SetBranchAddress( "AK8jet_e4_v2_sdb4", 	 &vbsEvent.AK8jet_e4_v2_sdb4 );
	 vbsTree->SetBranchAddress( "AK8jet_mass", 	 &vbsEvent.AK8jet_mass );
	 vbsTree->SetBranchAddress( "AK8jet_mass_fi", 	 &vbsEvent.AK8jet_mass_fi );
	 vbsTree->SetBranchAddress( "AK8jet_mass_pr", 	 &vbsEvent.AK8jet_mass_pr );
	 vbsTree->SetBranchAddress( "AK8jet_mass_so", 	 &vbsEvent.AK8jet_mass_so );
	 vbsTree->SetBranchAddress( "AK8jet_mass_tr", 	 &vbsEvent.AK8jet_mass_tr );
	 vbsTree->SetBranchAddress( "AK8jet_pt_so", 	 &vbsEvent.AK8jet_pt_so );
	 vbsTree->SetBranchAddress( "AK8jet_qjet", 	 &vbsEvent.AK8jet_qjet );
	 vbsTree->SetBranchAddress( "AK8jet_sj1_eta", 	 &vbsEvent.AK8jet_sj1_eta );
	 vbsTree->SetBranchAddress( "AK8jet_sj1_m", 	 &vbsEvent.AK8jet_sj1_m );
	 vbsTree->SetBranchAddress( "AK8jet_sj1_phi", 	 &vbsEvent.AK8jet_sj1_phi );
	 vbsTree->SetBranchAddress( "AK8jet_sj1_pt", 	 &vbsEvent.AK8jet_sj1_pt );
	 vbsTree->SetBranchAddress( "AK8jet_sj1_q", 	 &vbsEvent.AK8jet_sj1_q );
	 vbsTree->SetBranchAddress( "AK8jet_sj2_eta", 	 &vbsEvent.AK8jet_sj2_eta );
	 vbsTree->SetBranchAddress( "AK8jet_sj2_m", 	 &vbsEvent.AK8jet_sj2_m );
	 vbsTree->SetBranchAddress( "AK8jet_sj2_phi", 	 &vbsEvent.AK8jet_sj2_phi );
	 vbsTree->SetBranchAddress( "AK8jet_sj2_pt", 	 &vbsEvent.AK8jet_sj2_pt );
	 vbsTree->SetBranchAddress( "AK8jet_sj2_q", 	 &vbsEvent.AK8jet_sj2_q );
	 vbsTree->SetBranchAddress( "AK8jet_tau2tau1", 	 &vbsEvent.AK8jet_tau2tau1 );
	 vbsTree->SetBranchAddress( "PuppiAK4_jetjet_deltaeta", 	 &vbsEvent.PuppiAK4_jetjet_deltaeta );
	 vbsTree->SetBranchAddress( "PuppiAK4_jetjet_deltaphi", 	 &vbsEvent.PuppiAK4_jetjet_deltaphi );
	 vbsTree->SetBranchAddress( "PuppiAK4_jetjet_deltar", 	 &vbsEvent.PuppiAK4_jetjet_deltar );
	 vbsTree->SetBranchAddress( "PuppiAK4_jetjet_mass", 	 &vbsEvent.PuppiAK4_jetjet_mass );
	 vbsTree->SetBranchAddress( "PuppiAK4_jetjet_pt", 	 &vbsEvent.PuppiAK4_jetjet_pt );
	 vbsTree->SetBranchAddress( "PuppiAK8_jetID_loose", 	 &vbsEvent.PuppiAK8_jetID_loose );
	 vbsTree->SetBranchAddress( "PuppiAK8_jet_mass", 	 &vbsEvent.PuppiAK8_jet_mass );
	 vbsTree->SetBranchAddress( "PuppiAK8_jet_mass_fi", 	 &vbsEvent.PuppiAK8_jet_mass_fi );
	 vbsTree->SetBranchAddress( "PuppiAK8_jet_mass_pr", 	 &vbsEvent.PuppiAK8_jet_mass_pr );
	 vbsTree->SetBranchAddress( "PuppiAK8_jet_mass_so", 	 &vbsEvent.PuppiAK8_jet_mass_so );
	 vbsTree->SetBranchAddress( "PuppiAK8_jet_mass_so_corr", 	 &vbsEvent.PuppiAK8_jet_mass_so_corr );
	 vbsTree->SetBranchAddress( "PuppiAK8_jet_mass_tr", 	 &vbsEvent.PuppiAK8_jet_mass_tr );
	 vbsTree->SetBranchAddress( "PuppiAK8_jet_pt_so", 	 &vbsEvent.PuppiAK8_jet_pt_so );
	 vbsTree->SetBranchAddress( "PuppiAK8_jet_sj1_eta", 	 &vbsEvent.PuppiAK8_jet_sj1_eta );
	 vbsTree->SetBranchAddress( "PuppiAK8_jet_sj1_m", 	 &vbsEvent.PuppiAK8_jet_sj1_m );
	 vbsTree->SetBranchAddress( "PuppiAK8_jet_sj1_phi", 	 &vbsEvent.PuppiAK8_jet_sj1_phi );
	 vbsTree->SetBranchAddress( "PuppiAK8_jet_sj1_pt", 	 &vbsEvent.PuppiAK8_jet_sj1_pt );
	 vbsTree->SetBranchAddress( "PuppiAK8_jet_sj1_q", 	 &vbsEvent.PuppiAK8_jet_sj1_q );
	 vbsTree->SetBranchAddress( "PuppiAK8_jet_sj2_eta", 	 &vbsEvent.PuppiAK8_jet_sj2_eta );
	 vbsTree->SetBranchAddress( "PuppiAK8_jet_sj2_m", 	 &vbsEvent.PuppiAK8_jet_sj2_m );
	 vbsTree->SetBranchAddress( "PuppiAK8_jet_sj2_phi", 	 &vbsEvent.PuppiAK8_jet_sj2_phi );
	 vbsTree->SetBranchAddress( "PuppiAK8_jet_sj2_pt", 	 &vbsEvent.PuppiAK8_jet_sj2_pt );
	 vbsTree->SetBranchAddress( "PuppiAK8_jet_sj2_q", 	 &vbsEvent.PuppiAK8_jet_sj2_q );
	 vbsTree->SetBranchAddress( "PuppiAK8_jet_tau2tau1", 	 &vbsEvent.PuppiAK8_jet_tau2tau1 );
	 vbsTree->SetBranchAddress( "PuppiAK8jet_e2_sdb05", 	 &vbsEvent.PuppiAK8jet_e2_sdb05 );
	 vbsTree->SetBranchAddress( "PuppiAK8jet_e2_sdb1", 	 &vbsEvent.PuppiAK8jet_e2_sdb1 );
	 vbsTree->SetBranchAddress( "PuppiAK8jet_e2_sdb2", 	 &vbsEvent.PuppiAK8jet_e2_sdb2 );
	 vbsTree->SetBranchAddress( "PuppiAK8jet_e2_sdb4", 	 &vbsEvent.PuppiAK8jet_e2_sdb4 );
	 vbsTree->SetBranchAddress( "PuppiAK8jet_e3_b1", 	 &vbsEvent.PuppiAK8jet_e3_b1 );
	 vbsTree->SetBranchAddress( "PuppiAK8jet_e3_b2", 	 &vbsEvent.PuppiAK8jet_e3_b2 );
	 vbsTree->SetBranchAddress( "PuppiAK8jet_e3_sdb05", 	 &vbsEvent.PuppiAK8jet_e3_sdb05 );
	 vbsTree->SetBranchAddress( "PuppiAK8jet_e3_sdb1", 	 &vbsEvent.PuppiAK8jet_e3_sdb1 );
	 vbsTree->SetBranchAddress( "PuppiAK8jet_e3_sdb2", 	 &vbsEvent.PuppiAK8jet_e3_sdb2 );
	 vbsTree->SetBranchAddress( "PuppiAK8jet_e3_sdb4", 	 &vbsEvent.PuppiAK8jet_e3_sdb4 );
	 vbsTree->SetBranchAddress( "PuppiAK8jet_e3_v1_b1", 	 &vbsEvent.PuppiAK8jet_e3_v1_b1 );
	 vbsTree->SetBranchAddress( "PuppiAK8jet_e3_v1_b2", 	 &vbsEvent.PuppiAK8jet_e3_v1_b2 );
	 vbsTree->SetBranchAddress( "PuppiAK8jet_e3_v1_sdb05", 	 &vbsEvent.PuppiAK8jet_e3_v1_sdb05 );
	 vbsTree->SetBranchAddress( "PuppiAK8jet_e3_v1_sdb1", 	 &vbsEvent.PuppiAK8jet_e3_v1_sdb1 );
	 vbsTree->SetBranchAddress( "PuppiAK8jet_e3_v1_sdb2", 	 &vbsEvent.PuppiAK8jet_e3_v1_sdb2 );
	 vbsTree->SetBranchAddress( "PuppiAK8jet_e3_v1_sdb4", 	 &vbsEvent.PuppiAK8jet_e3_v1_sdb4 );
	 vbsTree->SetBranchAddress( "PuppiAK8jet_e3_v2_b1", 	 &vbsEvent.PuppiAK8jet_e3_v2_b1 );
	 vbsTree->SetBranchAddress( "PuppiAK8jet_e3_v2_b2", 	 &vbsEvent.PuppiAK8jet_e3_v2_b2 );
	 vbsTree->SetBranchAddress( "PuppiAK8jet_e3_v2_sdb05", 	 &vbsEvent.PuppiAK8jet_e3_v2_sdb05 );
	 vbsTree->SetBranchAddress( "PuppiAK8jet_e3_v2_sdb1", 	 &vbsEvent.PuppiAK8jet_e3_v2_sdb1 );
	 vbsTree->SetBranchAddress( "PuppiAK8jet_e3_v2_sdb2", 	 &vbsEvent.PuppiAK8jet_e3_v2_sdb2 );
	 vbsTree->SetBranchAddress( "PuppiAK8jet_e3_v2_sdb4", 	 &vbsEvent.PuppiAK8jet_e3_v2_sdb4 );
	 vbsTree->SetBranchAddress( "PuppiAK8jet_e4_v1_b1", 	 &vbsEvent.PuppiAK8jet_e4_v1_b1 );
	 vbsTree->SetBranchAddress( "PuppiAK8jet_e4_v1_b2", 	 &vbsEvent.PuppiAK8jet_e4_v1_b2 );
	 vbsTree->SetBranchAddress( "PuppiAK8jet_e4_v1_sdb05", 	 &vbsEvent.PuppiAK8jet_e4_v1_sdb05 );
	 vbsTree->SetBranchAddress( "PuppiAK8jet_e4_v1_sdb1", 	 &vbsEvent.PuppiAK8jet_e4_v1_sdb1 );
	 vbsTree->SetBranchAddress( "PuppiAK8jet_e4_v1_sdb2", 	 &vbsEvent.PuppiAK8jet_e4_v1_sdb2 );
	 vbsTree->SetBranchAddress( "PuppiAK8jet_e4_v1_sdb4", 	 &vbsEvent.PuppiAK8jet_e4_v1_sdb4 );
	 vbsTree->SetBranchAddress( "PuppiAK8jet_e4_v2_b1", 	 &vbsEvent.PuppiAK8jet_e4_v2_b1 );
	 vbsTree->SetBranchAddress( "PuppiAK8jet_e4_v2_b2", 	 &vbsEvent.PuppiAK8jet_e4_v2_b2 );
	 vbsTree->SetBranchAddress( "PuppiAK8jet_e4_v2_sdb05", 	 &vbsEvent.PuppiAK8jet_e4_v2_sdb05 );
	 vbsTree->SetBranchAddress( "PuppiAK8jet_e4_v2_sdb1", 	 &vbsEvent.PuppiAK8jet_e4_v2_sdb1 );
	 vbsTree->SetBranchAddress( "PuppiAK8jet_e4_v2_sdb2", 	 &vbsEvent.PuppiAK8jet_e4_v2_sdb2 );
	 vbsTree->SetBranchAddress( "PuppiAK8jet_e4_v2_sdb4", 	 &vbsEvent.PuppiAK8jet_e4_v2_sdb4 );
	 vbsTree->SetBranchAddress( "PuppiAK8jet_qjet", 	 &vbsEvent.PuppiAK8jet_qjet );
	 vbsTree->SetBranchAddress( "WW_mT_gen", 	 &vbsEvent.WW_mT_gen );
	 vbsTree->SetBranchAddress( "WW_mass_gen", 	 &vbsEvent.WW_mass_gen );
	 vbsTree->SetBranchAddress( "WW_pT_gen", 	 &vbsEvent.WW_pT_gen );
	 vbsTree->SetBranchAddress( "W_pt_gen", 	 &vbsEvent.W_pt_gen );
	 vbsTree->SetBranchAddress( "W_pz_gen", 	 &vbsEvent.W_pz_gen );
	 vbsTree->SetBranchAddress( "W_rap_gen", 	 &vbsEvent.W_rap_gen );
	 vbsTree->SetBranchAddress( "hadW_e_gen", 	 &vbsEvent.hadW_e_gen );
	 vbsTree->SetBranchAddress( "hadW_eta_gen", 	 &vbsEvent.hadW_eta_gen );
	 vbsTree->SetBranchAddress( "hadW_m_gen", 	 &vbsEvent.hadW_m_gen );
	 vbsTree->SetBranchAddress( "hadW_phi_gen", 	 &vbsEvent.hadW_phi_gen );
	 vbsTree->SetBranchAddress( "hadW_pt_gen", 	 &vbsEvent.hadW_pt_gen );
	 vbsTree->SetBranchAddress( "lepW_e_gen", 	 &vbsEvent.lepW_e_gen );
	 vbsTree->SetBranchAddress( "lepW_eta_gen", 	 &vbsEvent.lepW_eta_gen );
	 vbsTree->SetBranchAddress( "lepW_m_gen", 	 &vbsEvent.lepW_m_gen );
	 vbsTree->SetBranchAddress( "lepW_phi_gen", 	 &vbsEvent.lepW_phi_gen );
	 vbsTree->SetBranchAddress( "lepW_pt_gen", 	 &vbsEvent.lepW_pt_gen );
	 vbsTree->SetBranchAddress( "lep_eta_gen", 	 &vbsEvent.lep_eta_gen );
	 vbsTree->SetBranchAddress( "lep_pt_gen", 	 &vbsEvent.lep_pt_gen );
	 vbsTree->SetBranchAddress( "nu_eta_gen", 	 &vbsEvent.nu_eta_gen );
	 vbsTree->SetBranchAddress( "nu_phi_gen", 	 &vbsEvent.nu_phi_gen );
	 vbsTree->SetBranchAddress( "nu_pt_gen", 	 &vbsEvent.nu_pt_gen );
	 vbsTree->SetBranchAddress( "nu_pz_gen", 	 &vbsEvent.nu_pz_gen );
	 vbsTree->SetBranchAddress( "ttb_jet_mass_fi", 	 &vbsEvent.ttb_jet_mass_fi );
	 vbsTree->SetBranchAddress( "ttb_jet_mass_pr", 	 &vbsEvent.ttb_jet_mass_pr );
	 vbsTree->SetBranchAddress( "ttb_jet_mass_so", 	 &vbsEvent.ttb_jet_mass_so );
	 vbsTree->SetBranchAddress( "ttb_jet_mass_tr", 	 &vbsEvent.ttb_jet_mass_tr );
	 vbsTree->SetBranchAddress( "ttb_jet_pt_so", 	 &vbsEvent.ttb_jet_pt_so );
	 vbsTree->SetBranchAddress( "ttb_jet_tau2tau1", 	 &vbsEvent.ttb_jet_tau2tau1 );
	 vbsTree->SetBranchAddress( "event", 	 &vbsEvent.event );
	 vbsTree->SetBranchAddress( "isPuppiVBF", 	 &vbsEvent.isPuppiVBF );
	 vbsTree->SetBranchAddress( "isVBF", 	 &vbsEvent.isVBF );
	 vbsTree->SetBranchAddress( "issignal", 	 &vbsEvent.issignal );
	 vbsTree->SetBranchAddress( "issignal_AK4jetjet", 	 &vbsEvent.issignal_AK4jetjet );
	 vbsTree->SetBranchAddress( "issignal_PuppiAK4jetjet", 	 &vbsEvent.issignal_PuppiAK4jetjet );
	 vbsTree->SetBranchAddress( "issignal_PuppiAK8", 	 &vbsEvent.issignal_PuppiAK8 );
	 vbsTree->SetBranchAddress( "l_charge1", 	 &vbsEvent.l_charge1 );
	 vbsTree->SetBranchAddress( "l_charge2", 	 &vbsEvent.l_charge2 );
	 vbsTree->SetBranchAddress( "lumi", 	 &vbsEvent.lumi );
	 vbsTree->SetBranchAddress( "nBTagJetPuppi_loose", 	 &vbsEvent.nBTagJetPuppi_loose );
	 vbsTree->SetBranchAddress( "nBTagJetPuppi_loose_unmerged", 	 &vbsEvent.nBTagJetPuppi_loose_unmerged );
	 vbsTree->SetBranchAddress( "nBTagJetPuppi_medium", 	 &vbsEvent.nBTagJetPuppi_medium );
	 vbsTree->SetBranchAddress( "nBTagJetPuppi_medium_unmerged", 	 &vbsEvent.nBTagJetPuppi_medium_unmerged );
	 vbsTree->SetBranchAddress( "nBTagJetPuppi_tight", 	 &vbsEvent.nBTagJetPuppi_tight );
	 vbsTree->SetBranchAddress( "nBTagJetPuppi_tight_unmerged", 	 &vbsEvent.nBTagJetPuppi_tight_unmerged );
	 vbsTree->SetBranchAddress( "nBTagJet_loose", 	 &vbsEvent.nBTagJet_loose );
	 vbsTree->SetBranchAddress( "nBTagJet_loose_unmerged", 	 &vbsEvent.nBTagJet_loose_unmerged );
	 vbsTree->SetBranchAddress( "nBTagJet_medium", 	 &vbsEvent.nBTagJet_medium );
	 vbsTree->SetBranchAddress( "nBTagJet_medium_unmerged", 	 &vbsEvent.nBTagJet_medium_unmerged );
	 vbsTree->SetBranchAddress( "nBTagJet_tight", 	 &vbsEvent.nBTagJet_tight );
	 vbsTree->SetBranchAddress( "nBTagJet_tight_unmerged", 	 &vbsEvent.nBTagJet_tight_unmerged );
	 vbsTree->SetBranchAddress( "nEvents", 	 &vbsEvent.nEvents );
	 vbsTree->SetBranchAddress( "nGoodAK8jets", 	 &vbsEvent.nGoodAK8jets );
	 vbsTree->SetBranchAddress( "nGoodPuppiAK8jets", 	 &vbsEvent.nGoodPuppiAK8jets );
	 vbsTree->SetBranchAddress( "nNegEvents", 	 &vbsEvent.nNegEvents );
	 vbsTree->SetBranchAddress( "nPV", 	 &vbsEvent.nPV );
	 vbsTree->SetBranchAddress( "nTotEvents", 	 &vbsEvent.nTotEvents );
	 vbsTree->SetBranchAddress( "nTotNegEvents", 	 &vbsEvent.nTotNegEvents );
	 vbsTree->SetBranchAddress( "njets", 	 &vbsEvent.njets );
	 vbsTree->SetBranchAddress( "njetsPuppi", 	 &vbsEvent.njetsPuppi );
	 vbsTree->SetBranchAddress( "njetsPuppi_unmerged", 	 &vbsEvent.njetsPuppi_unmerged );
	 vbsTree->SetBranchAddress( "njets_unmerged", 	 &vbsEvent.njets_unmerged );
	 vbsTree->SetBranchAddress( "nu_pz_isre", 	 &vbsEvent.nu_pz_isre );
	 vbsTree->SetBranchAddress( "nu_pz_run2_type", 	 &vbsEvent.nu_pz_run2_type );
	 vbsTree->SetBranchAddress( "run", 	 &vbsEvent.run );
	 vbsTree->SetBranchAddress( "type", 	 &vbsEvent.type );
	 vbsTree->SetBranchAddress( "ungroomed_AK8jet_charge", 	 &vbsEvent.ungroomed_AK8jet_charge );
	 vbsTree->SetBranchAddress( "ungroomed_PuppiAK8_jet_charge", 	 &vbsEvent.ungroomed_PuppiAK8_jet_charge );
	 vbsTree->SetBranchAddress( "vbf_maxpt_j1_charge", 	 &vbsEvent.vbf_maxpt_j1_charge );
	 vbsTree->SetBranchAddress( "vbf_maxpt_j2_charge", 	 &vbsEvent.vbf_maxpt_j2_charge );
	 vbsTree->SetBranchAddress( "AK4Puppi_DR_GENRECO_11", 	 &vbsEvent.AK4Puppi_DR_GENRECO_11 );
	 vbsTree->SetBranchAddress( "AK4Puppi_DR_GENRECO_12", 	 &vbsEvent.AK4Puppi_DR_GENRECO_12 );
	 vbsTree->SetBranchAddress( "AK4Puppi_DR_GENRECO_21", 	 &vbsEvent.AK4Puppi_DR_GENRECO_21 );
	 vbsTree->SetBranchAddress( "AK4Puppi_DR_GENRECO_22", 	 &vbsEvent.AK4Puppi_DR_GENRECO_22 );
	 vbsTree->SetBranchAddress( "AK4_1_e_gen", 	 &vbsEvent.AK4_1_e_gen );
	 vbsTree->SetBranchAddress( "AK4_1_eta_gen", 	 &vbsEvent.AK4_1_eta_gen );
	 vbsTree->SetBranchAddress( "AK4_1_mass_gen", 	 &vbsEvent.AK4_1_mass_gen );
	 vbsTree->SetBranchAddress( "AK4_1_phi_gen", 	 &vbsEvent.AK4_1_phi_gen );
	 vbsTree->SetBranchAddress( "AK4_1_pt_gen", 	 &vbsEvent.AK4_1_pt_gen );
	 vbsTree->SetBranchAddress( "AK4_2_e_gen", 	 &vbsEvent.AK4_2_e_gen );
	 vbsTree->SetBranchAddress( "AK4_2_eta_gen", 	 &vbsEvent.AK4_2_eta_gen );
	 vbsTree->SetBranchAddress( "AK4_2_mass_gen", 	 &vbsEvent.AK4_2_mass_gen );
	 vbsTree->SetBranchAddress( "AK4_2_phi_gen", 	 &vbsEvent.AK4_2_phi_gen );
	 vbsTree->SetBranchAddress( "AK4_2_pt_gen", 	 &vbsEvent.AK4_2_pt_gen );
	 vbsTree->SetBranchAddress( "AK4_DR_GENRECO_11", 	 &vbsEvent.AK4_DR_GENRECO_11 );
	 vbsTree->SetBranchAddress( "AK4_DR_GENRECO_12", 	 &vbsEvent.AK4_DR_GENRECO_12 );
	 vbsTree->SetBranchAddress( "AK4_DR_GENRECO_21", 	 &vbsEvent.AK4_DR_GENRECO_21 );
	 vbsTree->SetBranchAddress( "AK4_DR_GENRECO_22", 	 &vbsEvent.AK4_DR_GENRECO_22 );
	 vbsTree->SetBranchAddress( "AK4_jet1_e", 	 &vbsEvent.AK4_jet1_e );
	 vbsTree->SetBranchAddress( "AK4_jet1_eta", 	 &vbsEvent.AK4_jet1_eta );
	 vbsTree->SetBranchAddress( "AK4_jet1_phi", 	 &vbsEvent.AK4_jet1_phi );
	 vbsTree->SetBranchAddress( "AK4_jet1_pt", 	 &vbsEvent.AK4_jet1_pt );
	 vbsTree->SetBranchAddress( "AK4_jet1_pt_jer", 	 &vbsEvent.AK4_jet1_pt_jer );
	 vbsTree->SetBranchAddress( "AK4_jet1_pt_jer_dn", 	 &vbsEvent.AK4_jet1_pt_jer_dn );
	 vbsTree->SetBranchAddress( "AK4_jet1_pt_jer_up", 	 &vbsEvent.AK4_jet1_pt_jer_up );
	 vbsTree->SetBranchAddress( "AK4_jet1_pt_jes_dn", 	 &vbsEvent.AK4_jet1_pt_jes_dn );
	 vbsTree->SetBranchAddress( "AK4_jet1_pt_jes_up", 	 &vbsEvent.AK4_jet1_pt_jes_up );
	 vbsTree->SetBranchAddress( "AK4_jet2_e", 	 &vbsEvent.AK4_jet2_e );
	 vbsTree->SetBranchAddress( "AK4_jet2_eta", 	 &vbsEvent.AK4_jet2_eta );
	 vbsTree->SetBranchAddress( "AK4_jet2_phi", 	 &vbsEvent.AK4_jet2_phi );
	 vbsTree->SetBranchAddress( "AK4_jet2_pt", 	 &vbsEvent.AK4_jet2_pt );
	 vbsTree->SetBranchAddress( "AK4_jet2_pt_jer", 	 &vbsEvent.AK4_jet2_pt_jer );
	 vbsTree->SetBranchAddress( "AK4_jet2_pt_jer_dn", 	 &vbsEvent.AK4_jet2_pt_jer_dn );
	 vbsTree->SetBranchAddress( "AK4_jet2_pt_jer_up", 	 &vbsEvent.AK4_jet2_pt_jer_up );
	 vbsTree->SetBranchAddress( "AK4_jet2_pt_jes_dn", 	 &vbsEvent.AK4_jet2_pt_jes_dn );
	 vbsTree->SetBranchAddress( "AK4_jet2_pt_jes_up", 	 &vbsEvent.AK4_jet2_pt_jes_up );
	 vbsTree->SetBranchAddress( "AK4_jj_DeltaEta_gen", 	 &vbsEvent.AK4_jj_DeltaEta_gen );
	 vbsTree->SetBranchAddress( "AK4_jj_mass_gen", 	 &vbsEvent.AK4_jj_mass_gen );
	 vbsTree->SetBranchAddress( "AK8_closerjet_e", 	 &vbsEvent.AK8_closerjet_e );
	 vbsTree->SetBranchAddress( "AK8_closerjet_eta", 	 &vbsEvent.AK8_closerjet_eta );
	 vbsTree->SetBranchAddress( "AK8_closerjet_phi", 	 &vbsEvent.AK8_closerjet_phi );
	 vbsTree->SetBranchAddress( "AK8_closerjet_pt", 	 &vbsEvent.AK8_closerjet_pt );
	 vbsTree->SetBranchAddress( "AK8jet_mass_pr_jer", 	 &vbsEvent.AK8jet_mass_pr_jer );
	 vbsTree->SetBranchAddress( "AK8jet_mass_pr_jer_dn", 	 &vbsEvent.AK8jet_mass_pr_jer_dn );
	 vbsTree->SetBranchAddress( "AK8jet_mass_pr_jer_up", 	 &vbsEvent.AK8jet_mass_pr_jer_up );
	 vbsTree->SetBranchAddress( "AK8jet_mass_pr_jes_dn", 	 &vbsEvent.AK8jet_mass_pr_jes_dn );
	 vbsTree->SetBranchAddress( "AK8jet_mass_pr_jes_up", 	 &vbsEvent.AK8jet_mass_pr_jes_up );
	 vbsTree->SetBranchAddress( "BosonCentralityPuppi_run2", 	 &vbsEvent.BosonCentralityPuppi_run2 );
	 vbsTree->SetBranchAddress( "BosonCentralityPuppi_type0", 	 &vbsEvent.BosonCentralityPuppi_type0 );
	 vbsTree->SetBranchAddress( "BosonCentralityPuppi_type2", 	 &vbsEvent.BosonCentralityPuppi_type2 );
	 vbsTree->SetBranchAddress( "BosonCentrality_2Lep", 	 &vbsEvent.BosonCentrality_2Lep );
	 vbsTree->SetBranchAddress( "BosonCentrality_2Lep_LEP_Down", 	 &vbsEvent.BosonCentrality_2Lep_LEP_Down );
	 vbsTree->SetBranchAddress( "BosonCentrality_2Lep_LEP_Up", 	 &vbsEvent.BosonCentrality_2Lep_LEP_Up );
	 vbsTree->SetBranchAddress( "BosonCentrality_2Lep_jes_dn", 	 &vbsEvent.BosonCentrality_2Lep_jes_dn );
	 vbsTree->SetBranchAddress( "BosonCentrality_2Lep_jes_up", 	 &vbsEvent.BosonCentrality_2Lep_jes_up );
	 vbsTree->SetBranchAddress( "BosonCentrality_run2", 	 &vbsEvent.BosonCentrality_run2 );
	 vbsTree->SetBranchAddress( "BosonCentrality_type0", 	 &vbsEvent.BosonCentrality_type0 );
	 vbsTree->SetBranchAddress( "BosonCentrality_type0_LEP_Down", 	 &vbsEvent.BosonCentrality_type0_LEP_Down );
	 vbsTree->SetBranchAddress( "BosonCentrality_type0_LEP_Up", 	 &vbsEvent.BosonCentrality_type0_LEP_Up );
	 vbsTree->SetBranchAddress( "BosonCentrality_type0_jer_dn", 	 &vbsEvent.BosonCentrality_type0_jer_dn );
	 vbsTree->SetBranchAddress( "BosonCentrality_type0_jer_up", 	 &vbsEvent.BosonCentrality_type0_jer_up );
	 vbsTree->SetBranchAddress( "BosonCentrality_type0_jes_dn", 	 &vbsEvent.BosonCentrality_type0_jes_dn );
	 vbsTree->SetBranchAddress( "BosonCentrality_type0_jes_up", 	 &vbsEvent.BosonCentrality_type0_jes_up );
	 vbsTree->SetBranchAddress( "BosonCentrality_type2", 	 &vbsEvent.BosonCentrality_type2 );
	 vbsTree->SetBranchAddress( "HadWEta", 	 &vbsEvent.HadWEta );
	 vbsTree->SetBranchAddress( "HadWRapidity", 	 &vbsEvent.HadWRapidity );
	 vbsTree->SetBranchAddress( "L1_Prefweight", 	 &vbsEvent.L1_Prefweight );
	 vbsTree->SetBranchAddress( "L1_PrefweightDown", 	 &vbsEvent.L1_PrefweightDown );
	 vbsTree->SetBranchAddress( "L1_PrefweightUp", 	 &vbsEvent.L1_PrefweightUp );
	 vbsTree->SetBranchAddress( "LHEWeight", 	 &vbsEvent.LHEWeight );
	 vbsTree->SetBranchAddress( "LepWEta", 	 &vbsEvent.LepWEta );
	 vbsTree->SetBranchAddress( "LepWRapidity", 	 &vbsEvent.LepWRapidity );
	 vbsTree->SetBranchAddress( "LeptonProjectionPuppi_run2", 	 &vbsEvent.LeptonProjectionPuppi_run2 );
	 vbsTree->SetBranchAddress( "LeptonProjectionPuppi_type0", 	 &vbsEvent.LeptonProjectionPuppi_type0 );
	 vbsTree->SetBranchAddress( "LeptonProjectionPuppi_type2", 	 &vbsEvent.LeptonProjectionPuppi_type2 );
	 vbsTree->SetBranchAddress( "LeptonProjection_2Lep", 	 &vbsEvent.LeptonProjection_2Lep );
	 vbsTree->SetBranchAddress( "LeptonProjection_run2", 	 &vbsEvent.LeptonProjection_run2 );
	 vbsTree->SetBranchAddress( "LeptonProjection_type0", 	 &vbsEvent.LeptonProjection_type0 );
	 vbsTree->SetBranchAddress( "LeptonProjection_type2", 	 &vbsEvent.LeptonProjection_type2 );
	 vbsTree->SetBranchAddress( "PtBalancePuppi_run2", 	 &vbsEvent.PtBalancePuppi_run2 );
	 vbsTree->SetBranchAddress( "PtBalancePuppi_type0", 	 &vbsEvent.PtBalancePuppi_type0 );
	 vbsTree->SetBranchAddress( "PtBalancePuppi_type2", 	 &vbsEvent.PtBalancePuppi_type2 );
	 vbsTree->SetBranchAddress( "PtBalance_2Lep", 	 &vbsEvent.PtBalance_2Lep );
	 vbsTree->SetBranchAddress( "PtBalance_run2", 	 &vbsEvent.PtBalance_run2 );
	 vbsTree->SetBranchAddress( "PtBalance_type0", 	 &vbsEvent.PtBalance_type0 );
	 vbsTree->SetBranchAddress( "PtBalance_type0_LEP_Down", 	 &vbsEvent.PtBalance_type0_LEP_Down );
	 vbsTree->SetBranchAddress( "PtBalance_type0_LEP_Up", 	 &vbsEvent.PtBalance_type0_LEP_Up );
	 vbsTree->SetBranchAddress( "PtBalance_type0_jer_dn", 	 &vbsEvent.PtBalance_type0_jer_dn );
	 vbsTree->SetBranchAddress( "PtBalance_type0_jer_up", 	 &vbsEvent.PtBalance_type0_jer_up );
	 vbsTree->SetBranchAddress( "PtBalance_type0_jes_dn", 	 &vbsEvent.PtBalance_type0_jes_dn );
	 vbsTree->SetBranchAddress( "PtBalance_type0_jes_up", 	 &vbsEvent.PtBalance_type0_jes_up );
	 vbsTree->SetBranchAddress( "PtBalance_type2", 	 &vbsEvent.PtBalance_type2 );
	 vbsTree->SetBranchAddress( "PuppiAK4_jet1_e", 	 &vbsEvent.PuppiAK4_jet1_e );
	 vbsTree->SetBranchAddress( "PuppiAK4_jet1_eta", 	 &vbsEvent.PuppiAK4_jet1_eta );
	 vbsTree->SetBranchAddress( "PuppiAK4_jet1_phi", 	 &vbsEvent.PuppiAK4_jet1_phi );
	 vbsTree->SetBranchAddress( "PuppiAK4_jet1_pt", 	 &vbsEvent.PuppiAK4_jet1_pt );
	 vbsTree->SetBranchAddress( "PuppiAK4_jet1_pt_jer", 	 &vbsEvent.PuppiAK4_jet1_pt_jer );
	 vbsTree->SetBranchAddress( "PuppiAK4_jet1_pt_jer_dn", 	 &vbsEvent.PuppiAK4_jet1_pt_jer_dn );
	 vbsTree->SetBranchAddress( "PuppiAK4_jet1_pt_jer_up", 	 &vbsEvent.PuppiAK4_jet1_pt_jer_up );
	 vbsTree->SetBranchAddress( "PuppiAK4_jet1_pt_jes_dn", 	 &vbsEvent.PuppiAK4_jet1_pt_jes_dn );
	 vbsTree->SetBranchAddress( "PuppiAK4_jet1_pt_jes_up", 	 &vbsEvent.PuppiAK4_jet1_pt_jes_up );
	 vbsTree->SetBranchAddress( "PuppiAK4_jet2_e", 	 &vbsEvent.PuppiAK4_jet2_e );
	 vbsTree->SetBranchAddress( "PuppiAK4_jet2_eta", 	 &vbsEvent.PuppiAK4_jet2_eta );
	 vbsTree->SetBranchAddress( "PuppiAK4_jet2_phi", 	 &vbsEvent.PuppiAK4_jet2_phi );
	 vbsTree->SetBranchAddress( "PuppiAK4_jet2_pt", 	 &vbsEvent.PuppiAK4_jet2_pt );
	 vbsTree->SetBranchAddress( "PuppiAK4_jet2_pt_jer", 	 &vbsEvent.PuppiAK4_jet2_pt_jer );
	 vbsTree->SetBranchAddress( "PuppiAK4_jet2_pt_jer_dn", 	 &vbsEvent.PuppiAK4_jet2_pt_jer_dn );
	 vbsTree->SetBranchAddress( "PuppiAK4_jet2_pt_jer_up", 	 &vbsEvent.PuppiAK4_jet2_pt_jer_up );
	 vbsTree->SetBranchAddress( "PuppiAK4_jet2_pt_jes_dn", 	 &vbsEvent.PuppiAK4_jet2_pt_jes_dn );
	 vbsTree->SetBranchAddress( "PuppiAK4_jet2_pt_jes_up", 	 &vbsEvent.PuppiAK4_jet2_pt_jes_up );
	 vbsTree->SetBranchAddress( "PuppiAK8_jet_mass_pr_jer", 	 &vbsEvent.PuppiAK8_jet_mass_pr_jer );
	 vbsTree->SetBranchAddress( "PuppiAK8_jet_mass_pr_jer_dn", 	 &vbsEvent.PuppiAK8_jet_mass_pr_jer_dn );
	 vbsTree->SetBranchAddress( "PuppiAK8_jet_mass_pr_jer_up", 	 &vbsEvent.PuppiAK8_jet_mass_pr_jer_up );
	 vbsTree->SetBranchAddress( "PuppiAK8_jet_mass_pr_jes_dn", 	 &vbsEvent.PuppiAK8_jet_mass_pr_jes_dn );
	 vbsTree->SetBranchAddress( "PuppiAK8_jet_mass_pr_jes_up", 	 &vbsEvent.PuppiAK8_jet_mass_pr_jes_up );
	 vbsTree->SetBranchAddress( "RpTPuppi_run2", 	 &vbsEvent.RpTPuppi_run2 );
	 vbsTree->SetBranchAddress( "RpTPuppi_type0", 	 &vbsEvent.RpTPuppi_type0 );
	 vbsTree->SetBranchAddress( "RpTPuppi_type2", 	 &vbsEvent.RpTPuppi_type2 );
	 vbsTree->SetBranchAddress( "RpT_2Lep", 	 &vbsEvent.RpT_2Lep );
	 vbsTree->SetBranchAddress( "RpT_run2", 	 &vbsEvent.RpT_run2 );
	 vbsTree->SetBranchAddress( "RpT_type0", 	 &vbsEvent.RpT_type0 );
	 vbsTree->SetBranchAddress( "RpT_type2", 	 &vbsEvent.RpT_type2 );
	 vbsTree->SetBranchAddress( "VBSCentralityPuppi_run2", 	 &vbsEvent.VBSCentralityPuppi_run2 );
	 vbsTree->SetBranchAddress( "VBSCentralityPuppi_type0", 	 &vbsEvent.VBSCentralityPuppi_type0 );
	 vbsTree->SetBranchAddress( "VBSCentralityPuppi_type2", 	 &vbsEvent.VBSCentralityPuppi_type2 );
	 vbsTree->SetBranchAddress( "VBSCentrality_2Lep", 	 &vbsEvent.VBSCentrality_2Lep );
	 vbsTree->SetBranchAddress( "VBSCentrality_run2", 	 &vbsEvent.VBSCentrality_run2 );
	 vbsTree->SetBranchAddress( "VBSCentrality_type0", 	 &vbsEvent.VBSCentrality_type0 );
	 vbsTree->SetBranchAddress( "VBSCentrality_type2", 	 &vbsEvent.VBSCentrality_type2 );
	 vbsTree->SetBranchAddress( "WWEta", 	 &vbsEvent.WWEta );
	 vbsTree->SetBranchAddress( "WWEta_PuppiAK8", 	 &vbsEvent.WWEta_PuppiAK8 );
	 vbsTree->SetBranchAddress( "WWRapidity", 	 &vbsEvent.WWRapidity );
	 vbsTree->SetBranchAddress( "WWRapidity_PuppiAK8", 	 &vbsEvent.WWRapidity_PuppiAK8 );
	 vbsTree->SetBranchAddress( "ZeppenfeldWH", 	 &vbsEvent.ZeppenfeldWH );
	 vbsTree->SetBranchAddress( "ZeppenfeldWHPuppi", 	 &vbsEvent.ZeppenfeldWHPuppi );
	 vbsTree->SetBranchAddress( "ZeppenfeldWH_jes_dn", 	 &vbsEvent.ZeppenfeldWH_jes_dn );
	 vbsTree->SetBranchAddress( "ZeppenfeldWH_jes_up", 	 &vbsEvent.ZeppenfeldWH_jes_up );
	 vbsTree->SetBranchAddress( "ZeppenfeldWLPuppi_run2", 	 &vbsEvent.ZeppenfeldWLPuppi_run2 );
	 vbsTree->SetBranchAddress( "ZeppenfeldWLPuppi_type0", 	 &vbsEvent.ZeppenfeldWLPuppi_type0 );
	 vbsTree->SetBranchAddress( "ZeppenfeldWLPuppi_type2", 	 &vbsEvent.ZeppenfeldWLPuppi_type2 );
	 vbsTree->SetBranchAddress( "ZeppenfeldWL_2Lep", 	 &vbsEvent.ZeppenfeldWL_2Lep );
	 vbsTree->SetBranchAddress( "ZeppenfeldWL_2Lep_LEP_Down", 	 &vbsEvent.ZeppenfeldWL_2Lep_LEP_Down );
	 vbsTree->SetBranchAddress( "ZeppenfeldWL_2Lep_LEP_Up", 	 &vbsEvent.ZeppenfeldWL_2Lep_LEP_Up );
	 vbsTree->SetBranchAddress( "ZeppenfeldWL_2Lep_jes_dn", 	 &vbsEvent.ZeppenfeldWL_2Lep_jes_dn );
	 vbsTree->SetBranchAddress( "ZeppenfeldWL_2Lep_jes_up", 	 &vbsEvent.ZeppenfeldWL_2Lep_jes_up );
	 vbsTree->SetBranchAddress( "ZeppenfeldWL_run2", 	 &vbsEvent.ZeppenfeldWL_run2 );
	 vbsTree->SetBranchAddress( "ZeppenfeldWL_type0", 	 &vbsEvent.ZeppenfeldWL_type0 );
	 vbsTree->SetBranchAddress( "ZeppenfeldWL_type0_LEP_Down", 	 &vbsEvent.ZeppenfeldWL_type0_LEP_Down );
	 vbsTree->SetBranchAddress( "ZeppenfeldWL_type0_LEP_Up", 	 &vbsEvent.ZeppenfeldWL_type0_LEP_Up );
	 vbsTree->SetBranchAddress( "ZeppenfeldWL_type0_jer_dn", 	 &vbsEvent.ZeppenfeldWL_type0_jer_dn );
	 vbsTree->SetBranchAddress( "ZeppenfeldWL_type0_jer_up", 	 &vbsEvent.ZeppenfeldWL_type0_jer_up );
	 vbsTree->SetBranchAddress( "ZeppenfeldWL_type0_jes_dn", 	 &vbsEvent.ZeppenfeldWL_type0_jes_dn );
	 vbsTree->SetBranchAddress( "ZeppenfeldWL_type0_jes_up", 	 &vbsEvent.ZeppenfeldWL_type0_jes_up );
	 vbsTree->SetBranchAddress( "ZeppenfeldWL_type2", 	 &vbsEvent.ZeppenfeldWL_type2 );
	 vbsTree->SetBranchAddress( "btag0Wgt", 	 &vbsEvent.btag0Wgt );
	 vbsTree->SetBranchAddress( "btag0WgtDownHF", 	 &vbsEvent.btag0WgtDownHF );
	 vbsTree->SetBranchAddress( "btag0WgtDownLF", 	 &vbsEvent.btag0WgtDownLF );
	 vbsTree->SetBranchAddress( "btag0WgtUpHF", 	 &vbsEvent.btag0WgtUpHF );
	 vbsTree->SetBranchAddress( "btag0WgtUpLF", 	 &vbsEvent.btag0WgtUpLF );
	 vbsTree->SetBranchAddress( "btag1Wgt", 	 &vbsEvent.btag1Wgt );
	 vbsTree->SetBranchAddress( "btag1WgtDownHF", 	 &vbsEvent.btag1WgtDownHF );
	 vbsTree->SetBranchAddress( "btag1WgtDownLF", 	 &vbsEvent.btag1WgtDownLF );
	 vbsTree->SetBranchAddress( "btag1WgtUpHF", 	 &vbsEvent.btag1WgtUpHF );
	 vbsTree->SetBranchAddress( "btag1WgtUpLF", 	 &vbsEvent.btag1WgtUpLF );
	 vbsTree->SetBranchAddress( "btag2Wgt", 	 &vbsEvent.btag2Wgt );
	 vbsTree->SetBranchAddress( "costheta1Puppi_run2", 	 &vbsEvent.costheta1Puppi_run2 );
	 vbsTree->SetBranchAddress( "costheta1Puppi_type0", 	 &vbsEvent.costheta1Puppi_type0 );
	 vbsTree->SetBranchAddress( "costheta1Puppi_type2", 	 &vbsEvent.costheta1Puppi_type2 );
	 vbsTree->SetBranchAddress( "costheta1_2Lep", 	 &vbsEvent.costheta1_2Lep );
	 vbsTree->SetBranchAddress( "costheta1_run2", 	 &vbsEvent.costheta1_run2 );
	 vbsTree->SetBranchAddress( "costheta1_type0", 	 &vbsEvent.costheta1_type0 );
	 vbsTree->SetBranchAddress( "costheta1_type2", 	 &vbsEvent.costheta1_type2 );
	 vbsTree->SetBranchAddress( "costheta2Puppi_run2", 	 &vbsEvent.costheta2Puppi_run2 );
	 vbsTree->SetBranchAddress( "costheta2Puppi_type0", 	 &vbsEvent.costheta2Puppi_type0 );
	 vbsTree->SetBranchAddress( "costheta2Puppi_type2", 	 &vbsEvent.costheta2Puppi_type2 );
	 vbsTree->SetBranchAddress( "costheta2_2Lep", 	 &vbsEvent.costheta2_2Lep );
	 vbsTree->SetBranchAddress( "costheta2_run2", 	 &vbsEvent.costheta2_run2 );
	 vbsTree->SetBranchAddress( "costheta2_type0", 	 &vbsEvent.costheta2_type0 );
	 vbsTree->SetBranchAddress( "costheta2_type2", 	 &vbsEvent.costheta2_type2 );
	 vbsTree->SetBranchAddress( "costhetastarPuppi_run2", 	 &vbsEvent.costhetastarPuppi_run2 );
	 vbsTree->SetBranchAddress( "costhetastarPuppi_type0", 	 &vbsEvent.costhetastarPuppi_type0 );
	 vbsTree->SetBranchAddress( "costhetastarPuppi_type2", 	 &vbsEvent.costhetastarPuppi_type2 );
	 vbsTree->SetBranchAddress( "costhetastar_2Lep", 	 &vbsEvent.costhetastar_2Lep );
	 vbsTree->SetBranchAddress( "costhetastar_run2", 	 &vbsEvent.costhetastar_run2 );
	 vbsTree->SetBranchAddress( "costhetastar_type0", 	 &vbsEvent.costhetastar_type0 );
	 vbsTree->SetBranchAddress( "costhetastar_type2", 	 &vbsEvent.costhetastar_type2 );
	 vbsTree->SetBranchAddress( "deltaR_AK8_closestBtagJet", 	 &vbsEvent.deltaR_AK8_closestBtagJet );
	 vbsTree->SetBranchAddress( "deltaR_AK8_closestBtagJet_loose", 	 &vbsEvent.deltaR_AK8_closestBtagJet_loose );
	 vbsTree->SetBranchAddress( "deltaR_VLepPuppiak8jet", 	 &vbsEvent.deltaR_VLepPuppiak8jet );
	 vbsTree->SetBranchAddress( "deltaR_Wjet_GenReco", 	 &vbsEvent.deltaR_Wjet_GenReco );
	 vbsTree->SetBranchAddress( "deltaR_l2Puppiak8jet", 	 &vbsEvent.deltaR_l2Puppiak8jet );
	 vbsTree->SetBranchAddress( "deltaR_lPuppiak4jetjet", 	 &vbsEvent.deltaR_lPuppiak4jetjet );
	 vbsTree->SetBranchAddress( "deltaR_lPuppiak8jet", 	 &vbsEvent.deltaR_lPuppiak8jet );
	 vbsTree->SetBranchAddress( "deltaR_lak4jetjet", 	 &vbsEvent.deltaR_lak4jetjet );
	 vbsTree->SetBranchAddress( "deltaR_lak8jet", 	 &vbsEvent.deltaR_lak8jet );
	 vbsTree->SetBranchAddress( "deltaphi_METPuppiak4jetjet", 	 &vbsEvent.deltaphi_METPuppiak4jetjet );
	 vbsTree->SetBranchAddress( "deltaphi_METPuppiak8jet", 	 &vbsEvent.deltaphi_METPuppiak8jet );
	 vbsTree->SetBranchAddress( "deltaphi_METak4jetjet", 	 &vbsEvent.deltaphi_METak4jetjet );
	 vbsTree->SetBranchAddress( "deltaphi_METak8jet", 	 &vbsEvent.deltaphi_METak8jet );
	 vbsTree->SetBranchAddress( "deltaphi_METmin", 	 &vbsEvent.deltaphi_METmin );
	 vbsTree->SetBranchAddress( "deltaphi_METvbfJ1", 	 &vbsEvent.deltaphi_METvbfJ1 );
	 vbsTree->SetBranchAddress( "deltaphi_METvbfJ2", 	 &vbsEvent.deltaphi_METvbfJ2 );
	 vbsTree->SetBranchAddress( "deltaphi_VPuppiak4jetjet", 	 &vbsEvent.deltaphi_VPuppiak4jetjet );
	 vbsTree->SetBranchAddress( "deltaphi_VPuppiak8jet", 	 &vbsEvent.deltaphi_VPuppiak8jet );
	 vbsTree->SetBranchAddress( "deltaphi_Vak4jetjet", 	 &vbsEvent.deltaphi_Vak4jetjet );
	 vbsTree->SetBranchAddress( "deltaphi_Vak8jet", 	 &vbsEvent.deltaphi_Vak8jet );
	 vbsTree->SetBranchAddress( "dilep_eta", 	 &vbsEvent.dilep_eta );
	 vbsTree->SetBranchAddress( "dilep_eta_Down", 	 &vbsEvent.dilep_eta_Down );
	 vbsTree->SetBranchAddress( "dilep_eta_Up", 	 &vbsEvent.dilep_eta_Up );
	 vbsTree->SetBranchAddress( "dilep_m", 	 &vbsEvent.dilep_m );
	 vbsTree->SetBranchAddress( "dilep_m_Down", 	 &vbsEvent.dilep_m_Down );
	 vbsTree->SetBranchAddress( "dilep_m_Up", 	 &vbsEvent.dilep_m_Up );
	 vbsTree->SetBranchAddress( "dilep_phi", 	 &vbsEvent.dilep_phi );
	 vbsTree->SetBranchAddress( "dilep_phi_Down", 	 &vbsEvent.dilep_phi_Down );
	 vbsTree->SetBranchAddress( "dilep_phi_Up", 	 &vbsEvent.dilep_phi_Up );
	 vbsTree->SetBranchAddress( "dilep_pt", 	 &vbsEvent.dilep_pt );
	 vbsTree->SetBranchAddress( "dilep_pt_Down", 	 &vbsEvent.dilep_pt_Down );
	 vbsTree->SetBranchAddress( "dilep_pt_Up", 	 &vbsEvent.dilep_pt_Up );
	 vbsTree->SetBranchAddress( "energy_lvj_run2_PuppiAK8", 	 &vbsEvent.energy_lvj_run2_PuppiAK8 );
	 vbsTree->SetBranchAddress( "energy_lvj_type0_PuppiAK8", 	 &vbsEvent.energy_lvj_type0_PuppiAK8 );
	 vbsTree->SetBranchAddress( "energy_lvj_type2_PuppiAK8", 	 &vbsEvent.energy_lvj_type2_PuppiAK8 );
	 vbsTree->SetBranchAddress( "eta_llj_PuppiAK8", 	 &vbsEvent.eta_llj_PuppiAK8 );
	 vbsTree->SetBranchAddress( "eta_lvj_run2_PuppiAK8", 	 &vbsEvent.eta_lvj_run2_PuppiAK8 );
	 vbsTree->SetBranchAddress( "eta_lvj_type0_PuppiAK8", 	 &vbsEvent.eta_lvj_type0_PuppiAK8 );
	 vbsTree->SetBranchAddress( "eta_lvj_type2_PuppiAK8", 	 &vbsEvent.eta_lvj_type2_PuppiAK8 );
	 vbsTree->SetBranchAddress( "genWeight", 	 &vbsEvent.genWeight );
	 vbsTree->SetBranchAddress( "gen_top1_pt", 	 &vbsEvent.gen_top1_pt );
	 vbsTree->SetBranchAddress( "gen_top2_pt", 	 &vbsEvent.gen_top2_pt );
	 vbsTree->SetBranchAddress( "id_eff_Weight", 	 &vbsEvent.id_eff_Weight );
	 vbsTree->SetBranchAddress( "id_eff_Weight2", 	 &vbsEvent.id_eff_Weight2 );
	 vbsTree->SetBranchAddress( "id_eff_Weight2_Down", 	 &vbsEvent.id_eff_Weight2_Down );
	 vbsTree->SetBranchAddress( "id_eff_Weight2_Up", 	 &vbsEvent.id_eff_Weight2_Up );
	 vbsTree->SetBranchAddress( "id_eff_Weight_Down", 	 &vbsEvent.id_eff_Weight_Down );
	 vbsTree->SetBranchAddress( "id_eff_Weight_Up", 	 &vbsEvent.id_eff_Weight_Up );
	 vbsTree->SetBranchAddress( "isGen", 	 &vbsEvent.isGen );
	 vbsTree->SetBranchAddress( "jet2_btag", 	 &vbsEvent.jet2_btag );
	 vbsTree->SetBranchAddress( "jet2_e", 	 &vbsEvent.jet2_e );
	 vbsTree->SetBranchAddress( "jet2_eta", 	 &vbsEvent.jet2_eta );
	 vbsTree->SetBranchAddress( "jet2_phi", 	 &vbsEvent.jet2_phi );
	 vbsTree->SetBranchAddress( "jet2_pt", 	 &vbsEvent.jet2_pt );
	 vbsTree->SetBranchAddress( "jet3_btag", 	 &vbsEvent.jet3_btag );
	 vbsTree->SetBranchAddress( "jet3_e", 	 &vbsEvent.jet3_e );
	 vbsTree->SetBranchAddress( "jet3_eta", 	 &vbsEvent.jet3_eta );
	 vbsTree->SetBranchAddress( "jet3_phi", 	 &vbsEvent.jet3_phi );
	 vbsTree->SetBranchAddress( "jet3_pt", 	 &vbsEvent.jet3_pt );
	 vbsTree->SetBranchAddress( "l_e1", 	 &vbsEvent.l_e1 );
	 vbsTree->SetBranchAddress( "l_e2", 	 &vbsEvent.l_e2 );
	 vbsTree->SetBranchAddress( "l_eta1", 	 &vbsEvent.l_eta1 );
	 vbsTree->SetBranchAddress( "l_eta1_Down", 	 &vbsEvent.l_eta1_Down );
	 vbsTree->SetBranchAddress( "l_eta1_Up", 	 &vbsEvent.l_eta1_Up );
	 vbsTree->SetBranchAddress( "l_eta2", 	 &vbsEvent.l_eta2 );
	 vbsTree->SetBranchAddress( "l_iso1", 	 &vbsEvent.l_iso1 );
	 vbsTree->SetBranchAddress( "l_iso2", 	 &vbsEvent.l_iso2 );
	 vbsTree->SetBranchAddress( "l_phi1", 	 &vbsEvent.l_phi1 );
	 vbsTree->SetBranchAddress( "l_phi2", 	 &vbsEvent.l_phi2 );
	 vbsTree->SetBranchAddress( "l_pt1", 	 &vbsEvent.l_pt1 );
	 vbsTree->SetBranchAddress( "l_pt1_Down", 	 &vbsEvent.l_pt1_Down );
	 vbsTree->SetBranchAddress( "l_pt1_Up", 	 &vbsEvent.l_pt1_Up );
	 vbsTree->SetBranchAddress( "l_pt2", 	 &vbsEvent.l_pt2 );
	 vbsTree->SetBranchAddress( "l_pt2_Down", 	 &vbsEvent.l_pt2_Down );
	 vbsTree->SetBranchAddress( "l_pt2_Up", 	 &vbsEvent.l_pt2_Up );
	 vbsTree->SetBranchAddress( "mass_leptonic_closerjet", 	 &vbsEvent.mass_leptonic_closerjet );
	 vbsTree->SetBranchAddress( "mass_llj_PuppiAK8", 	 &vbsEvent.mass_llj_PuppiAK8 );
	 vbsTree->SetBranchAddress( "mass_llj_PuppiAK8_LEP_Down", 	 &vbsEvent.mass_llj_PuppiAK8_LEP_Down );
	 vbsTree->SetBranchAddress( "mass_llj_PuppiAK8_LEP_Up", 	 &vbsEvent.mass_llj_PuppiAK8_LEP_Up );
	 vbsTree->SetBranchAddress( "mass_llj_PuppiAK8_jes_dn", 	 &vbsEvent.mass_llj_PuppiAK8_jes_dn );
	 vbsTree->SetBranchAddress( "mass_llj_PuppiAK8_jes_up", 	 &vbsEvent.mass_llj_PuppiAK8_jes_up );
	 vbsTree->SetBranchAddress( "mass_lvj_run2", 	 &vbsEvent.mass_lvj_run2 );
	 vbsTree->SetBranchAddress( "mass_lvj_run2_PuppiAK8", 	 &vbsEvent.mass_lvj_run2_PuppiAK8 );
	 vbsTree->SetBranchAddress( "mass_lvj_type0", 	 &vbsEvent.mass_lvj_type0 );
	 vbsTree->SetBranchAddress( "mass_lvj_type0_PuppiAK8", 	 &vbsEvent.mass_lvj_type0_PuppiAK8 );
	 vbsTree->SetBranchAddress( "mass_lvj_type0_PuppiAK8_LEP_Down", 	 &vbsEvent.mass_lvj_type0_PuppiAK8_LEP_Down );
	 vbsTree->SetBranchAddress( "mass_lvj_type0_PuppiAK8_LEP_Up", 	 &vbsEvent.mass_lvj_type0_PuppiAK8_LEP_Up );
	 vbsTree->SetBranchAddress( "mass_lvj_type0_PuppiAK8_jer_dn", 	 &vbsEvent.mass_lvj_type0_PuppiAK8_jer_dn );
	 vbsTree->SetBranchAddress( "mass_lvj_type0_PuppiAK8_jer_up", 	 &vbsEvent.mass_lvj_type0_PuppiAK8_jer_up );
	 vbsTree->SetBranchAddress( "mass_lvj_type0_PuppiAK8_jes_dn", 	 &vbsEvent.mass_lvj_type0_PuppiAK8_jes_dn );
	 vbsTree->SetBranchAddress( "mass_lvj_type0_PuppiAK8_jes_up", 	 &vbsEvent.mass_lvj_type0_PuppiAK8_jes_up );
	 vbsTree->SetBranchAddress( "mass_lvj_type0_met_PuppiAK8_jes_dn", 	 &vbsEvent.mass_lvj_type0_met_PuppiAK8_jes_dn );
	 vbsTree->SetBranchAddress( "mass_lvj_type0_met_PuppiAK8_jes_up", 	 &vbsEvent.mass_lvj_type0_met_PuppiAK8_jes_up );
	 vbsTree->SetBranchAddress( "mass_lvj_type0_met_jer", 	 &vbsEvent.mass_lvj_type0_met_jer );
	 vbsTree->SetBranchAddress( "mass_lvj_type0_met_jer_dn", 	 &vbsEvent.mass_lvj_type0_met_jer_dn );
	 vbsTree->SetBranchAddress( "mass_lvj_type0_met_jer_up", 	 &vbsEvent.mass_lvj_type0_met_jer_up );
	 vbsTree->SetBranchAddress( "mass_lvj_type0_met_jes_dn", 	 &vbsEvent.mass_lvj_type0_met_jes_dn );
	 vbsTree->SetBranchAddress( "mass_lvj_type0_met_jes_up", 	 &vbsEvent.mass_lvj_type0_met_jes_up );
	 vbsTree->SetBranchAddress( "mass_lvj_type2", 	 &vbsEvent.mass_lvj_type2 );
	 vbsTree->SetBranchAddress( "mass_lvj_type2_PuppiAK8", 	 &vbsEvent.mass_lvj_type2_PuppiAK8 );
	 vbsTree->SetBranchAddress( "mass_lvjj_run2_AK4", 	 &vbsEvent.mass_lvjj_run2_AK4 );
	 vbsTree->SetBranchAddress( "mass_lvjj_run2_PuppiAK4", 	 &vbsEvent.mass_lvjj_run2_PuppiAK4 );
	 vbsTree->SetBranchAddress( "mass_lvjj_type0_AK4", 	 &vbsEvent.mass_lvjj_type0_AK4 );
	 vbsTree->SetBranchAddress( "mass_lvjj_type0_PuppiAK4", 	 &vbsEvent.mass_lvjj_type0_PuppiAK4 );
	 vbsTree->SetBranchAddress( "mass_lvjj_type0_met_jes_dn_AK4", 	 &vbsEvent.mass_lvjj_type0_met_jes_dn_AK4 );
	 vbsTree->SetBranchAddress( "mass_lvjj_type0_met_jes_dn_PuppiAK4", 	 &vbsEvent.mass_lvjj_type0_met_jes_dn_PuppiAK4 );
	 vbsTree->SetBranchAddress( "mass_lvjj_type0_met_jes_up_AK4", 	 &vbsEvent.mass_lvjj_type0_met_jes_up_AK4 );
	 vbsTree->SetBranchAddress( "mass_lvjj_type0_met_jes_up_PuppiAK4", 	 &vbsEvent.mass_lvjj_type0_met_jes_up_PuppiAK4 );
	 vbsTree->SetBranchAddress( "mass_lvjj_type2_AK4", 	 &vbsEvent.mass_lvjj_type2_AK4 );
	 vbsTree->SetBranchAddress( "mass_lvjj_type2_PuppiAK4", 	 &vbsEvent.mass_lvjj_type2_PuppiAK4 );
	 vbsTree->SetBranchAddress( "mass_ungroomedjet_closerjet", 	 &vbsEvent.mass_ungroomedjet_closerjet );
	 vbsTree->SetBranchAddress( "mt_lvj_run2_PuppiAK8", 	 &vbsEvent.mt_lvj_run2_PuppiAK8 );
	 vbsTree->SetBranchAddress( "mt_lvj_type0_PuppiAK8", 	 &vbsEvent.mt_lvj_type0_PuppiAK8 );
	 vbsTree->SetBranchAddress( "mt_lvj_type2_PuppiAK8", 	 &vbsEvent.mt_lvj_type2_PuppiAK8 );
	 vbsTree->SetBranchAddress( "nu_pz_run2", 	 &vbsEvent.nu_pz_run2 );
	 vbsTree->SetBranchAddress( "nu_pz_run2_oth", 	 &vbsEvent.nu_pz_run2_oth );
	 vbsTree->SetBranchAddress( "nu_pz_type0", 	 &vbsEvent.nu_pz_type0 );
	 vbsTree->SetBranchAddress( "nu_pz_type2", 	 &vbsEvent.nu_pz_type2 );
	 vbsTree->SetBranchAddress( "pfMET", 	 &vbsEvent.pfMET );
	 vbsTree->SetBranchAddress( "pfMET_Corr", 	 &vbsEvent.pfMET_Corr );
	 vbsTree->SetBranchAddress( "pfMET_Corr_Cov00", 	 &vbsEvent.pfMET_Corr_Cov00 );
	 vbsTree->SetBranchAddress( "pfMET_Corr_Cov01", 	 &vbsEvent.pfMET_Corr_Cov01 );
	 vbsTree->SetBranchAddress( "pfMET_Corr_Cov11", 	 &vbsEvent.pfMET_Corr_Cov11 );
	 vbsTree->SetBranchAddress( "pfMET_Corr_jendn", 	 &vbsEvent.pfMET_Corr_jendn );
	 vbsTree->SetBranchAddress( "pfMET_Corr_jenup", 	 &vbsEvent.pfMET_Corr_jenup );
	 vbsTree->SetBranchAddress( "pfMET_Corr_jerdn", 	 &vbsEvent.pfMET_Corr_jerdn );
	 vbsTree->SetBranchAddress( "pfMET_Corr_jerup", 	 &vbsEvent.pfMET_Corr_jerup );
	 vbsTree->SetBranchAddress( "pfMET_Corr_jrsdn", 	 &vbsEvent.pfMET_Corr_jrsdn );
	 vbsTree->SetBranchAddress( "pfMET_Corr_jrsup", 	 &vbsEvent.pfMET_Corr_jrsup );
	 vbsTree->SetBranchAddress( "pfMET_Corr_phi", 	 &vbsEvent.pfMET_Corr_phi );
	 vbsTree->SetBranchAddress( "pfMET_Corr_phijendn", 	 &vbsEvent.pfMET_Corr_phijendn );
	 vbsTree->SetBranchAddress( "pfMET_Corr_phijenup", 	 &vbsEvent.pfMET_Corr_phijenup );
	 vbsTree->SetBranchAddress( "pfMET_Corr_phijerdn", 	 &vbsEvent.pfMET_Corr_phijerdn );
	 vbsTree->SetBranchAddress( "pfMET_Corr_phijerup", 	 &vbsEvent.pfMET_Corr_phijerup );
	 vbsTree->SetBranchAddress( "pfMET_Corr_phijrsdn", 	 &vbsEvent.pfMET_Corr_phijrsdn );
	 vbsTree->SetBranchAddress( "pfMET_Corr_phijrsup", 	 &vbsEvent.pfMET_Corr_phijrsup );
	 vbsTree->SetBranchAddress( "pfMET_Corr_phiuncdn", 	 &vbsEvent.pfMET_Corr_phiuncdn );
	 vbsTree->SetBranchAddress( "pfMET_Corr_phiuncup", 	 &vbsEvent.pfMET_Corr_phiuncup );
	 vbsTree->SetBranchAddress( "pfMET_Corr_uncdn", 	 &vbsEvent.pfMET_Corr_uncdn );
	 vbsTree->SetBranchAddress( "pfMET_Corr_uncup", 	 &vbsEvent.pfMET_Corr_uncup );
	 vbsTree->SetBranchAddress( "pfMET_Phi", 	 &vbsEvent.pfMET_Phi );
	 vbsTree->SetBranchAddress( "pfMET_jes_dn", 	 &vbsEvent.pfMET_jes_dn );
	 vbsTree->SetBranchAddress( "pfMET_jes_up", 	 &vbsEvent.pfMET_jes_up );
	 vbsTree->SetBranchAddress( "pfMETpuppi", 	 &vbsEvent.pfMETpuppi );
	 vbsTree->SetBranchAddress( "pfMETpuppi_Corr", 	 &vbsEvent.pfMETpuppi_Corr );
	 vbsTree->SetBranchAddress( "pfMETpuppi_Corr_Cov00", 	 &vbsEvent.pfMETpuppi_Corr_Cov00 );
	 vbsTree->SetBranchAddress( "pfMETpuppi_Corr_Cov01", 	 &vbsEvent.pfMETpuppi_Corr_Cov01 );
	 vbsTree->SetBranchAddress( "pfMETpuppi_Corr_Cov11", 	 &vbsEvent.pfMETpuppi_Corr_Cov11 );
	 vbsTree->SetBranchAddress( "pfMETpuppi_Corr_phi", 	 &vbsEvent.pfMETpuppi_Corr_phi );
	 vbsTree->SetBranchAddress( "pfMETpuppi_Cov00", 	 &vbsEvent.pfMETpuppi_Cov00 );
	 vbsTree->SetBranchAddress( "pfMETpuppi_Cov01", 	 &vbsEvent.pfMETpuppi_Cov01 );
	 vbsTree->SetBranchAddress( "pfMETpuppi_Cov11", 	 &vbsEvent.pfMETpuppi_Cov11 );
	 vbsTree->SetBranchAddress( "pfMETpuppi_Phi", 	 &vbsEvent.pfMETpuppi_Phi );
	 vbsTree->SetBranchAddress( "pfMETpuppi_jer", 	 &vbsEvent.pfMETpuppi_jer );
	 vbsTree->SetBranchAddress( "pfMETpuppi_jer_dn", 	 &vbsEvent.pfMETpuppi_jer_dn );
	 vbsTree->SetBranchAddress( "pfMETpuppi_jer_up", 	 &vbsEvent.pfMETpuppi_jer_up );
	 vbsTree->SetBranchAddress( "pfMETpuppi_jes_dn", 	 &vbsEvent.pfMETpuppi_jes_dn );
	 vbsTree->SetBranchAddress( "pfMETpuppi_jes_up", 	 &vbsEvent.pfMETpuppi_jes_up );
	 vbsTree->SetBranchAddress( "phi1Puppi_run2", 	 &vbsEvent.phi1Puppi_run2 );
	 vbsTree->SetBranchAddress( "phi1Puppi_type0", 	 &vbsEvent.phi1Puppi_type0 );
	 vbsTree->SetBranchAddress( "phi1Puppi_type2", 	 &vbsEvent.phi1Puppi_type2 );
	 vbsTree->SetBranchAddress( "phi1_2Lep", 	 &vbsEvent.phi1_2Lep );
	 vbsTree->SetBranchAddress( "phi1_run2", 	 &vbsEvent.phi1_run2 );
	 vbsTree->SetBranchAddress( "phi1_type0", 	 &vbsEvent.phi1_type0 );
	 vbsTree->SetBranchAddress( "phi1_type2", 	 &vbsEvent.phi1_type2 );
	 vbsTree->SetBranchAddress( "phiPuppi_run2", 	 &vbsEvent.phiPuppi_run2 );
	 vbsTree->SetBranchAddress( "phiPuppi_type0", 	 &vbsEvent.phiPuppi_type0 );
	 vbsTree->SetBranchAddress( "phiPuppi_type2", 	 &vbsEvent.phiPuppi_type2 );
	 vbsTree->SetBranchAddress( "phi_2Lep", 	 &vbsEvent.phi_2Lep );
	 vbsTree->SetBranchAddress( "phi_llj_PuppiAK8", 	 &vbsEvent.phi_llj_PuppiAK8 );
	 vbsTree->SetBranchAddress( "phi_lvj_run2_PuppiAK8", 	 &vbsEvent.phi_lvj_run2_PuppiAK8 );
	 vbsTree->SetBranchAddress( "phi_lvj_type0_PuppiAK8", 	 &vbsEvent.phi_lvj_type0_PuppiAK8 );
	 vbsTree->SetBranchAddress( "phi_lvj_type2_PuppiAK8", 	 &vbsEvent.phi_lvj_type2_PuppiAK8 );
	 vbsTree->SetBranchAddress( "phi_run2", 	 &vbsEvent.phi_run2 );
	 vbsTree->SetBranchAddress( "phi_type0", 	 &vbsEvent.phi_type0 );
	 vbsTree->SetBranchAddress( "phi_type2", 	 &vbsEvent.phi_type2 );
	 vbsTree->SetBranchAddress( "pt_llj_PuppiAK8", 	 &vbsEvent.pt_llj_PuppiAK8 );
	 vbsTree->SetBranchAddress( "pt_lvj_run2_PuppiAK8", 	 &vbsEvent.pt_lvj_run2_PuppiAK8 );
	 vbsTree->SetBranchAddress( "pt_lvj_type0_PuppiAK8", 	 &vbsEvent.pt_lvj_type0_PuppiAK8 );
	 vbsTree->SetBranchAddress( "pt_lvj_type2_PuppiAK8", 	 &vbsEvent.pt_lvj_type2_PuppiAK8 );
	 vbsTree->SetBranchAddress( "pu_Weight", 	 &vbsEvent.pu_Weight );
	 vbsTree->SetBranchAddress( "pu_Weight_down", 	 &vbsEvent.pu_Weight_down );
	 vbsTree->SetBranchAddress( "pu_Weight_up", 	 &vbsEvent.pu_Weight_up );
	 vbsTree->SetBranchAddress( "rapidity_lvj_run2_PuppiAK8", 	 &vbsEvent.rapidity_lvj_run2_PuppiAK8 );
	 vbsTree->SetBranchAddress( "rapidity_lvj_type0_PuppiAK8", 	 &vbsEvent.rapidity_lvj_type0_PuppiAK8 );
	 vbsTree->SetBranchAddress( "rapidity_lvj_type2_PuppiAK8", 	 &vbsEvent.rapidity_lvj_type2_PuppiAK8 );
	 vbsTree->SetBranchAddress( "top1_NNLO_Weight", 	 &vbsEvent.top1_NNLO_Weight );
	 vbsTree->SetBranchAddress( "top2_NNLO_Weight", 	 &vbsEvent.top2_NNLO_Weight );
	 vbsTree->SetBranchAddress( "totalEventWeight", 	 &vbsEvent.totalEventWeight );
	 vbsTree->SetBranchAddress( "totalEventWeight_2", 	 &vbsEvent.totalEventWeight_2 );
	 vbsTree->SetBranchAddress( "totalEventWeight_2Lep", 	 &vbsEvent.totalEventWeight_2Lep );
	 vbsTree->SetBranchAddress( "totalEventWeight_3", 	 &vbsEvent.totalEventWeight_3 );
	 vbsTree->SetBranchAddress( "trig_eff_Weight", 	 &vbsEvent.trig_eff_Weight );
	 vbsTree->SetBranchAddress( "trig_eff_Weight2", 	 &vbsEvent.trig_eff_Weight2 );
	 vbsTree->SetBranchAddress( "trig_eff_Weight2_Down", 	 &vbsEvent.trig_eff_Weight2_Down );
	 vbsTree->SetBranchAddress( "trig_eff_Weight2_Up", 	 &vbsEvent.trig_eff_Weight2_Up );
	 vbsTree->SetBranchAddress( "trig_eff_Weight_Down", 	 &vbsEvent.trig_eff_Weight_Down );
	 vbsTree->SetBranchAddress( "trig_eff_Weight_Up", 	 &vbsEvent.trig_eff_Weight_Up );
	 vbsTree->SetBranchAddress( "ttb_deltaeta_lak8jet", 	 &vbsEvent.ttb_deltaeta_lak8jet );
	 vbsTree->SetBranchAddress( "ttb_ungroomed_jet_e", 	 &vbsEvent.ttb_ungroomed_jet_e );
	 vbsTree->SetBranchAddress( "ttb_ungroomed_jet_eta", 	 &vbsEvent.ttb_ungroomed_jet_eta );
	 vbsTree->SetBranchAddress( "ttb_ungroomed_jet_phi", 	 &vbsEvent.ttb_ungroomed_jet_phi );
	 vbsTree->SetBranchAddress( "ttb_ungroomed_jet_pt", 	 &vbsEvent.ttb_ungroomed_jet_pt );
	 vbsTree->SetBranchAddress( "ungroomed_AK8jet_e", 	 &vbsEvent.ungroomed_AK8jet_e );
	 vbsTree->SetBranchAddress( "ungroomed_AK8jet_eta", 	 &vbsEvent.ungroomed_AK8jet_eta );
	 vbsTree->SetBranchAddress( "ungroomed_AK8jet_eta_jes_dn", 	 &vbsEvent.ungroomed_AK8jet_eta_jes_dn );
	 vbsTree->SetBranchAddress( "ungroomed_AK8jet_eta_jes_up", 	 &vbsEvent.ungroomed_AK8jet_eta_jes_up );
	 vbsTree->SetBranchAddress( "ungroomed_AK8jet_mass_jes_dn", 	 &vbsEvent.ungroomed_AK8jet_mass_jes_dn );
	 vbsTree->SetBranchAddress( "ungroomed_AK8jet_mass_jes_up", 	 &vbsEvent.ungroomed_AK8jet_mass_jes_up );
	 vbsTree->SetBranchAddress( "ungroomed_AK8jet_phi", 	 &vbsEvent.ungroomed_AK8jet_phi );
	 vbsTree->SetBranchAddress( "ungroomed_AK8jet_phi_jes_dn", 	 &vbsEvent.ungroomed_AK8jet_phi_jes_dn );
	 vbsTree->SetBranchAddress( "ungroomed_AK8jet_phi_jes_up", 	 &vbsEvent.ungroomed_AK8jet_phi_jes_up );
	 vbsTree->SetBranchAddress( "ungroomed_AK8jet_pt", 	 &vbsEvent.ungroomed_AK8jet_pt );
	 vbsTree->SetBranchAddress( "ungroomed_AK8jet_pt_jer", 	 &vbsEvent.ungroomed_AK8jet_pt_jer );
	 vbsTree->SetBranchAddress( "ungroomed_AK8jet_pt_jer_dn", 	 &vbsEvent.ungroomed_AK8jet_pt_jer_dn );
	 vbsTree->SetBranchAddress( "ungroomed_AK8jet_pt_jer_up", 	 &vbsEvent.ungroomed_AK8jet_pt_jer_up );
	 vbsTree->SetBranchAddress( "ungroomed_AK8jet_pt_jes_dn", 	 &vbsEvent.ungroomed_AK8jet_pt_jes_dn );
	 vbsTree->SetBranchAddress( "ungroomed_AK8jet_pt_jes_up", 	 &vbsEvent.ungroomed_AK8jet_pt_jes_up );
	 vbsTree->SetBranchAddress( "ungroomed_PuppiAK8_jet_e", 	 &vbsEvent.ungroomed_PuppiAK8_jet_e );
	 vbsTree->SetBranchAddress( "ungroomed_PuppiAK8_jet_eta", 	 &vbsEvent.ungroomed_PuppiAK8_jet_eta );
	 vbsTree->SetBranchAddress( "ungroomed_PuppiAK8_jet_eta_jes_dn", 	 &vbsEvent.ungroomed_PuppiAK8_jet_eta_jes_dn );
	 vbsTree->SetBranchAddress( "ungroomed_PuppiAK8_jet_eta_jes_up", 	 &vbsEvent.ungroomed_PuppiAK8_jet_eta_jes_up );
	 vbsTree->SetBranchAddress( "ungroomed_PuppiAK8_jet_mass_jes_dn", 	 &vbsEvent.ungroomed_PuppiAK8_jet_mass_jes_dn );
	 vbsTree->SetBranchAddress( "ungroomed_PuppiAK8_jet_mass_jes_up", 	 &vbsEvent.ungroomed_PuppiAK8_jet_mass_jes_up );
	 vbsTree->SetBranchAddress( "ungroomed_PuppiAK8_jet_phi", 	 &vbsEvent.ungroomed_PuppiAK8_jet_phi );
	 vbsTree->SetBranchAddress( "ungroomed_PuppiAK8_jet_phi_jes_dn", 	 &vbsEvent.ungroomed_PuppiAK8_jet_phi_jes_dn );
	 vbsTree->SetBranchAddress( "ungroomed_PuppiAK8_jet_phi_jes_up", 	 &vbsEvent.ungroomed_PuppiAK8_jet_phi_jes_up );
	 vbsTree->SetBranchAddress( "ungroomed_PuppiAK8_jet_pt", 	 &vbsEvent.ungroomed_PuppiAK8_jet_pt );
	 vbsTree->SetBranchAddress( "ungroomed_PuppiAK8_jet_pt_jer", 	 &vbsEvent.ungroomed_PuppiAK8_jet_pt_jer );
	 vbsTree->SetBranchAddress( "ungroomed_PuppiAK8_jet_pt_jer_dn", 	 &vbsEvent.ungroomed_PuppiAK8_jet_pt_jer_dn );
	 vbsTree->SetBranchAddress( "ungroomed_PuppiAK8_jet_pt_jer_up", 	 &vbsEvent.ungroomed_PuppiAK8_jet_pt_jer_up );
	 vbsTree->SetBranchAddress( "ungroomed_PuppiAK8_jet_pt_jes_dn", 	 &vbsEvent.ungroomed_PuppiAK8_jet_pt_jes_dn );
	 vbsTree->SetBranchAddress( "ungroomed_PuppiAK8_jet_pt_jes_up", 	 &vbsEvent.ungroomed_PuppiAK8_jet_pt_jes_up );
	 vbsTree->SetBranchAddress( "v_eta_run2", 	 &vbsEvent.v_eta_run2 );
	 vbsTree->SetBranchAddress( "v_eta_type0", 	 &vbsEvent.v_eta_type0 );
	 vbsTree->SetBranchAddress( "v_eta_type0_jer_dn", 	 &vbsEvent.v_eta_type0_jer_dn );
	 vbsTree->SetBranchAddress( "v_eta_type0_jer_up", 	 &vbsEvent.v_eta_type0_jer_up );
	 vbsTree->SetBranchAddress( "v_eta_type0_jes_dn", 	 &vbsEvent.v_eta_type0_jes_dn );
	 vbsTree->SetBranchAddress( "v_eta_type0_jes_up", 	 &vbsEvent.v_eta_type0_jes_up );
	 vbsTree->SetBranchAddress( "v_eta_type2", 	 &vbsEvent.v_eta_type2 );
	 vbsTree->SetBranchAddress( "v_mass_run2", 	 &vbsEvent.v_mass_run2 );
	 vbsTree->SetBranchAddress( "v_mass_type0", 	 &vbsEvent.v_mass_type0 );
	 vbsTree->SetBranchAddress( "v_mass_type0_jer_dn", 	 &vbsEvent.v_mass_type0_jer_dn );
	 vbsTree->SetBranchAddress( "v_mass_type0_jer_up", 	 &vbsEvent.v_mass_type0_jer_up );
	 vbsTree->SetBranchAddress( "v_mass_type0_jes_dn", 	 &vbsEvent.v_mass_type0_jes_dn );
	 vbsTree->SetBranchAddress( "v_mass_type0_jes_up", 	 &vbsEvent.v_mass_type0_jes_up );
	 vbsTree->SetBranchAddress( "v_mass_type2", 	 &vbsEvent.v_mass_type2 );
	 vbsTree->SetBranchAddress( "v_mt_run2", 	 &vbsEvent.v_mt_run2 );
	 vbsTree->SetBranchAddress( "v_mt_type0", 	 &vbsEvent.v_mt_type0 );
	 vbsTree->SetBranchAddress( "v_mt_type0_jer_dn", 	 &vbsEvent.v_mt_type0_jer_dn );
	 vbsTree->SetBranchAddress( "v_mt_type0_jer_up", 	 &vbsEvent.v_mt_type0_jer_up );
	 vbsTree->SetBranchAddress( "v_mt_type0_jes_dn", 	 &vbsEvent.v_mt_type0_jes_dn );
	 vbsTree->SetBranchAddress( "v_mt_type0_jes_up", 	 &vbsEvent.v_mt_type0_jes_up );
	 vbsTree->SetBranchAddress( "v_mt_type2", 	 &vbsEvent.v_mt_type2 );
	 vbsTree->SetBranchAddress( "v_phi", 	 &vbsEvent.v_phi );
	 vbsTree->SetBranchAddress( "v_pt_run2", 	 &vbsEvent.v_pt_run2 );
	 vbsTree->SetBranchAddress( "v_pt_type0", 	 &vbsEvent.v_pt_type0 );
	 vbsTree->SetBranchAddress( "v_pt_type0_jer_dn", 	 &vbsEvent.v_pt_type0_jer_dn );
	 vbsTree->SetBranchAddress( "v_pt_type0_jer_up", 	 &vbsEvent.v_pt_type0_jer_up );
	 vbsTree->SetBranchAddress( "v_pt_type0_jes_dn", 	 &vbsEvent.v_pt_type0_jes_dn );
	 vbsTree->SetBranchAddress( "v_pt_type0_jes_up", 	 &vbsEvent.v_pt_type0_jes_up );
	 vbsTree->SetBranchAddress( "v_pt_type2", 	 &vbsEvent.v_pt_type2 );
	 vbsTree->SetBranchAddress( "v_puppi_eta_run2", 	 &vbsEvent.v_puppi_eta_run2 );
	 vbsTree->SetBranchAddress( "v_puppi_eta_type0", 	 &vbsEvent.v_puppi_eta_type0 );
	 vbsTree->SetBranchAddress( "v_puppi_eta_type2", 	 &vbsEvent.v_puppi_eta_type2 );
	 vbsTree->SetBranchAddress( "v_puppi_mass_run2", 	 &vbsEvent.v_puppi_mass_run2 );
	 vbsTree->SetBranchAddress( "v_puppi_mass_type0", 	 &vbsEvent.v_puppi_mass_type0 );
	 vbsTree->SetBranchAddress( "v_puppi_mass_type2", 	 &vbsEvent.v_puppi_mass_type2 );
	 vbsTree->SetBranchAddress( "v_puppi_mt_run2", 	 &vbsEvent.v_puppi_mt_run2 );
	 vbsTree->SetBranchAddress( "v_puppi_mt_type0", 	 &vbsEvent.v_puppi_mt_type0 );
	 vbsTree->SetBranchAddress( "v_puppi_mt_type2", 	 &vbsEvent.v_puppi_mt_type2 );
	 vbsTree->SetBranchAddress( "v_puppi_phi", 	 &vbsEvent.v_puppi_phi );
	 vbsTree->SetBranchAddress( "v_puppi_pt_run2", 	 &vbsEvent.v_puppi_pt_run2 );
	 vbsTree->SetBranchAddress( "v_puppi_pt_type0", 	 &vbsEvent.v_puppi_pt_type0 );
	 vbsTree->SetBranchAddress( "v_puppi_pt_type2", 	 &vbsEvent.v_puppi_pt_type2 );
	 vbsTree->SetBranchAddress( "vbfPuppi_maxpt_deltaR", 	 &vbsEvent.vbfPuppi_maxpt_deltaR );
	 vbsTree->SetBranchAddress( "vbfPuppi_maxpt_j1_ID", 	 &vbsEvent.vbfPuppi_maxpt_j1_ID );
	 vbsTree->SetBranchAddress( "vbfPuppi_maxpt_j1_bDiscriminatorCSV", 	 &vbsEvent.vbfPuppi_maxpt_j1_bDiscriminatorCSV );
	 vbsTree->SetBranchAddress( "vbfPuppi_maxpt_j1_e", 	 &vbsEvent.vbfPuppi_maxpt_j1_e );
	 vbsTree->SetBranchAddress( "vbfPuppi_maxpt_j1_eta", 	 &vbsEvent.vbfPuppi_maxpt_j1_eta );
	 vbsTree->SetBranchAddress( "vbfPuppi_maxpt_j1_eta_jer", 	 &vbsEvent.vbfPuppi_maxpt_j1_eta_jer );
	 vbsTree->SetBranchAddress( "vbfPuppi_maxpt_j1_eta_jer_dn", 	 &vbsEvent.vbfPuppi_maxpt_j1_eta_jer_dn );
	 vbsTree->SetBranchAddress( "vbfPuppi_maxpt_j1_eta_jer_up", 	 &vbsEvent.vbfPuppi_maxpt_j1_eta_jer_up );
	 vbsTree->SetBranchAddress( "vbfPuppi_maxpt_j1_eta_jes_dn", 	 &vbsEvent.vbfPuppi_maxpt_j1_eta_jes_dn );
	 vbsTree->SetBranchAddress( "vbfPuppi_maxpt_j1_eta_jes_up", 	 &vbsEvent.vbfPuppi_maxpt_j1_eta_jes_up );
	 vbsTree->SetBranchAddress( "vbfPuppi_maxpt_j1_phi", 	 &vbsEvent.vbfPuppi_maxpt_j1_phi );
	 vbsTree->SetBranchAddress( "vbfPuppi_maxpt_j1_pt", 	 &vbsEvent.vbfPuppi_maxpt_j1_pt );
	 vbsTree->SetBranchAddress( "vbfPuppi_maxpt_j1_pt_jer", 	 &vbsEvent.vbfPuppi_maxpt_j1_pt_jer );
	 vbsTree->SetBranchAddress( "vbfPuppi_maxpt_j1_pt_jer_dn", 	 &vbsEvent.vbfPuppi_maxpt_j1_pt_jer_dn );
	 vbsTree->SetBranchAddress( "vbfPuppi_maxpt_j1_pt_jer_up", 	 &vbsEvent.vbfPuppi_maxpt_j1_pt_jer_up );
	 vbsTree->SetBranchAddress( "vbfPuppi_maxpt_j1_pt_jes_dn", 	 &vbsEvent.vbfPuppi_maxpt_j1_pt_jes_dn );
	 vbsTree->SetBranchAddress( "vbfPuppi_maxpt_j1_pt_jes_up", 	 &vbsEvent.vbfPuppi_maxpt_j1_pt_jes_up );
	 vbsTree->SetBranchAddress( "vbfPuppi_maxpt_j2_ID", 	 &vbsEvent.vbfPuppi_maxpt_j2_ID );
	 vbsTree->SetBranchAddress( "vbfPuppi_maxpt_j2_bDiscriminatorCSV", 	 &vbsEvent.vbfPuppi_maxpt_j2_bDiscriminatorCSV );
	 vbsTree->SetBranchAddress( "vbfPuppi_maxpt_j2_e", 	 &vbsEvent.vbfPuppi_maxpt_j2_e );
	 vbsTree->SetBranchAddress( "vbfPuppi_maxpt_j2_eta", 	 &vbsEvent.vbfPuppi_maxpt_j2_eta );
	 vbsTree->SetBranchAddress( "vbfPuppi_maxpt_j2_eta_jer", 	 &vbsEvent.vbfPuppi_maxpt_j2_eta_jer );
	 vbsTree->SetBranchAddress( "vbfPuppi_maxpt_j2_eta_jer_dn", 	 &vbsEvent.vbfPuppi_maxpt_j2_eta_jer_dn );
	 vbsTree->SetBranchAddress( "vbfPuppi_maxpt_j2_eta_jer_up", 	 &vbsEvent.vbfPuppi_maxpt_j2_eta_jer_up );
	 vbsTree->SetBranchAddress( "vbfPuppi_maxpt_j2_eta_jes_dn", 	 &vbsEvent.vbfPuppi_maxpt_j2_eta_jes_dn );
	 vbsTree->SetBranchAddress( "vbfPuppi_maxpt_j2_eta_jes_up", 	 &vbsEvent.vbfPuppi_maxpt_j2_eta_jes_up );
	 vbsTree->SetBranchAddress( "vbfPuppi_maxpt_j2_phi", 	 &vbsEvent.vbfPuppi_maxpt_j2_phi );
	 vbsTree->SetBranchAddress( "vbfPuppi_maxpt_j2_pt", 	 &vbsEvent.vbfPuppi_maxpt_j2_pt );
	 vbsTree->SetBranchAddress( "vbfPuppi_maxpt_j2_pt_jer", 	 &vbsEvent.vbfPuppi_maxpt_j2_pt_jer );
	 vbsTree->SetBranchAddress( "vbfPuppi_maxpt_j2_pt_jer_dn", 	 &vbsEvent.vbfPuppi_maxpt_j2_pt_jer_dn );
	 vbsTree->SetBranchAddress( "vbfPuppi_maxpt_j2_pt_jer_up", 	 &vbsEvent.vbfPuppi_maxpt_j2_pt_jer_up );
	 vbsTree->SetBranchAddress( "vbfPuppi_maxpt_j2_pt_jes_dn", 	 &vbsEvent.vbfPuppi_maxpt_j2_pt_jes_dn );
	 vbsTree->SetBranchAddress( "vbfPuppi_maxpt_j2_pt_jes_up", 	 &vbsEvent.vbfPuppi_maxpt_j2_pt_jes_up );
	 vbsTree->SetBranchAddress( "vbfPuppi_maxpt_jj_Deta", 	 &vbsEvent.vbfPuppi_maxpt_jj_Deta );
	 vbsTree->SetBranchAddress( "vbfPuppi_maxpt_jj_eta", 	 &vbsEvent.vbfPuppi_maxpt_jj_eta );
	 vbsTree->SetBranchAddress( "vbfPuppi_maxpt_jj_m", 	 &vbsEvent.vbfPuppi_maxpt_jj_m );
	 vbsTree->SetBranchAddress( "vbfPuppi_maxpt_jj_phi", 	 &vbsEvent.vbfPuppi_maxpt_jj_phi );
	 vbsTree->SetBranchAddress( "vbfPuppi_maxpt_jj_pt", 	 &vbsEvent.vbfPuppi_maxpt_jj_pt );
	 vbsTree->SetBranchAddress( "vbf_maxpt_deltaR", 	 &vbsEvent.vbf_maxpt_deltaR );
	 vbsTree->SetBranchAddress( "vbf_maxpt_j1_bDiscriminatorCSV", 	 &vbsEvent.vbf_maxpt_j1_bDiscriminatorCSV );
	 vbsTree->SetBranchAddress( "vbf_maxpt_j1_e", 	 &vbsEvent.vbf_maxpt_j1_e );
	 vbsTree->SetBranchAddress( "vbf_maxpt_j1_eta", 	 &vbsEvent.vbf_maxpt_j1_eta );
	 vbsTree->SetBranchAddress( "vbf_maxpt_j1_eta_jer", 	 &vbsEvent.vbf_maxpt_j1_eta_jer );
	 vbsTree->SetBranchAddress( "vbf_maxpt_j1_eta_jer_dn", 	 &vbsEvent.vbf_maxpt_j1_eta_jer_dn );
	 vbsTree->SetBranchAddress( "vbf_maxpt_j1_eta_jer_up", 	 &vbsEvent.vbf_maxpt_j1_eta_jer_up );
	 vbsTree->SetBranchAddress( "vbf_maxpt_j1_eta_jes_dn", 	 &vbsEvent.vbf_maxpt_j1_eta_jes_dn );
	 vbsTree->SetBranchAddress( "vbf_maxpt_j1_eta_jes_up", 	 &vbsEvent.vbf_maxpt_j1_eta_jes_up );
	 vbsTree->SetBranchAddress( "vbf_maxpt_j1_mass", 	 &vbsEvent.vbf_maxpt_j1_mass );
	 vbsTree->SetBranchAddress( "vbf_maxpt_j1_mass_jes_dn", 	 &vbsEvent.vbf_maxpt_j1_mass_jes_dn );
	 vbsTree->SetBranchAddress( "vbf_maxpt_j1_mass_jes_up", 	 &vbsEvent.vbf_maxpt_j1_mass_jes_up );
	 vbsTree->SetBranchAddress( "vbf_maxpt_j1_phi", 	 &vbsEvent.vbf_maxpt_j1_phi );
	 vbsTree->SetBranchAddress( "vbf_maxpt_j1_phi_jes_dn", 	 &vbsEvent.vbf_maxpt_j1_phi_jes_dn );
	 vbsTree->SetBranchAddress( "vbf_maxpt_j1_phi_jes_up", 	 &vbsEvent.vbf_maxpt_j1_phi_jes_up );
	 vbsTree->SetBranchAddress( "vbf_maxpt_j1_pt", 	 &vbsEvent.vbf_maxpt_j1_pt );
	 vbsTree->SetBranchAddress( "vbf_maxpt_j1_pt_jer", 	 &vbsEvent.vbf_maxpt_j1_pt_jer );
	 vbsTree->SetBranchAddress( "vbf_maxpt_j1_pt_jer_dn", 	 &vbsEvent.vbf_maxpt_j1_pt_jer_dn );
	 vbsTree->SetBranchAddress( "vbf_maxpt_j1_pt_jer_up", 	 &vbsEvent.vbf_maxpt_j1_pt_jer_up );
	 vbsTree->SetBranchAddress( "vbf_maxpt_j1_pt_jes_dn", 	 &vbsEvent.vbf_maxpt_j1_pt_jes_dn );
	 vbsTree->SetBranchAddress( "vbf_maxpt_j1_pt_jes_up", 	 &vbsEvent.vbf_maxpt_j1_pt_jes_up );
	 vbsTree->SetBranchAddress( "vbf_maxpt_j2_bDiscriminatorCSV", 	 &vbsEvent.vbf_maxpt_j2_bDiscriminatorCSV );
	 vbsTree->SetBranchAddress( "vbf_maxpt_j2_e", 	 &vbsEvent.vbf_maxpt_j2_e );
	 vbsTree->SetBranchAddress( "vbf_maxpt_j2_eta", 	 &vbsEvent.vbf_maxpt_j2_eta );
	 vbsTree->SetBranchAddress( "vbf_maxpt_j2_eta_jer", 	 &vbsEvent.vbf_maxpt_j2_eta_jer );
	 vbsTree->SetBranchAddress( "vbf_maxpt_j2_eta_jer_dn", 	 &vbsEvent.vbf_maxpt_j2_eta_jer_dn );
	 vbsTree->SetBranchAddress( "vbf_maxpt_j2_eta_jer_up", 	 &vbsEvent.vbf_maxpt_j2_eta_jer_up );
	 vbsTree->SetBranchAddress( "vbf_maxpt_j2_eta_jes_dn", 	 &vbsEvent.vbf_maxpt_j2_eta_jes_dn );
	 vbsTree->SetBranchAddress( "vbf_maxpt_j2_eta_jes_up", 	 &vbsEvent.vbf_maxpt_j2_eta_jes_up );
	 vbsTree->SetBranchAddress( "vbf_maxpt_j2_mass", 	 &vbsEvent.vbf_maxpt_j2_mass );
	 vbsTree->SetBranchAddress( "vbf_maxpt_j2_mass_jes_dn", 	 &vbsEvent.vbf_maxpt_j2_mass_jes_dn );
	 vbsTree->SetBranchAddress( "vbf_maxpt_j2_mass_jes_up", 	 &vbsEvent.vbf_maxpt_j2_mass_jes_up );
	 vbsTree->SetBranchAddress( "vbf_maxpt_j2_phi", 	 &vbsEvent.vbf_maxpt_j2_phi );
	 vbsTree->SetBranchAddress( "vbf_maxpt_j2_phi_jes_dn", 	 &vbsEvent.vbf_maxpt_j2_phi_jes_dn );
	 vbsTree->SetBranchAddress( "vbf_maxpt_j2_phi_jes_up", 	 &vbsEvent.vbf_maxpt_j2_phi_jes_up );
	 vbsTree->SetBranchAddress( "vbf_maxpt_j2_pt", 	 &vbsEvent.vbf_maxpt_j2_pt );
	 vbsTree->SetBranchAddress( "vbf_maxpt_j2_pt_jer", 	 &vbsEvent.vbf_maxpt_j2_pt_jer );
	 vbsTree->SetBranchAddress( "vbf_maxpt_j2_pt_jer_dn", 	 &vbsEvent.vbf_maxpt_j2_pt_jer_dn );
	 vbsTree->SetBranchAddress( "vbf_maxpt_j2_pt_jer_up", 	 &vbsEvent.vbf_maxpt_j2_pt_jer_up );
	 vbsTree->SetBranchAddress( "vbf_maxpt_j2_pt_jes_dn", 	 &vbsEvent.vbf_maxpt_j2_pt_jes_dn );
	 vbsTree->SetBranchAddress( "vbf_maxpt_j2_pt_jes_up", 	 &vbsEvent.vbf_maxpt_j2_pt_jes_up );
	 vbsTree->SetBranchAddress( "vbf_maxpt_jj_Deta", 	 &vbsEvent.vbf_maxpt_jj_Deta );
	 vbsTree->SetBranchAddress( "vbf_maxpt_jj_Deta_jes_dn", 	 &vbsEvent.vbf_maxpt_jj_Deta_jes_dn );
	 vbsTree->SetBranchAddress( "vbf_maxpt_jj_Deta_jes_up", 	 &vbsEvent.vbf_maxpt_jj_Deta_jes_up );
	 vbsTree->SetBranchAddress( "vbf_maxpt_jj_eta", 	 &vbsEvent.vbf_maxpt_jj_eta );
	 vbsTree->SetBranchAddress( "vbf_maxpt_jj_m", 	 &vbsEvent.vbf_maxpt_jj_m );
	 vbsTree->SetBranchAddress( "vbf_maxpt_jj_m_jes_dn", 	 &vbsEvent.vbf_maxpt_jj_m_jes_dn );
	 vbsTree->SetBranchAddress( "vbf_maxpt_jj_m_jes_up", 	 &vbsEvent.vbf_maxpt_jj_m_jes_up );
	 vbsTree->SetBranchAddress( "vbf_maxpt_jj_phi", 	 &vbsEvent.vbf_maxpt_jj_phi );
	 vbsTree->SetBranchAddress( "vbf_maxpt_jj_pt", 	 &vbsEvent.vbf_maxpt_jj_pt );
	 vbsTree->SetBranchAddress( "vbf_maxpt_jj_pt_jes_dn", 	 &vbsEvent.vbf_maxpt_jj_pt_jes_dn );
	 vbsTree->SetBranchAddress( "vbf_maxpt_jj_pt_jes_up", 	 &vbsEvent.vbf_maxpt_jj_pt_jes_up );
	 vbsTree->SetBranchAddress( "wSampleWeight", 	 &vbsEvent.wSampleWeight );
 // }
}
//=======================================
#endif
