#!/bin/bash

# Runs second after dsw.sh.
#   Purpose:
#       - Creates a ROOT macro "write_list.cc" to read in one of the .root data files
#       - Creates a list of variables (branches) from that .root file
#       - The writes vbsReducedTree.hpp with all of those variable names
#       - Takes a list of variables (from the list generated) to use as discriminating variables
#       and spectators in the TMVA step
#       - Creates vbsActiveBranches.hpp from the list of what's a variable and what's a spectator

#   Usage:
#       ./write_vbsDL.sh "location/of/data" "variable_set" "year"

# --------------------------------------------------------- Start - Create the write_list C++ macro - Start -------------------------------------------------------------------

SNAME="$(uname -a | awk '{print $2}')"
if [ $2 == "old" ]; then
    Trees="otree"
else
    Trees="Events"
fi

if [[ "0$1" == "0" && "0$(echo $SNAME | grep Manjaro)" != "0" ]]; then
    if [[ "$3" == "2016" || "$3" == "2017" || "$3" == "2018" ]]; then
        rootFiles="/mnt/Storage/Research/ntuples/NEW/$3/haddedFiles/"
    else
        echo "Error setting file - check write_vbsDL"
    fi
elif [[ "0$1" == "0" && "0$(echo $SNAME | grep oplp)" != "0" ]]; then
    if [[ "$3" == "2016" || "$3" == "2017" || "$3" == "2018" ]]; then
        rootFiles="/mnt/Volume/ntuples/$3/haddedFiles/"
    else
        echo "Error setting file - check write_vbsDL"
    fi
else
    rootFiles="/mnt/$1/" # $1 = g/2016/haddedFiles on my flashdrive, or on my desktop e/Research/ntuples/NEW/2016/haddedFiles
fi

now=$(date)

macroFile="write_list.cc"
if [ -f $macroFile ]; then rm -f $macroFile; fi
touch $macroFile

echo "Creating $macroFile"
cat >> $macroFile << EOF
{
    #include <fstream>
    #include <vector>
    #include <string>
    #include "TFile.h"
    #include "TObjArray.h"
    #include "TTree.h"
    /////////////////////////////////////////////////////
    // Autogenerated by write_list_macro.sh
    // Purpose: Store all of the root file names in a vector and print
    // the branch names and types to a text file.
    // $now
    /////////////////////////////////////////////////////

    std::vector<std::string> ntuples = {
EOF

# This block reads the names off all the files in the folder and adds them to the ntuples vector in $macroFile
for file in "$rootFiles"/*; do 
    echo -e '\t''\t'$file | sed "s|$rootFiles||g" | sed 's/\//\"/g' | sed 's/$/\",/g' | cat >> $macroFile 
done

# This reads the branch names out of the first ntuple in the vector and writes the type and branch name to a text file
cat >> $macroFile << EOF
    };

    std::string location="$rootFiles"; // on my personal desktop
    //TFile *outfile = new TFile("var_list.txt", "RECREATE");
    std::ofstream ofs ("var_list.txt", std::ofstream::out);

    // Change the 1 in the loop to ntuples.size() if the ntuples have different sets of branches
    for (int i = 0; i<1; i++) {
        std::string infile = location+ntuples[i];
        TFile *input = new TFile(infile.c_str());
        TObjArray* brches = $Trees->GetListOfBranches();
        for (int iter = 0; iter <brches->GetEntries(); iter++) {
            ofs << brches->At(iter)->GetTitle() << '\t' << '\t' << brches->At(iter)->GetName() << ";" << std::endl;
        }
        input->Close();
    }
    
    ofs.close();
}
EOF

# --------------------------------------------------------- End - Create the write_list C++ macro - End -------------------------------------------------------------------

# Run the macro that was just generated
root -q .x write_list.cc
# sort the branches and remove any duplicates then store the result in a new file
sort -u var_list.txt > branches.txt
# Delete the old varible list file
rm var_list.txt
# Replace the I, F, and O type names with the full root type name (Int_t, Float_t, Bool_t) then store it in a new file
# This can give issues. Apparently some branches in the root files don't have types. Forced them to be floats
cat branches.txt | sed 's/[0-z]*\/I/Int_t/g' | sed 's/[0-z]*\/F/Float_t/g' | sed 's/[0-z]*\/O/Bool_t/g' | grep -v Float_t | grep -v Int_t | grep -v Bool_t | awk '{$1="Float_t"} {print}' > list_of_branches.txt
cat branches.txt | sed 's/[0-z]*\/I/Int_t/g' | grep Int_t  >> list_of_branches.txt
cat branches.txt | sed 's/[0-z]*\/F/Float_t/g' | grep Float_t >> list_of_branches.txt
#cat branches.txt | sed 's/[0-z]*\/O/Int_t/g' | grep Int_t >> list_of_branches.txt
cat branches.txt | sed 's/[0-z]*\/O/Bool_t/g' | grep Bool_t >> list_of_branches.txt
# Delete the old variable list file
#rm branches.txt

if [ $2 == "Boosted" ]; then
    # These are the variables for the new ntuples.
    TMVAVARS="vbf2_AK4_pt vbf1_AK4_pt zeppLep zeppHad nJet30f vbf_m lep1_eta lep1_pt vbf1_AK4_eta vbf2_AK4_eta dibos_pt dibos_m dibos_eta dilep_pt dilep_eta dilep_m bos_PuppiAK8_tau2tau1 vbf_deta vbf_eta bos_PuppiAK8_m_sd0_corr bos_PuppiAK8_pt bosCent vbf1_AK4_qgid vbf2_AK4_qgid MET MET_phi"
    activeVARS="gid sid run evt bosCent L1PFWeight nBtag_loose genWeight puWeight lep2_pt bos_PuppiAK8_eta lep1_m lep2_eta mcWeight btagWeight_loose bos_AK4AK4_eta $TMVAVARS"
    plotVARS="nPV MET lep1_pt lep1_eta lep1_iso lep1_phi lep1_q neu_pz_type0 MET_phi dibos_m dibos_eta dibos_mt dibos_phi dibos_pt zeppHad nJet30 nJet50"
    plotVARS_AK8jet="bos_PuppiAK8_pt bos_PuppiAK8_eta bos_PuppiAK8_phi bos_PuppiAK8_m_sd0 bos_PuppiAK8_m_sd0_corr"
    plotVARS_VBFJet="nBtag_loose nBtag_medium vbf1_AK4_eta vbf1_AK4_phi vbf1_AK4_pt vbf2_AK4_eta vbf2_AK4_phi vbf2_AK4_pt vbf_m vbf_deta vbf1_AK4_qgid vbf2_AK4_qgid vbf_phi"
    plotVARS_Lep="lep1_eta lep1_phi lep1_pt lep2_eta lep2_pt lep2_phi"
    plotVARS_Other="dilep_eta dilep_m dilep_mt dilep_phi dilep_pt bos_j1_AK4_eta bos_j1_AK4_pt bos_j2_AK4_eta bos_j2_AK4_pt bos_AK4AK4_m bos_AK4AK4_pt year lumin"
    SUanlVARS="$(echo $activeVARS $plotVARS ${plotVARS_AK8jet} ${plotVARS_VBFJet} ${plotVARS_Other} ${plot_VARS_Lep} | sort | tr -s '\ ' '\n' | sort | uniq )"
elif [ $2 == "Boosted2" ]; then
    TMVAVARS="bos_PuppiAK8_tau2tau1 vbf_m lep1_eta nJet30f vbf_deta vbf1_AK4_pt zeppLep vbf2_AK4_qgid vbf1_AK4_qgid vbf2_AK4_eta vbf1_AK4_eta vbf2_AK4_pt zeppHad vbf_eta bos_PuppiAK8_m_sd0_corr"
    activeVARS="gid sid run evt bosCent L1PFWeight nBtag_loose genWeight puWeight lep2_pt bos_PuppiAK8_eta lep1_m lep2_eta mcWeight btagWeight_loose bos_AK4AK4_eta AntiIsoInt $TMVAVARS" # isAntiIso should go here, but it's a bool and AddSpectator expects a Float_t or Int_t AntiIsoInt
    plotVARS="nPV MET lep1_pt lep1_eta lep1_iso lep1_phi lep1_q neu_pz_type0 MET_phi dibos_m dibos_eta dibos_mt dibos_phi dibos_pt zeppHad zeppLep nJet30 nJet50 nJet30f"
    plotVARS_AK8jet="bos_PuppiAK8_pt bos_PuppiAK8_eta bos_PuppiAK8_phi bos_PuppiAK8_m_sd0 bos_PuppiAK8_m_sd0_corr bos_PuppiAK8_tau2tau1"
    plotVARS_VBFJet="nBtag_loose nBtag_medium vbf1_AK4_eta vbf1_AK4_phi vbf1_AK4_pt vbf2_AK4_eta vbf2_AK4_phi vbf2_AK4_pt vbf_m vbf_deta vbf1_AK4_qgid vbf2_AK4_qgid vbf_phi vbf_pt vbf_eta"
    plotVARS_Lep="lep1_eta lep1_phi lep1_pt lep2_eta lep2_pt lep2_phi"
    plotVARS_Other="dilep_eta dilep_m dilep_mt dilep_phi dilep_pt bos_j1_AK4_eta bos_j1_AK4_pt bos_j2_AK4_eta bos_j2_AK4_pt bos_AK4AK4_m bos_AK4AK4_pt year lumin lep1_idEffWeight lep2_idEffWeight lep1_trigEffWeight lep2_trigEffWeight"
    #weightVARS=""#mcWeight genWeight L1PFWeight puWeight btagWeight_loose lep1_idEffWeight lep2_idEffWeight lep1_trigEffWeight lep2_trigEffWeight pdfWeight scaleWeight"
    SUanlVARS="$(echo $activeVARS $plotVARS ${plotVARS_AK8jet} ${plotVARS_VBFJet} ${plotVARS_Other} ${plotVARS_Lep} | sort | tr -s '\ ' '\n' | sort | uniq )"
elif [ $2 == "set2" ]; then
    TMVAVARS="lep1_eta lep1_pt nJet30f vbf1_AK4_pt vbf2_AK4_pt bos_j1_AK4_pt bos_j2_AK4_pt vbf_m bos_AK4AK4_m vbf_deta vbf_eta bos_AK4AK4_eta zeppHad zeppLep bosCent"
    activeVARS="gid sid run evt bosCent L1PFWeight nBtag_loose genWeight puWeight lep2_pt bos_PuppiAK8_eta lep1_m lep2_eta mcWeight btagWeight_loose bos_AK4AK4_eta $TMVAVARS" # isAntiIso should go here, but it's a bool and AddSpectator expects a Float_t or Int_t
    plotVARS="nPV MET lep1_pt lep1_eta lep1_iso lep1_phi lep1_q neu_pz_type0 MET_phi dibos_m dibos_eta dibos_mt dibos_phi dibos_pt zeppHad nJet30 nJet50"
    plotVARS_AK8jet="bos_PuppiAK8_pt bos_PuppiAK8_eta bos_PuppiAK8_phi bos_PuppiAK8_m_sd0 bos_PuppiAK8_m_sd0_corr bos_PuppiAK8_tau2tau1"
    plotVARS_VBFJet="nBtag_loose nBtag_medium vbf1_AK4_eta vbf1_AK4_phi vbf1_AK4_pt vbf2_AK4_eta vbf2_AK4_phi vbf2_AK4_pt vbf_m vbf_deta vbf1_AK4_qgid vbf2_AK4_qgid vbf_phi vbf_pt"
    plotVARS_Lep="lep1_eta lep1_phi lep1_pt lep2_eta lep2_pt lep2_phi"
    plotVARS_Other="dilep_eta dilep_m dilep_mt dilep_phi dilep_pt bos_j1_AK4_eta bos_j1_AK4_pt bos_j2_AK4_eta bos_j2_AK4_pt bos_AK4AK4_m bos_AK4AK4_pt year lumin"
    SUanlVARS="$(echo $activeVARS $plotVARS ${plotVARS_AK8jet} ${plotVARS_VBFJet} ${plotVARS_Other} ${plot_VARS_Lep} | sort | tr -s '\ ' '\n' | sort | uniq )"
elif [ $2 == "Resolved" ]; then 
    TMVAVARS="vbf2_AK4_pt vbf1_AK4_pt zeppLep vbf_m lep1_eta lep1_pt vbf_pt vbf2_AK4_eta dibos_pt bos_PuppiAK8_tau2tau1 vbf_deta bos_PuppiAK8_m_sd0 vbf1_AK4_axis2 bos_AK4AK4_m bos_AK4AK4_pt bos_AK4AK4_eta bos_AK4AK4_phi"
    activeVARS="gid sid run evt L1PFWeight nBtag_loose genWeight puWeight lep2_pt bos_PuppiAK8_eta lep1_m lep2_eta mcWeight btagWeight_loose LHEWeight lep1_idEffWeight lep1_trigEffWeight bos_AK4AK4_phi bos_AK4AK4_eta $TMVAVARS"
    plotVARS="nPV lep1_pt lep1_eta lep1_iso lep1_phi lep1_q neu_pz_type0 MET_phi dibos_m dibos_eta dibos_mt dibos_phi dibos_pt zeppHad"
    plotVARS_AK8jet="bos_PuppiAK8_pt bos_PuppiAK8_eta bos_PuppiAK8_phi bos_PuppiAK8_m_sd0 bos_PuppiAK8_m_sd0_corr"
    plotVARS_VBFJet="nBtag_loose nBtag_medium vbf1_AK4_eta vbf2_AK4_eta vbf2_AK4_pt vbf1_AK4_pt vbf_m vbf_deta"
    plotVARS_Other="dilep_eta dilep_m dilep_mt dilep_phi dilep_pt bos_AK4AK4_m bos_AK4AK4_phi bos_AK4AK4_pt bos_AK4AK4_eta year lumin"
    SUanlVARS="$(echo $activeVARS $plotVARS ${plotVARS_AK8jet} ${plotVARS_VBFJet} ${plotVARS_Other} | sort | tr -s '\ ' '\n' | sort | uniq )"
elif [ $2 == "set4" ]; then 
    TMVAVARS="vbf2_AK4_pt vbf1_AK4_pt zeppLep vbf_m lep1_eta lep1_pt vbf_pt vbf2_AK4_eta dibos_pt bos_PuppiAK8_tau2tau1 vbf_deta bos_PuppiAK8_m_sd0"
    activeVARS="gid sid run evt L1PFWeight nBtag_loose genWeight puWeight lep2_pt bos_PuppiAK8_eta lep1_m lep2_eta mcWeight btagWeight_loose $TMVAVARS"
    plotVARS="nPV MET lep1_pt lep1_eta lep1_iso lep1_phi lep1_q neu_pz_type0 MET_phi dibos_m dibos_eta dibos_mt dibos_phi dibos_pt"
    plotVARS_AK8jet="bos_PuppiAK8_pt bos_PuppiAK8_eta bos_PuppiAK8_phi bos_PuppiAK8_m_sd0"
    plotVARS_VBFJet="nBtag_loose nBtag_medium vbf1_AK4_eta vbf2_AK4_eta vbf2_AK4_pt vbf1_AK4_pt vbf_m vbf_deta"
    plotVARS_Other="dilep_eta dilep_m dilep_mt dilep_phi dilep_pt year lumin"
    SUanlVARS="$(echo $activeVARS $plotVARS ${plotVARS_AK8jet} ${plotVARS_VBFJet} ${plotVARS_Other} | sort | tr -s '\ ' '\n' | sort | uniq )"
elif [ $2 == "old" ]; then
    # These are the variables for the old ntuples
    TMVAVARS=" l_pt1  l_eta1 pfMET_Corr ungroomed_PuppiAK8_jet_pt PuppiAK8_jet_tau2tau1 PuppiAK8_jet_mass_so_corr vbf_maxpt_jj_m vbf_maxpt_j2_eta vbf_maxpt_j1_eta vbf_maxpt_j1_pt  vbf_maxpt_j2_pt mass_lvj_type0_PuppiAK8 BosonCentrality_type0 ZeppenfeldWL_type0 ZeppenfeldWH"
    activeVARS="gid sid mcWeight run event nTotEvents lumi  L1_Prefweight totalEventWeight type isVBF nBTagJet_loose btag0Wgt genWeight trig_eff_Weight id_eff_Weight pu_Weight l_pt2  ungroomed_PuppiAK8_jet_eta $TMVAVARS"
    plotVARS="nPV l_pt1 l_eta1 l_iso1 l_phi1 l_e1 l_charge1    pfMET_Corr pfMET_Corr_phi nu_pz_type0   mass_lvj_type0_PuppiAK8 mt_lvj_type0_PuppiAK8  v_pt_type0 v_mt_type0"
    plotVARS_AK8jet="nGoodPuppiAK8jets ungroomed_PuppiAK8_jet_pt  ungroomed_PuppiAK8_jet_pt ungroomed_PuppiAK8_jet_eta ungroomed_PuppiAK8_jet_phi ungroomed_PuppiAK8_jet_e ungroomed_PuppiAK8_jet_charge PuppiAK8_jet_mass PuppiAK8_jet_mass_pr PuppiAK8_jet_mass_so_corr PuppiAK8_jet_mass_tr PuppiAK8_jet_sj1_pt PuppiAK8_jet_sj1_eta PuppiAK8_jet_sj1_phi PuppiAK8_jet_sj1_m  PuppiAK8_jet_sj1_q PuppiAK8_jet_sj2_pt PuppiAK8_jet_sj2_eta PuppiAK8_jet_sj2_phi PuppiAK8_jet_sj2_m PuppiAK8_jet_sj2_q PuppiAK8jet_qjet PuppiAK8_jet_tau2tau1"
    plotVARS_VBFJet="njets nBTagJet_loose nBTagJet_medium vbf_maxpt_j1_eta vbf_maxpt_j2_eta vbf_maxpt_j2_pt vbf_maxpt_j1_pt vbf_maxpt_jj_m vbf_maxpt_jj_Deta"
    plotVARS_Other="deltaR_lPuppiak8jet deltaphi_METPuppiak8jet deltaphi_METvbfJ1 deltaphi_METvbfJ2 deltaphi_METmin deltaphi_VPuppiak8jet PtBalance_type0 BosonCentrality_type0  costheta1_type0 costheta2_type0 costhetastar_type0  phi_type0 phi1_type0  PtBalance_type2 costheta1_type2 costheta2_type2 costhetastar_type2 phi_type2 phi1_type2"
    SUanlVARS="$(echo $activeVARS $plotVARS ${plotVARS_AK8jet} ${plotVARS_VBFJet}  ${plotVARS_Other} | sort | tr -s '\ '  '\n'  | sort | uniq )"
else
    echo "Pick from the premade variable lists or make a new list"
    return 0;
fi
# Write SUanlVARS into an array
var_arr=(`echo ${SUanlVARS}`)

# --------------------------------------------------------- Start - Create the vbsReducedTree.hpp file - Start ----------------------------------------------------
outfile="vbsReducedTree.hpp"

if [ -f $outfile ]; then rm -f $outfile; fi
echo "Creating $outfile"

# cat boiler plate things
cat >> $outfile << EOF
#ifndef vbsReducedTree_hpp
#define vbsReducedTree_hpp
//////////////////////////////////////////////////////////
// This class has been automatically generated by write_vbsDL.sh on
// $now
// from TTree $Trees
// found on file: DYJetsToLL_M-50_HT-100to200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_01.root
//////////////////////////////////////////////////////////
//VbsReducedEvent structure (keeps variables of the VbsAnalysisReduced ntuple)
typedef struct {
//Additional branches - to be added
  Int_t           gid;                  // - group  ID
  Int_t           sid;                  // - sample ID
  Float_t         mcWeight;             //== xsect/ngen 
  Float_t         lumin;
  Int_t           year;
//  Int_t           AntiIsoInt;

   // Declaration of leaf types

EOF

# cat all of the names of branches previously automatically generated
cat list_of_branches.txt >> $outfile

cat >> $outfile << EOF
} VbsReducedEvent;

//===================================================================================
//
void addBranches_vbsReducedTree(TTree* vbsTree, VbsReducedEvent& vbsEvent){
  cout << "Adding branches" << endl;
  vbsTree->Branch( "gid",                &vbsEvent.gid,              "gid/I");
  vbsTree->Branch( "sid",                &vbsEvent.sid,              "sid/I");
  vbsTree->Branch( "mcWeight",           &vbsEvent.mcWeight,         "mcWeight/F");
  vbsTree->Branch( "lumin",              &vbsEvent.lumin,            "lumin/F");
  vbsTree->Branch( "year",               &vbsEvent.year,             "year/I");
//  vbsTree->Branch( "AntiIsoInt",        &vbsEvent.AntiIsoInt,      "AntiIsoInt/I");
}

//===================================================================================
// 
void arrange_vbsReducedTree(TTree* vbsTree, VbsReducedEvent& vbsEvent){
//Maps the vbsTree branches to members of local  vbsEvent structure
  cout << " Setting extra branches" << endl;
  vbsTree->SetBranchAddress( "gid",                                      &vbsEvent.gid    );
  vbsTree->SetBranchAddress( "sid",                                      &vbsEvent.sid    );
  vbsTree->SetBranchAddress( "mcWeight",                                 &vbsEvent.mcWeight );
  vbsTree->SetBranchAddress( "lumin",                                    &vbsEvent.lumin);
  vbsTree->SetBranchAddress( "year",                                     &vbsEvent.year);
//  vbsTree->SetBranchAddress( "AntiIsoInt",                              &vbsEvent.AntiIsoInt); 
  cout << " Done setting extra branches. Setting the rest." << endl;
//  vbsTree->SetBranchAddress( "isAntiIso",                                &vbsEvent.isAntiIso);
EOF

while read line; do
    two=$(echo $line | awk '{print $2}' | sed 's/;//g')
    if [[ "${var_arr[@]}" =~ "$two" ]]; then
        echo -e "\t vbsTree->SetBranchAddress( \"$two\", \t\t\t &vbsEvent.$two);" >> $outfile
    fi
done < list_of_branches.txt

cat >> $outfile << EOF
 // }
}
//=======================================
#endif
EOF

#rm list_of_branches.txt

# --------------------------------------------------------- End - Create vbsReducedTree.hpp file - End -------------------------------------------------------------

# --------------------------------------------------------- Start - Create vbsDL.hpp file - Start -----------------------------------------------------------------

outfile_DL="vbsDL.hpp"
ActiveBranchesOutfile="vbsActiveBranches.hpp"

if [ -f $outfile_DL ]; then rm -f $outfile_DL; fi
echo "Creating $outfile_DL"

cat >> $outfile_DL << EOF
#ifndef vbsDL_hpp
#define vbsDL_hpp
//
//Note::Autogenerated with writeDL.sh on $now
//Please check vbsDL*.hpp for available configurations.
//TMVA vars:
//$TMVAVARS
#include "TMVA/Factory.h"
#include "TMVA/DataLoader.h"
#include "TMVA/Tools.h"
#include "TMVA/Reader.h"
#include "TMVA/TMVAGui.h"
#include "vbsReducedTree.hpp"
//
void   setChainBranches (TChain* inpChain);
//
void setVbsDLorReaderVarsAndSpectators(TMVA::DataLoader* dataloader, TMVA::Reader* datareader, VbsReducedEvent& vbsEvent){

EOF

# List all variables from the vbsReducedTree.hpp file, pull the names out of the SetBranchAddress lines and remove the quote marks/comma
allVARS="$(cat vbsReducedTree.hpp | grep SetBranchAddress | awk '{print $2}' | sed 's/\"//g' | sed 's/,//g')"

# Loop over all variables in SUanlVARS
for var in $SUanlVARS; do
    is_var_array="$(cat vbsReducedTree.hpp | grep $var | grep '\['])"

    # Save the type of the variable (Int_t, Float_t, Bool_t)
    typevar="$(cat vbsReducedTree.hpp | grep -v SetBranchAddress | grep -v Branch | grep -v typedef | grep $var | awk '{print $1}' | sort | uniq | awk '{print $1}')"

    # Replace the Float_t and Int_t (and I guess Bool_t) with F and I
    nw="$(echo $typevar | wc -w)"
    if [ $nw != "1" ]; then echo $typevar $var; fi
    if [ "$typevar " == "Float_t " ]; then
        typevar="F"
    else
        typevar="I"
    fi

    # Determine if var is in TMVAVARS, if so set isVariable to 1
    isVariable="0"
    for tmvavar in $TMVAVARS; do
        if [ $var == $tmvavar ]; then
            isVariable="1";
            break;
        fi
    done

    # If var is in TMVAVARS then add it as a variable to the data loader in file vbsDL.hpp
    # If var is in TMVAVARS and is not an array at it as a variable to the data reader
    # Print var to the terminal
    if [ $isVariable == "1" ]; then
        isVariable="0";
        echo "//TMVA variable" >> $outfile_DL
        echo "if(dataloader) dataloader->AddVariable(\"$var\", \"$var\", \"\", '$typevar');" >> $outfile_DL 
        if [ "0$is_var_array" == "0" ]; then
            echo "if(datareader) datareader->AddVariable(\"$var\",    &vbsEvent.$var        );" >> $outfile_DL
        else
            echo "//if(datareader) datareader->AddVariable(\"$var\",    &vbsEvent.${var}[0]     );" >> $outfile_DL
        fi
        echo " " >> $outfile_DL
        echo "Variable::" $var

    # If var is not in TMVAVARS then add it as a spectator to the data loader and reader
    # Print var to the terminal
    else
        echo "//TMVA spectator " >> $outfile_DL
        echo "if(dataloader) dataloader->AddSpectator(\"$var\",    \"$var\",   \"\",      '$typevar');" >> $outfile_DL
        if [ "0$is_var_array" == "0" ]; then
            echo "if(datareader) datareader->AddSpectator(\"$var\",    &vbsEvent.$var        );" >> $outfile_DL
        else
            echo "//if(datareader) datareader->AddSpectator(\"$var\",    &vbsEvent.${var}[0]   );" >> $outfile_DL
        fi
        echo " " >> $outfile_DL
        echo "Spectator::" $var
    fi
done

cat >> $outfile_DL << EOF
}
//=======================================
//========================================
void setChainBranches (TChain* inpChain){
//
   inpChain->SetBranchStatus("*", 0);   // disable all branches
// switch on required  branches
EOF

# Loop over all analysis variables and set their branch status to enabled
for var in $SUanlVARS; do
    echo "inpChain->SetBranchStatus(\"$var\", 1);" >> $outfile_DL
done

cat >> $outfile_DL << EOF
}
//=============================
#endif
EOF
# --------------------------------------------------------- End - Create vbsDL.hpp file - End ----------------------------------------------------------------------

# --------------------------------------------------------- Start - Create vbsActiveBranches.hpp - Start ------------------------------------------------------------
echo "Creating $ActiveBranchesOutfile"

if [ -f $ActiveBranchesOutfile ]; then /bin/rm -f  ${ActiveBranchesOutfile}; fi
cat >> $ActiveBranchesOutfile <<EOF
#ifndef vbsActiveBranches_hpp
#define vbsActiveBranches_hpp
////////////////////////////////////////////////////////////////////////
// $Id: vbsActiveBranches.hpp
// 
// File:    vbsActiveBranches.hpp
// Purpose: set active Branches for VBS analysis interface to TMVA 
// (works with VBS4LeptonsAnalysisReduced trees)   
// Autogenerated using write_vbsDL.sh
////////////////////////////////////////////////////////////////////////
#include "TROOT.h"
#include "TChain.h"

void   setChainBranches (TChain* inpChain);
//========================================
void setChainBranches (TChain* inpChain){
//
   inpChain->SetBranchStatus("", kFALSE);   // disable all branches
// switch on required  branches
EOF

for var in $SUanlVARS; do
    echo "inpChain->SetBranchStatus(\"$var\", 1);" >>  $ActiveBranchesOutfile
done
cat >> $ActiveBranchesOutfile <<EOF
}
//=======================================
#endif
EOF

# --------------------------------------------------------- End - Create vbsActiveBranches.hpp - End ---------------------------------------------------------------

echo "Done!"
echo ""
echo "Next run root -b -q ./vbsTMVAClassification.cc\(\\\"vbs_ww\\\",\\\"BDT\\\"\)"
echo "Don't forget to change the selector variable to switch what samples are being used"

#	void main(){
#
#    // Change the 1 in the loop to ntuples.size() if the ntuples have different sets of branches
#    for (int i = 0; i<1; i++) {
#        std::string infile = location+ntuples[i];
#        TFile *input = new TFile(infile.c_str());
#				TTree* Events = input->Get<TTree>("Events");
#        TObjArray* brches = Events->GetListOfBranches();
#        for (int iter = 0; iter <brches->GetEntries(); iter++) {
#            ofs << brches->At(iter)->GetTitle() << '\t' << '\t' << brches->At(iter)->GetName() << ";" << std::endl;
#        }
#        input->Close();
#    }
#    
#    ofs.close();
#	}

# ----------------------------------------------------- Start - Material from old write_vbsDL.sh - Start ------------------------------------------------------------

# Purpose: to generate vbsDL.hpp file
# Usage ::  Edit *VARS* lists; ./write_vbsDL.sh  
#
#Variable description
#   plotvar	MINRange  MAXRange  NBINS  slog xlabel outfile AMINRange  AMAXRange ANBINS drawleg
#plotvar( anl, var,        cut,   scale=1.0, debug=0, istyle=0,   xmin,xmax, binwdth, flogy=0, flogx=0, hTitle[], xTitle[]="test", yTitle[]);

#------------   VERTICES  	-------------------

#plotvar(anl, "nPV", tmvasel+allCuts,  1.0, 1, 0,  0, 50, 1,       1, 0,  "VBS (WV), 35.9 fb^{-1}", "Number of primary vertices", "Events/bin")
#------------    LEPTONS  	-------------------

# { "l_pt1",		0, 390, 26, 3,		"Lepton p_{T} (GeV)",     "lepton_pt",       0,  390, 26, 1 },
# plotvar(anl, "l_pt1",  tmvasel+allCuts,  1.0, 1, 0,   0., 600., 10,      1, 0,  "VBS (WV), 35.9 fb^{-1}", "Lepton_1 p_{T} (GeV)", "Events/bin")
# plotvar(anl, "l_eta1", tmvasel+allCuts,  1.0, 1, 0,  -3.5,  6.5, .5,   1, 0,  "VBS (WV), 35.9 fb^{-1}", "Lepton_1 #eta", "Events/bin")
# plotvar(anl, "l_phi1", tmvasel+allCuts,  1.0, 1, 0,  0., 1.8*TMath::Pi(), 0.125*TMath::Pi(),   1, 0,  "VBS (WV), 35.9 fb^{-1}", "Lepton_1 #phi", "Events/bin")
# plotvar(anl, "l_charge1", tmvasel+allCuts,  1.0, 1, 0,  -2.5, 5.5, 1,     1, 0,  "VBS (WV), 35.9 fb^{-1}", "Lepton_1 charge", "Events/bin")
# plotvar(anl, "l_e1",    tmvasel+allCuts,  1.0, 1, 0,   0., 600., 10,       1, 0,  "VBS (WV), 35.9 fb^{-1}", "Lepton_1 energy", "Events/bin")
# plotvar(anl, "l_iso1",  tmvasel+allCuts,  1.0, 1, 0,   0., 0.5, 0.02,       1, 0,  "VBS (WV), 35.9 fb^{-1}", "Lepton_1 isolation", "Events/bin")

#
##-------------- 	MET	-------------------
# plotvar(anl, "pfMET_Corr",  tmvasel+allCuts,  1.0, 1, 0,   0., 600., 10,      1, 0,  "VBS (WV), 35.9 fb^{-1}", "pfMET_Corr (GeV)", "Events/bin")
# plotvar(anl, "pfMET_Corr_phi",  tmvasel+allCuts,  1.0, 1, 0,   0., 1.8*TMath::Pi(), 0.125*TMath::Pi(),      1, 0,  "VBS (WV), 35.9 fb^{-1}", "pfMET_Corr_phi", "Events/bin")
# plotvar(anl, "nu_pz_type0",  tmvasel+allCuts,  1.0, 1, 0,   -500., 500., 20,      1, 0,  "VBS (WV), 35.9 fb^{-1}", "Reconstructed Neutrino p_{Z}", "Events/bin")
#
##--------------	AK8 Jet		------------
# plotvar(anl, "nGoodPuppiAK8jets",  tmvasel+allCuts,  1.0, 1, 0,  0., 10., 1,      1, 0,  "VBS (WV), 35.9 fb^{-1}", "Number of Good AK8 jets", "Events/bin")
# plotvar(anl, "ungroomed_PuppiAK8_jet_pt",  tmvasel+allCuts,  1.0, 1, 0,   0., 1400., 20,      1, 0,  "VBS (WV), 35.9 fb^{-1}", "AK8 p_{T} (GeV)", "Events/bin")
# plotvar(anl, "ungroomed_PuppiAK8_jet_eta", tmvasel+allCuts,  1.0, 1, 0,  -3.5,  6.5, .5,   1, 0,  "VBS (WV), 35.9 fb^{-1}", "AK8 #eta", "Events/bin")
# plotvar(anl, "ungroomed_PuppiAK8_jet_phi", tmvasel+allCuts,  1.0, 1, 0,  0., 1.8*TMath::Pi(), 0.125*TMath::Pi(),   1, 0,  "VBS (WV), 35.9 fb^{-1}", "AK8 #phi", "Events/bin")
# plotvar(anl, "ungroomed_PuppiAK8_jet_charge", tmvasel+allCuts,  1.0, 1, 0,  -2.5, 5.5, 0.1,     1, 0,  "VBS (WV), 35.9 fb^{-1}", "AK8 charge", "Events/bin")
# plotvar(anl, "ungroomed_PuppiAK8_jet_e",    tmvasel+allCuts,  1.0, 1, 0,   0., 1400., 20,       1, 0,  "VBS (WV), 35.9 fb^{-1}", "AK8  energy", "Events/bin")
#
# plotvar(anl, "PuppiAK8_jet_mass",         tmvasel+allCuts,  1.0, 1, 0,  20., 220., 10,       1, 0,  "VBS (WV), 35.9 fb^{-1}",    "AK8 mass (GeV)",           "Events/bin")
# plotvar(anl, "PuppiAK8_jet_mass_pr",      tmvasel+allCuts,  1.0, 1, 0,  20., 220., 10,       1, 0,  "VBS (WV), 35.9 fb^{-1}",    "AK8 pruned mass (GeV)",    "Events/bin")
# plotvar(anl, "PuppiAK8_jet_mass_so_corr", tmvasel+allCuts,  1.0, 1, 0,  20., 220., 10,       1, 0,  "VBS (WV), 35.9 fb^{-1}",    "AK8 Softdrop mass (GeV)",  "Events/bin")
# plotvar(anl, "PuppiAK8_jet_mass_tr",      tmvasel+allCuts,  1.0, 1, 0,  20., 220., 10,       1, 0,  "VBS (WV), 35.9 fb^{-1}",    "AK8 tr mass (GeV)",        "Events/bin")
# plotvar(anl, "PuppiAK8_jet_tau2tau1",     tmvasel+allCuts,  1.0, 1, 0,  0., 1., 0.1,          1, 0,  "VBS (WV), 35.9 fb^{-1}",   "AK8 #tau_{2}/#tau_{1}",      "Events/bin")
# plotvar(anl, "PuppiAK8jet_qjet",          tmvasel+allCuts,  1.0, 1, 0,  0., 3., 0.1,          1, 0,  "VBS (WV), 35.9 fb^{-1}",   "PuppiAK8jet_qjet",      "Events/bin")

#####	Leptonic & Hadronic W-boson 
# plotvar(anl, "v_pt_type0",     tmvasel+allCuts,  1.0, 1, 0,  0., 1000., 20,          1, 0,  "VBS (WV), 35.9 fb^{-1}",   "W p_{T} (GeV)",      "Events/bin")
# plotvar(anl, "v_mt_type0",     tmvasel+allCuts,  1.0, 1, 0,  0., 500.,  20,     1, 0,  "VBS (WV), 35.9 fb^{-1}",   "W Transverse Mass (GeV)",      "Events/bin")

##--------------	VBF Jet		------------
# plotvar(anl, "njets",  tmvasel+allCuts,  1.0, 1, 0,  0., 10., 1,      1, 0,  "VBS (WV), 35.9 fb^{-1}", "Number of VBF jets", "Events/bin")
# plotvar(anl, "nBTagJet_loose",    tmvasel+allCuts,  1.0, 1, 0,  0., 10., 1,      1, 0,  "VBS (WV), 35.9 fb^{-1}", "Number of VBF jets (Loose b-tag)", "Events/bin")
# plotvar(anl, "nBTagJet_medium",   tmvasel+allCuts,  1.0, 1, 0,  0., 10., 1,      1, 0,  "VBS (WV), 35.9 fb^{-1}", "Number of VBF jets (Medium b-tag)", "Events/bin")
# plotvar(anl, "vbf_maxpt_j1_eta",  tmvasel+allCuts,  1.0, 1, 0,  -6,  10, .5,   1, 0,  "VBS (WV), 35.9 fb^{-1}", "Leading VBF Jet #eta", "Events/bin")
# plotvar(anl, "vbf_maxpt_j2_eta",  tmvasel+allCuts,  1.0, 1, 0,  -6,  10, .5,   1, 0,  "VBS (WV), 35.9 fb^{-1}", "Sub-Leading VBF Jet #eta", "Events/bin")
# plotvar(anl, "vbf_maxpt_j1_pt",   tmvasel+allCuts,  1.0, 1, 0,  20,  720, 20,   1, 0,  "VBS (WV), 35.9 fb^{-1}", "Leading VBF Jet  p_{T}", "Events/bin")
# plotvar(anl, "vbf_maxpt_j2_pt",   tmvasel+allCuts,  1.0, 1, 0,  20,  720, 20,    1, 0,  "VBS (WV), 35.9 fb^{-1}", "Sub-Leading VBF Jet p_{T}", "Events/bin")
# plotvar(anl, "vbf_maxpt_jj_m",    tmvasel+allCuts,  1.0, 1, 0,  200,  4200, 100,    1, 0,  "VBS (WV), 35.9 fb^{-1}", "VBF M_{jj} GeV", "Events/bin")
# plotvar(anl, "vbf_maxpt_jj_Deta", tmvasel+allCuts,  1.0, 1, 0,  0.0,  20.0, 0.5,    1, 0,  "VBS (WV), 35.9 fb^{-1}", "VBF #Delta #eta", "Events/bin")

#
##----------------	4 body mass	---------------
# plotvar(anl, "mass_lvj_type0_PuppiAK8",    tmvasel+allCuts,  1.0, 1, 0,  0.0,  2500., 50,    1, 0,  "VBS (WV), 35.9 fb^{-1}", "mass_lvj_type0_PuppiAK8_4bin ( M_{WW} ) (GeV)", "Events/bin")
# plotvar(anl, "mt_lvj_type0_PuppiAK8",      tmvasel+allCuts,  1.0, 1, 0,  0.0,  2500., 50,    1, 0,  "VBS (WV), 35.9 fb^{-1}", "mt_lvj_type0_PuppiAK8_4bin ( MT_{WW} )  (GeV)", "Events/bin")
#======================================================================================================================================================================
##--------------	AK8 Jet		------------

### { "PuppiAK8_jet_mass", 	40, 150, 11, 3, "AK8 mass (GeV)",		"AK8_mass",    40.0, 150, 11, 1},
### { "PuppiAK8_jet_mass_pr", 	40, 150, 11, 3, "AK8 pruned mass (GeV)",	"AK8_mass_pr", 40.0, 150, 11, 1},
# #{ "PuppiAK8_jet_mass_so_corr", 	65, 105, 13, 3, "AK8 Softdrop mass (GeV)",	"AK8_mass_so_LSB", 65, 105, 13, 1},
# { "PuppiAK8_jet_mass_so_corr", 	40, 150, 22, 3, "AK8 Softdrop mass (GeV)",	"AK8_mass_so_22bin", 40.0, 150, 22, 1},
# { "PuppiAK8_jet_mass_so_corr", 	40, 150, 11, 3, "AK8 Softdrop mass (GeV)",	"AK8_mass_so_11bin", 40.0, 150, 11, 1},
### { "PuppiAK8_jet_mass_tr", 	40, 150, 11, 3, "AK8 tr mass (GeV)", 		"AK8_mass_tr", 40.0, 150, 11, 1},
### { "PuppiAK8_jet_mass", 	65, 105, 5, 3, "AK8 mass (GeV)",		"AK8_mass",    65, 105, 5, 1},
### { "PuppiAK8_jet_mass_pr", 	65, 105, 5, 3, "AK8 pruned mass (GeV)",		"AK8_mass_pr", 65, 105, 5, 1},
### { "PuppiAK8_jet_mass_tr", 	65, 105, 5, 3, "AK8 tr mass (GeV)", 		"AK8_mass_tr", 65, 105, 5, 1},
## { "PuppiAK8_jet_sj1_pt",	0, 800, 25, 3, "AK8 SJ1 pT (GeV)",	"PuppiAK8_jet_sj1_pt", 0, 800, 25, 1},
## { "PuppiAK8_jet_sj1_eta",	-2.4, 2.4, 25, 1, "AK8 SJ1 #eta",	"PuppiAK8_jet_sj1_eta", -2.4, 2.4, 25, 1},
## { "PuppiAK8_jet_sj1_phi",	-3, 3, 25, 6, "AK8 SJ1 #phi",	"PuppiAK8_jet_sj1_phi", -3, 3, 25, 1},
## { "PuppiAK8_jet_sj1_m",	0, 90, 25, 3, "AK8 SJ1 mass (GeV)",	"PuppiAK8_jet_sj1_m", 0, 90, 25, 1},
## { "PuppiAK8_jet_sj1_q",	-1, 1, 25, 1, "AK8 SJ1 charge",	"PuppiAK8_jet_sj1_q", -1, 1, 25, 1},
## { "PuppiAK8_jet_sj2_pt",	0, 400, 25, 3, "AK8 SJ2 pT (GeV)",	"PuppiAK8_jet_sj2_pt", 0, 400, 25, 1},
## { "PuppiAK8_jet_sj2_eta",	-2.4, 2.4, 25, 1, "AK8 SJ2 #eta",	"PuppiAK8_jet_sj2_eta", -2.4, 2.4, 25, 1},
## { "PuppiAK8_jet_sj2_phi",	-3, 3, 25, 6, "AK8 SJ2 #phi",	"PuppiAK8_jet_sj2_phi", -3, 3, 25, 1},
## { "PuppiAK8_jet_sj2_m",	0, 150, 25, 3, "AK8 SJ2 mass (GeV)",	"PuppiAK8_jet_sj2_m", 0, 150, 25, 1},
## { "PuppiAK8_jet_sj2_q",	-1, 1, 25, 1, "AK8 SJ2 charge",	"PuppiAK8_jet_sj2_q", -1, 1, 25, 1},
## { "PuppiAK8_jet_sj1_q*PuppiAK8_jet_sj2_q",	-20, 20, 25, 1, "AK8 (SJ1_q #times SJ2_q)",	"PuppiAK8_SJ1J2_chargeMultiplication", -20, 20, 25, 1},
### { "PuppiAK8jet_qjet",		0, 2, 20, 1, "PuppiAK8jet_qjet", 	"PuppiAK8jet_qjet", 0, 2, 20, 1},
# { "PuppiAK8_jet_tau2tau1", 		0, 0.55, 10, 1, "AK8 #tau_{2}/#tau_{1}", 		"Puppi_AK8_jet_tau2tau1",0,0.55,10,0},
#
#
##--------------	VBF Jet		------------
# { "njets",  0, 10, 10, 1, "Number of VBF jets",	"njets", 0, 10, 10, 1},
# { "nBTagJet_loose", 0, 6, 6, 1, "number of VBF jets (Loose b-tag)", "nBTagJet_loose", 0, 6, 6, 1},
# { "nBTagJet_medium", 0, 6, 6, 1, "number of VBF jets (medium b-tag)", "nBTagJet_medium", 0, 6, 6, 1},
# { "vbf_maxpt_j1_eta", -5.0, 5.0, 20, 1,	"Leading VBF Jet #eta",	"vbf_maxpt_j1_eta", 	-5.0, 5.0, 20, 0},
# { "vbf_maxpt_j2_eta", -5.0, 5.0, 20, 1,	"Sub-Leading VBF Jet #eta", "vbf_maxpt_j2_eta", -5.0, 5.0, 20, 0},
# { "vbf_maxpt_j2_pt", 30,330, 12, 3,		"Sub-Leading VBF Jet p_{T}", "vbf_maxpt_j2_pt", 30,330,12,0 },
# { "vbf_maxpt_j1_pt", 30, 630, 24, 3,		"Leading VBF Jet p_{T}",	"vbf_maxpt_j1_pt", 30,630,24,1 },
# { "vbf_maxpt_jj_m", 	500, 2500, 20, 3,		"VBF M_{jj} GeV",	"vbf_maxpt_jj_m",  500, 2500, 20, 1},
# { "vbf_maxpt_jj_Deta",	0.0, 9, 18, 1,	"VBF #Delta #eta",	"vbf_maxpt_jj_Deta", 0.0,9, 18, 1 },
#
#
##----------------	4 body mass	---------------
#
# { "mass_lvj_type0_PuppiAK8", 	600, 2500, 4, 3, "M_{WW} (GeV)",		"mass_lvj_type0_PuppiAK8_4bin",    600, 2500, 4, 1},
# #{ "mt_lvj_type0_PuppiAK8", 	600, 2500, 4, 3, "MT_{WW} (GeV)",		"mt_lvj_type0_PuppiAK8_4bin",    600, 2500, 4, 1},
# #{ "mass_lvj_type0_PuppiAK8", 	600, 2500, 38, 3, "M_{WW} (GeV)",		"mass_lvj_type0_PuppiAK8_38bin",    600, 2500, 38, 1},
# #{ "mt_lvj_type0_PuppiAK8", 	600, 2500, 38, 3, "MT_{WW} (GeV)",		"mt_lvj_type0_PuppiAK8_38bin",    600, 2500, 38, 1},
# { "mass_lvj_type0_PuppiAK8", 	600, 2500, 19, 3, "M_{WW} (GeV)",		"mass_lvj_type0_PuppiAK8_19bin",    600, 2500, 19, 1},
# { "mt_lvj_type0_PuppiAK8", 	600, 2500, 19, 3, "MT_{WW} (GeV)",		"mt_lvj_type0_PuppiAK8_19bin",    600, 2500, 19, 1},
# { "mass_lvj_type0_PuppiAK8", 	600, 2500, 38, 3, "M_{WW} (GeV)",		"mass_lvj_type0_PuppiAK8_38bin",    600, 2500, 38, 1},
# { "mass_lvj_type0_PuppiAK8", 	0.0, 2500, 50, 3, "M_{WW} (GeV)",		"mass_lvj_type0_PuppiAK8_38bin",    0.0, 2500, 50, 1},
##
#####	Leptonic & Hadronic W-boson 
# { "v_pt_type0",		0, 800, 16, 3,	"W p_{T} (GeV)",		"v_pt", 	 0, 800, 16, 1 },
# { "v_mt_type0",		0, 400, 8, 3,	"W Transverse Mass (GeV)",	"v_mt", 	 0, 400, 8, 0 },
##
###----------	Other Variables	------------------------
##
# { "deltaR_lPuppiak8jet", 0, 7.0, 20, 1, "#Delta R(l,AK8 jet)", "deltaR_lPuppiak8jet", 0, 7.0, 20, 1},
# { "deltaphi_METPuppiak8jet", 0, 3.14, 15, 1, "#Delta #phi(pfMET,AK8 jet)", "deltaphi_METPuppiak8jet", 0, 3.14, 15, 1},
# { "deltaphi_METvbfJ1", 0, 3.14, 15, 1, "#Delta #phi(pfMET,jet1)", "deltaphi_METvbfJ1", 0, 3.14, 15, 1},
# { "deltaphi_METvbfJ2", 0, 3.14, 15, 1, "#Delta #phi(pfMET,jet2)", "deltaphi_METvbfJ2", 0, 3.14, 15, 1},
# { "deltaphi_METmin", 0, 3.14, 15, 1, "#Delta #phi(pfMET,jets)_{min}", "deltaphi_METmin", 0, 3.14, 15, 1},
# { "deltaphi_VPuppiak8jet",0, 3.14, 15, 1, "#Delta #phi(Leptonic W,AK8 jet)", "deltaphi_VPuppiak8jet", 0, 3.14, 15, 1},
# { "(ungroomed_PuppiAK8_jet_pt-l_pt1)/pfMET_Corr",	0, 10, 40, 1, "(AK8 p_{T} - Lepton p_{T})/pfMET",		"AK8minusLeptonptByMet",  0, 10, 40, 1 },
# { "vbf_maxpt_j2_pt/pfMET_Corr",	0, 5, 20, 1, "Sub-leading VBF p_{T}/pfMET",		"SubLeadingVBFptByMet",  0, 5, 20, 1 },
# { "vbf_maxpt_j1_pt/pfMET_Corr",	0, 15, 20, 1, "Leading VBF p_{T}/pfMET",		"LeadingVBFptByMet",  0, 15, 20, 1 },
# { "(vbf_maxpt_j1_pt+vbf_maxpt_j2_pt+ungroomed_PuppiAK8_jet_pt+l_pt1)/pfMET_Corr",	0, 30, 20, 1, "H_{T}/pfMET",		"HTByMET",  0, 30, 20, 1 },
#  { "BDT_response", -1.0,1.0,20,1, "BDT Response",  "BDT_response", -1.0, 1.0, 20, 1},
# { "PuppiAK8jet_e3_sdb1/(PuppiAK8jet_e2_sdb1*PuppiAK8jet_e2_sdb1*PuppiAK8jet_e2_sdb1)", 	0.05,3.5,25, 1, "D2",	"d2_ECF", 0.05,3.5,25, 1},
# { "PuppiAK8jet_e3_v2_sdb1/(PuppiAK8jet_e2_sdb1*PuppiAK8jet_e2_sdb1)", 	0.00,0.5,25, 1, "N2",	"n2_ECF", 0.00,0.5,25, 1},
# { "l_pt1+ungroomed_PuppiAK8_jet_pt+vbf_maxpt_j1_pt+vbf_maxpt_j2_pt",	0, 1500, 15, 3, "HT", "ht", 0, 1500, 15, 1},
#
#
# { "PtBalance_type0",		0, 1.0, 10, 1,	"p_{T} Balance",	"PtBalance_type0",	0, 1.0, 10, 1 },
# { "BosonCentrality_type0",	1, 4.0, 10, 1, 	"Boson Centrality",	"BosonCentrality_type0",1, 4.0, 10, 1 },
##
### Angular variables
## #{ "LeptonProjection_run2", 	0, 2, 10, 1, "LeptonProjection_run2"  , "LeptonProjection_run2" ,0, 2, 10, 1}, 
## #{ "LeptonProjection_type2", 	0, 2, 10, 1, "LeptonProjection_type2"  , "LeptonProjection_type2" ,0, 2, 10, 1}, 
## { "LeptonProjection_type0", 	0, 2, 10, 1, "Lepton Projection"  , "LeptonProjection_type0" ,0, 2, 10, 1}, 
## #{ "ZeppenfeldWL_run2", 	-5, 5, 10, 1, "ZeppenfeldWL_run2"  , "ZeppenfeldWL_run2" , -5, 5, 10, 0}, 
## #{ "ZeppenfeldWL_type2", 	-5, 5, 10, 1, "ZeppenfeldWL_type2"  , "ZeppenfeldWL_type2" , -5, 5, 10, 0}, 
## { "ZeppenfeldWL_type0", 	-4, 4, 10, 1, "Zeppenfeld (with leptonic W)"  , "ZeppenfeldWL_type0" , -4, 4, 10, 0}, 
## { "ZeppenfeldWH", 	-4, 4, 10, 1, 		"Zeppenfeld (with hadronic W)"  , "ZeppenfeldWH" , -4, 4, 10, 0}, 
# { "ZeppenfeldWL_type0/vbf_maxpt_jj_Deta", 	-0.3, 0.3, 10, 1, "ZeppenfeldWL/#Delta #eta jj"  , "ZeppenfeldWL_type0_new" , -0.3, 0.3, 10, 1},  
# { "ZeppenfeldWH/vbf_maxpt_jj_Deta", 	-0.3, 0.3, 10, 1, 		"ZeppenfeldWH/#Delta #eta jj"  , "ZeppenfeldWH_new" , -0.3, 0.3, 10, 1}, 
## #{ "RpT_run2", 		0, 80, 10, 1, 		"RpT_run2"  , "RpT_run2" ,	0, 80, 10, 1}, 
## #{ "RpT_type2", 	0, 80, 10, 1, 		"RpT_type2"  , "RpT_type2",	0, 80, 10, 1}, 
## { "RpT_type0", 	0, 80, 10, 1, 		"RpT"  , "RpT_type0",	0, 80, 10, 1}, 
## { "WWRapidity", 	-2.5, 2.5, 10, 1, 	"WW Rapidity"  , "TempWWRapidity" , -2.5, 2.5, 10, 0}, 
# #{ "VBSCentrality_run2", 	0, 3, 10, 1, 	"VBSCentrality_run2"  , "VBSCentrality_run2" , 0, 3, 10, 1}, 
# #{ "VBSCentrality_type2", 	0, 3, 10, 1, 	"VBSCentrality_type2"  , "VBSCentrality_type2" , 0, 3, 10, 1}, 
# { "VBSCentrality_type0", 	0, 3, 10, 1, 	"VBSCentrality"  , "VBSCentrality_type0" , 0, 3, 10, 1}, 
# #{ "costhetastar_run2", 	-1,1, 10, 1, 	"costhetastar_run2"  , "costhetastar_run2" ,-1,1, 10, 1}, 
# #{ "costhetastar_type2", 	-1,1, 10, 1, 	"costhetastar_type2"  , "costhetastar_type2" ,-1,1, 10, 1}, 
# { "costhetastar_type0", 	-1,1, 10, 6, 	"costhetastar"  , "costhetastar_type0" ,-1,1, 10, 1}, 
# #{ "costheta1_run2", 	-1,1, 10, 1, 	"costheta1_run2"  , "costheta1_run2" ,-1,1, 10, 0}, 
# #{ "costheta1_type2", 	-1,1, 10, 1, 	"costheta1_type2"  , "costheta1_type2" ,-1,1, 10, 0}, 
# { "costheta1_type0", 	-1,1, 10, 6, 	"costheta1"  , "costheta1_type0" ,-1,1, 10, 0}, 
# #{ "costheta2_run2", 	-1,1, 10, 6, 	"costheta2_run2"  , "costheta2_run2" ,-1,1, 10, 0}, 
# #{ "costheta2_type2", 	-1,1, 10, 6, 	"costheta2_type2"  , "costheta2_type2" ,-1,1, 10, 0}, 
# { "costheta2_type0", 	-1,1, 10, 6, 	"costheta2"  , "costheta2_type0" ,-1,1, 10, 0}, 
# #{ "phi_run2", 	-3.5, 3.5, 20, 6, 	"phi_run2"  ,  "phi_run2" ,  -3.5, 3.5, 20, 0}, 
# #{ "phi_type2", 	-3.5, 3.5, 20, 6,	"phi_type2"  , "phi_type2" , -3.5, 3.5, 20, 0}, 
# { "phi_type0", 	-3.5, 3.5, 20, 6, 	"phi"  , "phi_type0" , -3.5, 3.5, 20, 0}, 
# #{ "phi1_run2", 	-3.5, 3.5, 20, 6, 	"phi1_run2"  ,  "phi1_run2" ,  -3.5, 3.5, 20, 0}, 
# #{ "phi1_type2", 	-3.5, 3.5, 20, 6,	"phi1_type2"  , "phi1_type2" , -3.5, 3.5, 20, 0}, 
# { "phi1_type0", 	-3.5, 3.5, 20, 6, 	"phi1"  , "phi1_type0" , -3.5, 3.5, 20, 0}, 
# { "ungroomed_PuppiAK8_jet_pt/pfMET_Corr",	0, 15, 15, 3, "AK8 p_{T}/pfMET",		"AK8ptByMet",  0, 15, 15, 1 },
# { "l_pt1/pfMET_Corr",	0, 10, 20, 1, "Lepton p_{T}/pfMET",		"LeptonptByMet",  0, 10, 20, 1 },
# { "pfMET_Corr/(sqrt(vbf_maxpt_j1_pt+vbf_maxpt_j2_pt+ungroomed_PuppiAK8_jet_pt+l_pt1))",		0, 24, 12, 3,		"s = E_{T}^{miss}/#sqrt{#sum E_{T}}",     "s_dist",       0,  24, 12, 1 },

# ------------------------------------------------------------- End - Material from old write_vbsDL.sh - End ------------------------------------------------------------------