{
    #include <fstream>
    #include <vector>
    #include <string>

    /////////////////////////////////////////////////////
    // Autogenerated by write_list_macro.sh
    // Purpose: Store all of the root file names in a vector and print
    // the branch names and types to a text file.
    // Thu Jan 28 15:29:49 CST 2021
    /////////////////////////////////////////////////////

    std::vector<std::string> ntuples = {
		"DYJetsToLL_M-50_HT-100to200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_01.root",
		"TTToHadronic_TuneCP5_PSweights_13TeV-powheg-pythia8_01.root",
		"WJetsToLNu_HT-100To200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_01.root",
		"WplusToLNuWminusTo2JJJ_EWK_LO_SM_MJJ100PTJ10_TuneCUETP8M1_13TeV-madgraph-pythia8_01.root",
		"ZTo2LZTo2JJJ_EWK_LO_aQGC_MJJ100PTJ10_TuneCUETP8M1_13TeV-madgraph-pythia8_01.root",
    };

    // string location="~/documents/ntuples/"; // on my personal laptop
    string location="/mnt/e/Research/ntuples/NEW/ntuples/"; // on my personal desktop
    //TFile *outfile = new TFile("var_list.txt", "RECREATE");
    std::ofstream ofs ("var_list.txt", std::ofstream::out);

    // Change the 1 in the loop to ntuples.size() if the ntuples have different sets of branches
    for (int i = 0; i<1; i++) {
        string infile = location+ntuples[i];
        TFile *input = new TFile(infile.c_str());
        TObjArray* brches = Events->GetListOfBranches();
        for (int iter = 0; iter <brches->GetEntries(); iter++) {
            ofs << brches->At(iter)->GetTitle() << '\t' << '\t' << brches->At(iter)->GetName() << ";" << std::endl;
        }
        input->Close();
    }
    
    ofs.close();

}
