{
    #include <fstream>
    #include <vector>
    #include <string>

    /////////////////////////////////////////////////////
    // Autogenerated by write_list_macro.sh
    // Purpose: Store all of the root file names in a vector and print
    // the branch names and types to a text file.
    // Wed Feb  3 16:54:41 CST 2021
    /////////////////////////////////////////////////////

    std::vector<std::string> ntuples = {
		"DY1JetsToLL.root",
		"DY2JetsToLL.root",
		"DY3JetsToLL.root",
		"DY4JetsToLL.root",
		"Data.root",
		"DibosonBoostedElMuSamples13TeV_2019_03_23_03h56.txt",
		"DoublyChargedHiggsGMmodel_HWW_WWToLNuQQ_M1000_13TeV.root",
		"DoublyChargedHiggsGMmodel_HWW_WWToLNuQQ_M1500_13TeV.root",
		"DoublyChargedHiggsGMmodel_HWW_WWToLNuQQ_M2000_13TeV.root",
		"DoublyChargedHiggsGMmodel_HWW_WWToLNuQQ_M200_13TeV.root",
		"DoublyChargedHiggsGMmodel_HWW_WWToLNuQQ_M300_13TeV.root",
		"DoublyChargedHiggsGMmodel_HWW_WWToLNuQQ_M400_13TeV.root",
		"DoublyChargedHiggsGMmodel_HWW_WWToLNuQQ_M500_13TeV.root",
		"DoublyChargedHiggsGMmodel_HWW_WWToLNuQQ_M600_13TeV.root",
		"DoublyChargedHiggsGMmodel_HWW_WWToLNuQQ_M700_13TeV.root",
		"DoublyChargedHiggsGMmodel_HWW_WWToLNuQQ_M800_13TeV.root",
		"DoublyChargedHiggsGMmodel_HWW_WWToLNuQQ_M900_13TeV.root",
		"ST_s_channel.root",
		"ST_tW_antitop_5f_NoFullyHadronicDecays.root",
		"ST_tW_top_5f_NoFullyHadronicDecays.root",
		"ST_t_channel_antitop.root",
		"ST_t_channel_top_4f.root",
		"SingleElectron.root",
		"SingleMuon.root",
		"TTToSemilepton.root",
		"TTWJetsToLNu.root",
		"TTWJetsToQQ.root",
		"TTZToLLNuNu_M-10.root",
		"TTZToQQ.root",
		"WJetsToLNu_HT_100To200.root",
		"WJetsToLNu_HT_1200To2500.root",
		"WJetsToLNu_HT_200To400.root",
		"WJetsToLNu_HT_2500ToInf.root",
		"WJetsToLNu_HT_400To600.root",
		"WJetsToLNu_HT_600To800.root",
		"WJetsToLNu_HT_800To1200.root",
		"WWTo1L1Nu2Q_13TeV.root",
		"WWTree_ChargedHiggsToWZToLLQQ_M1000_13TeV.root",
		"WWTree_ChargedHiggsToWZToLLQQ_M1500_13TeV.root",
		"WWTree_ChargedHiggsToWZToLLQQ_M200_13TeV.root",
		"WWTree_ChargedHiggsToWZToLLQQ_M300_13TeV.root",
		"WWTree_ChargedHiggsToWZToLLQQ_M400_13TeV.root",
		"WWTree_ChargedHiggsToWZToLLQQ_M500_13TeV.root",
		"WWTree_ChargedHiggsToWZToLLQQ_M600_13TeV.root",
		"WWTree_ChargedHiggsToWZToLLQQ_M700_13TeV.root",
		"WWTree_ChargedHiggsToWZToLLQQ_M800_13TeV.root",
		"WWTree_ChargedHiggsToWZToLLQQ_M900_13TeV.root",
		"WWTree_ChargedHiggsToWZToLNuQQ_M1000_13TeV.root",
		"WWTree_ChargedHiggsToWZToLNuQQ_M1500_13TeV.root",
		"WWTree_ChargedHiggsToWZToLNuQQ_M2000_13TeV.root",
		"WWTree_ChargedHiggsToWZToLNuQQ_M200_13TeV.root",
		"WWTree_ChargedHiggsToWZToLNuQQ_M300_13TeV.root",
		"WWTree_ChargedHiggsToWZToLNuQQ_M400_13TeV.root",
		"WWTree_ChargedHiggsToWZToLNuQQ_M500_13TeV.root",
		"WWTree_ChargedHiggsToWZToLNuQQ_M600_13TeV.root",
		"WWTree_ChargedHiggsToWZToLNuQQ_M700_13TeV.root",
		"WWTree_ChargedHiggsToWZToLNuQQ_M800_13TeV.root",
		"WWTree_ChargedHiggsToWZToLNuQQ_M900_13TeV.root",
		"WWZ_13TeV_amcatnlo.root",
		"WZTo1L1Nu2Q_13TeV.root",
		"WminusTo2JZTo2LJJ_EWK_LO_SM.root",
		"WminusTo2JZTo2LJJ_EWK_LO_aQGC.root",
		"WminusTo2JZTo2LJJ_QCD_LO_SM.root",
		"WminusToLNuWminusTo2JJJ_EWK_LO_SM.root",
		"WminusToLNuWminusTo2JJJ_EWK_LO_aQGC.root",
		"WminusToLNuWminusTo2JJJ_QCD_LO_SM.root",
		"WminusToLNuZTo2JJJ_EWK_LO_SM.root",
		"WminusToLNuZTo2JJJ_EWK_LO_aQGC.root",
		"WminusToLNuZTo2JJJ_QCD_LO_SM.root",
		"WplusTo2JWminusToLNuJJ_EWK_LO_SM.root",
		"WplusTo2JWminusToLNuJJ_EWK_LO_aQGC.root",
		"WplusTo2JWminusToLNuJJ_QCD_LO_SM.root",
		"WplusTo2JZTo2LJJ_EWK_LO_SM.root",
		"WplusTo2JZTo2LJJ_EWK_LO_aQGC.root",
		"WplusTo2JZTo2LJJ_QCD_LO_SM.root",
		"WplusToLNuWminusTo2JJJ_EWK_LO_SM.root",
		"WplusToLNuWminusTo2JJJ_EWK_LO_aQGC.root",
		"WplusToLNuWminusTo2JJJ_QCD_LO_SM.root",
		"WplusToLNuWplusTo2JJJ_EWK_LO_SM.root",
		"WplusToLNuWplusTo2JJJ_EWK_LO_aQGC.root",
		"WplusToLNuWplusTo2JJJ_QCD_LO_SM.root",
		"WplusToLNuZTo2JJJ_EWK_LO_SM.root",
		"WplusToLNuZTo2JJJ_EWK_LO_aQGC.root",
		"WplusToLNuZTo2JJJ_QCD_LO_SM.root",
		"ZTo2LZTo2JJJ_EWK_LO_SM.root",
		"ZTo2LZTo2JJJ_EWK_LO_aQGC.root",
		"ZTo2LZTo2JJJ_QCD_LO_SM.root",
		"ZZTo2L2Q_13TeV.root",
		"ZZZ_13TeV_amcatnlo.root",
		"ZZ_13TeV_pythia8.root",
    };

    // string location="~/documents/ntuples/"; // on my personal laptop
    string location="/mnt/e/Research/ntuples/vbs_ww_old/"; // on my personal desktop
    //TFile *outfile = new TFile("var_list.txt", "RECREATE");
    std::ofstream ofs ("var_list.txt", std::ofstream::out);

    // Change the 1 in the loop to ntuples.size() if the ntuples have different sets of branches
    for (int i = 0; i<1; i++) {
        string infile = location+ntuples[i];
        TFile *input = new TFile(infile.c_str());
        TObjArray* brches = otree->GetListOfBranches();
        for (int iter = 0; iter <brches->GetEntries(); iter++) {
            ofs << brches->At(iter)->GetTitle() << '\t' << '\t' << brches->At(iter)->GetName() << ";" << std::endl;
        }
        input->Close();
    }
    
    ofs.close();

}
