// Class: ReadDNN_GPU
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : DL::DNN_GPU
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.24/02       [399362]
Creator        : markm
Date           : Mon Nov 15 19:01:45 2021
Host           : Linux Manjaro-Desktop 5.10.52-1-MANJARO #1 SMP PREEMPT Tue Jul 20 20:32:02 UTC 2021 x86_64 GNU/Linux
Dir            : /home/markm/Documents/research/vbsTMVA
Training events: 3115
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "True" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
Layout: "TANH|100,TANH|50,TANH|10,LINEAR" [Layout of the network.]
ErrorStrategy: "CROSSENTROPY" [Loss function: Mean squared error (regression) or cross entropy (binary classification).]
WeightInitialization: "XAVIERUNIFORM" [Weight initialization strategy]
Architecture: "GPU" [Which architecture to perform the training on.]
TrainingStrategy: "LearningRate=1e-1,Momentum=0.0,Repetitions=1,ConvergenceSteps=300,BatchSize=256,TestRepetitions=15,WeightDecay=0.001,Regularization=NONE,DropConfig=0.0+0.5+0.5+0.5,DropRepetitions=1,Multithreading=True|LearningRate=1e-2,Momentum=0.5,Repetitions=1,ConvergenceSteps=300,BatchSize=256,TestRepetitions=7,WeightDecay=0.001,Regularization=L2,Multithreading=True,DropConfig=0.0+0.1+0.1+0.1,DropRepetitions=1|LearningRate=1e-2,Momentum=0.3,Repetitions=1,ConvergenceSteps=300,BatchSize=256,TestRepetitions=7,WeightDecay=0.0001,Regularization=L2,Multithreading=True|LearningRate=1e-2,Momentum=0.1,Repetitions=1,ConvergenceSteps=300,BatchSize=256,TestRepetitions=7,WeightDecay=0.0001,Regularization=NONE,Multithreading=True" [Defines the training strategies.]
# Default:
VerbosityLevel: "Verbose" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
InputLayout: "0|0|0" [The Layout of the input]
BatchLayout: "0|0|0" [The Layout of the batch]
RandomSeed: "0" [Random seed used for weight initialization and batch shuffling]
ValidationSize: "20%" [Part of the training data to use for validation. Specify as 0.2 or 20% to use a fifth of the data set as validation set. Specify as 100 to use exactly 100 events. (Default: 20%)]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 15
bos_PuppiAK8_m_sd0_corr       bos_PuppiAK8_m_sd0_corr       bos_PuppiAK8_m_sd0_corr       bos_PuppiAK8_m_sd0_corr                                         'F'    [65.0625,104.9375]
bos_PuppiAK8_tau2tau1         bos_PuppiAK8_tau2tau1         bos_PuppiAK8_tau2tau1         bos_PuppiAK8_tau2tau1                                           'F'    [0.0703273266554,0.549935996532]
lep1_eta                      lep1_eta                      lep1_eta                      lep1_eta                                                        'F'    [-2.498046875,2.49951171875]
nJet30f                       nJet30f                       nJet30f                       nJet30f                                                         'F'    [2,8]
vbf1_AK4_eta                  vbf1_AK4_eta                  vbf1_AK4_eta                  vbf1_AK4_eta                                                    'F'    [-4.5439453125,4.6123046875]
vbf1_AK4_pt                   vbf1_AK4_pt                   vbf1_AK4_pt                   vbf1_AK4_pt                                                     'F'    [50.2703475952,1335.79541016]
vbf1_AK4_qgid                 vbf1_AK4_qgid                 vbf1_AK4_qgid                 vbf1_AK4_qgid                                                   'F'    [-1,0.99951171875]
vbf2_AK4_eta                  vbf2_AK4_eta                  vbf2_AK4_eta                  vbf2_AK4_eta                                                    'F'    [-4.830078125,4.83203125]
vbf2_AK4_pt                   vbf2_AK4_pt                   vbf2_AK4_pt                   vbf2_AK4_pt                                                     'F'    [50.0074539185,656.952087402]
vbf2_AK4_qgid                 vbf2_AK4_qgid                 vbf2_AK4_qgid                 vbf2_AK4_qgid                                                   'F'    [-1,0.99951171875]
vbf_deta                      vbf_deta                      vbf_deta                      vbf_deta                                                        'F'    [2.50122070312,8.2470703125]
vbf_eta                       vbf_eta                       vbf_eta                       vbf_eta                                                         'F'    [-5.84900569916,6.13960266113]
vbf_m                         vbf_m                         vbf_m                         vbf_m                                                           'F'    [500.211364746,7465.87548828]
zeppHad                       zeppHad                       zeppHad                       zeppHad                                                         'F'    [-3.68803405762,4.19094085693]
zeppLep                       zeppLep                       zeppLep                       zeppLep                                                         'F'    [-4.53291130066,5.84013319016]
NSpec 50
bos_AK4AK4_eta                bos_AK4AK4_eta                bos_AK4AK4_eta                bos_AK4AK4_eta                                                  'F'    [-999,-999]
bos_AK4AK4_m                  bos_AK4AK4_m                  bos_AK4AK4_m                  bos_AK4AK4_m                                                    'F'    [-999,-999]
bos_AK4AK4_pt                 bos_AK4AK4_pt                 bos_AK4AK4_pt                 bos_AK4AK4_pt                                                   'F'    [-999,-999]
bosCent                       bosCent                       bosCent                       bosCent                                                         'F'    [-4.273665905,3.50659179688]
bos_j1_AK4_eta                bos_j1_AK4_eta                bos_j1_AK4_eta                bos_j1_AK4_eta                                                  'F'    [-999,-999]
bos_j1_AK4_pt                 bos_j1_AK4_pt                 bos_j1_AK4_pt                 bos_j1_AK4_pt                                                   'F'    [-999,-999]
bos_j2_AK4_eta                bos_j2_AK4_eta                bos_j2_AK4_eta                bos_j2_AK4_eta                                                  'F'    [-999,-999]
bos_j2_AK4_pt                 bos_j2_AK4_pt                 bos_j2_AK4_pt                 bos_j2_AK4_pt                                                   'F'    [-999,-999]
bos_PuppiAK8_eta              bos_PuppiAK8_eta              bos_PuppiAK8_eta              bos_PuppiAK8_eta                                                'F'    [-2.38427734375,2.3916015625]
bos_PuppiAK8_m_sd0            bos_PuppiAK8_m_sd0            bos_PuppiAK8_m_sd0            bos_PuppiAK8_m_sd0                                              'F'    [65.0625,104.9375]
bos_PuppiAK8_phi              bos_PuppiAK8_phi              bos_PuppiAK8_phi              bos_PuppiAK8_phi                                                'F'    [-3.14111328125,3.14111328125]
bos_PuppiAK8_pt               bos_PuppiAK8_pt               bos_PuppiAK8_pt               bos_PuppiAK8_pt                                                 'F'    [200.125,1318]
btagWeight_loose              btagWeight_loose              btagWeight_loose              btagWeight_loose                                                'F'    [0.814955830574,1.25747036934]
dibos_eta                     dibos_eta                     dibos_eta                     dibos_eta                                                       'F'    [-5.23238372803,5.64812707901]
dibos_m                       dibos_m                       dibos_m                       dibos_m                                                         'F'    [146.410430908,3918.45141602]
dibos_mt                      dibos_mt                      dibos_mt                      dibos_mt                                                        'F'    [307.985168457,3931.45605469]
dibos_phi                     dibos_phi                     dibos_phi                     dibos_phi                                                       'F'    [-3.13946557045,3.13840818405]
dibos_pt                      dibos_pt                      dibos_pt                      dibos_pt                                                        'F'    [6.70540380478,1139.82141113]
dilep_eta                     dilep_eta                     dilep_eta                     dilep_eta                                                       'F'    [-3.8847014904,4.78794813156]
dilep_m                       dilep_m                       dilep_m                       dilep_m                                                         'F'    [3.83930301666,727.030761719]
dilep_mt                      dilep_mt                      dilep_mt                      dilep_mt                                                        'F'    [60.4044761658,1197.99279785]
dilep_phi                     dilep_phi                     dilep_phi                     dilep_phi                                                       'F'    [-3.13781285286,3.14104056358]
dilep_pt                      dilep_pt                      dilep_pt                      dilep_pt                                                        'F'    [3.94462060928,1094.41308594]
evt                           evt                           evt                           evt                                                             'F'    [-2139706624,2145447680]
genWeight                     genWeight                     genWeight                     genWeight                                                       'F'    [1,1]
gid                           gid                           gid                           gid                                                             'F'    [1,3]
L1PFWeight                    L1PFWeight                    L1PFWeight                    L1PFWeight                                                      'F'    [0.252985924482,1]
lep1_iso                      lep1_iso                      lep1_iso                      lep1_iso                                                        'F'    [0,0.125540167093]
lep1_m                        lep1_m                        lep1_m                        lep1_m                                                          'F'    [0.000510999991093,0.000510999991093]
lep1_phi                      lep1_phi                      lep1_phi                      lep1_phi                                                        'F'    [-3.1376953125,3.13818359375]
lep1_pt                       lep1_pt                       lep1_pt                       lep1_pt                                                         'F'    [25.3310718536,864.241516113]
lep1_q                        lep1_q                        lep1_q                        lep1_q                                                          'F'    [-1,1]
lep2_eta                      lep2_eta                      lep2_eta                      lep2_eta                                                        'F'    [-999,-999]
lep2_pt                       lep2_pt                       lep2_pt                       lep2_pt                                                         'F'    [-999,-999]
mcWeight                      mcWeight                      mcWeight                      mcWeight                                                        'F'    [1.49100003455e-07,1]
MET                           MET                           MET                           MET                                                             'F'    [30.0104789734,760.374084473]
MET_phi                       MET_phi                       MET_phi                       MET_phi                                                         'F'    [-3.1377055645,3.14145612717]
nBtag_loose                   nBtag_loose                   nBtag_loose                   nBtag_loose                                                     'F'    [0,0]
nBtag_medium                  nBtag_medium                  nBtag_medium                  nBtag_medium                                                    'F'    [0,0]
neu_pz_type0                  neu_pz_type0                  neu_pz_type0                  neu_pz_type0                                                    'F'    [-999,-999]
nJet30                        nJet30                        nJet30                        nJet30                                                          'F'    [2,8]
nJet50                        nJet50                        nJet50                        nJet50                                                          'F'    [2,8]
nPV                           nPV                           nPV                           nPV                                                             'F'    [2,50]
puWeight                      puWeight                      puWeight                      puWeight                                                        'F'    [0,1.20750808716]
run                           run                           run                           run                                                             'F'    [1,284043]
sid                           sid                           sid                           sid                                                             'F'    [3,108]
vbf1_AK4_phi                  vbf1_AK4_phi                  vbf1_AK4_phi                  vbf1_AK4_phi                                                    'F'    [-3.14013671875,3.14013671875]
vbf2_AK4_phi                  vbf2_AK4_phi                  vbf2_AK4_phi                  vbf2_AK4_phi                                                    'F'    [-3.14111328125,3.14111328125]
vbf_phi                       vbf_phi                       vbf_phi                       vbf_phi                                                         'F'    [-3.14140558243,3.13814020157]
vbf_pt                        vbf_pt                        vbf_pt                        vbf_pt                                                          'F'    [4.79439496994,1280.16259766]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadDNN_GPU : public IClassifierReader {

 public:

   // constructor
   ReadDNN_GPU( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadDNN_GPU" ),
        fNvars( 15 )
   {
      // the training input variables
      const char* inputVars[] = { "bos_PuppiAK8_m_sd0_corr", "bos_PuppiAK8_tau2tau1", "lep1_eta", "nJet30f", "vbf1_AK4_eta", "vbf1_AK4_pt", "vbf1_AK4_qgid", "vbf2_AK4_eta", "vbf2_AK4_pt", "vbf2_AK4_qgid", "vbf_deta", "vbf_eta", "vbf_m", "zeppHad", "zeppLep" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 0.99999988079071;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 0.99999988079071;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 0.99999988079071;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;
      fVmin[11] = -1;
      fVmax[11] = 1;
      fVmin[12] = -1;
      fVmax[12] = 1;
      fVmin[13] = -1;
      fVmax[13] = 0.99999988079071;
      fVmin[14] = -1;
      fVmax[14] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadDNN_GPU() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fOff_1[3][15];
   double fScal_1[3][15];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[15];
   double fVmax[15];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[15];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
inline double ReadDNN_GPU::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         std::vector<double> iV(inputValues);
         Transform( iV, -1 );
         retval = GetMvaValue__( iV );
   }

   return retval;
}

//_______________________________________________________________________
inline void ReadDNN_GPU::InitTransform_1()
{
   double fMin_1[3][15];
   double fMax_1[3][15];
   // Normalization transformation, initialisation
   fMin_1[0][0] = 65.125;
   fMax_1[0][0] = 104.9375;
   fScal_1[0][0] = 2.0/(fMax_1[0][0]-fMin_1[0][0]);
   fOff_1[0][0] = fMin_1[0][0]*fScal_1[0][0]+1.;
   fMin_1[1][0] = 65.0625;
   fMax_1[1][0] = 104.9375;
   fScal_1[1][0] = 2.0/(fMax_1[1][0]-fMin_1[1][0]);
   fOff_1[1][0] = fMin_1[1][0]*fScal_1[1][0]+1.;
   fMin_1[2][0] = 65.0625;
   fMax_1[2][0] = 104.9375;
   fScal_1[2][0] = 2.0/(fMax_1[2][0]-fMin_1[2][0]);
   fOff_1[2][0] = fMin_1[2][0]*fScal_1[2][0]+1.;
   fMin_1[0][1] = 0.0703273266554;
   fMax_1[0][1] = 0.548578202724;
   fScal_1[0][1] = 2.0/(fMax_1[0][1]-fMin_1[0][1]);
   fOff_1[0][1] = fMin_1[0][1]*fScal_1[0][1]+1.;
   fMin_1[1][1] = 0.097385622561;
   fMax_1[1][1] = 0.549935996532;
   fScal_1[1][1] = 2.0/(fMax_1[1][1]-fMin_1[1][1]);
   fOff_1[1][1] = fMin_1[1][1]*fScal_1[1][1]+1.;
   fMin_1[2][1] = 0.0703273266554;
   fMax_1[2][1] = 0.549935996532;
   fScal_1[2][1] = 2.0/(fMax_1[2][1]-fMin_1[2][1]);
   fOff_1[2][1] = fMin_1[2][1]*fScal_1[2][1]+1.;
   fMin_1[0][2] = -2.494140625;
   fMax_1[0][2] = 2.470703125;
   fScal_1[0][2] = 2.0/(fMax_1[0][2]-fMin_1[0][2]);
   fOff_1[0][2] = fMin_1[0][2]*fScal_1[0][2]+1.;
   fMin_1[1][2] = -2.498046875;
   fMax_1[1][2] = 2.49951171875;
   fScal_1[1][2] = 2.0/(fMax_1[1][2]-fMin_1[1][2]);
   fOff_1[1][2] = fMin_1[1][2]*fScal_1[1][2]+1.;
   fMin_1[2][2] = -2.498046875;
   fMax_1[2][2] = 2.49951171875;
   fScal_1[2][2] = 2.0/(fMax_1[2][2]-fMin_1[2][2]);
   fOff_1[2][2] = fMin_1[2][2]*fScal_1[2][2]+1.;
   fMin_1[0][3] = 2;
   fMax_1[0][3] = 8;
   fScal_1[0][3] = 2.0/(fMax_1[0][3]-fMin_1[0][3]);
   fOff_1[0][3] = fMin_1[0][3]*fScal_1[0][3]+1.;
   fMin_1[1][3] = 2;
   fMax_1[1][3] = 8;
   fScal_1[1][3] = 2.0/(fMax_1[1][3]-fMin_1[1][3]);
   fOff_1[1][3] = fMin_1[1][3]*fScal_1[1][3]+1.;
   fMin_1[2][3] = 2;
   fMax_1[2][3] = 8;
   fScal_1[2][3] = 2.0/(fMax_1[2][3]-fMin_1[2][3]);
   fOff_1[2][3] = fMin_1[2][3]*fScal_1[2][3]+1.;
   fMin_1[0][4] = -4.2705078125;
   fMax_1[0][4] = 4.6123046875;
   fScal_1[0][4] = 2.0/(fMax_1[0][4]-fMin_1[0][4]);
   fOff_1[0][4] = fMin_1[0][4]*fScal_1[0][4]+1.;
   fMin_1[1][4] = -4.5439453125;
   fMax_1[1][4] = 4.4150390625;
   fScal_1[1][4] = 2.0/(fMax_1[1][4]-fMin_1[1][4]);
   fOff_1[1][4] = fMin_1[1][4]*fScal_1[1][4]+1.;
   fMin_1[2][4] = -4.5439453125;
   fMax_1[2][4] = 4.6123046875;
   fScal_1[2][4] = 2.0/(fMax_1[2][4]-fMin_1[2][4]);
   fOff_1[2][4] = fMin_1[2][4]*fScal_1[2][4]+1.;
   fMin_1[0][5] = 50.2703475952;
   fMax_1[0][5] = 1335.79541016;
   fScal_1[0][5] = 2.0/(fMax_1[0][5]-fMin_1[0][5]);
   fOff_1[0][5] = fMin_1[0][5]*fScal_1[0][5]+1.;
   fMin_1[1][5] = 52.7401771545;
   fMax_1[1][5] = 677.227844238;
   fScal_1[1][5] = 2.0/(fMax_1[1][5]-fMin_1[1][5]);
   fOff_1[1][5] = fMin_1[1][5]*fScal_1[1][5]+1.;
   fMin_1[2][5] = 50.2703475952;
   fMax_1[2][5] = 1335.79541016;
   fScal_1[2][5] = 2.0/(fMax_1[2][5]-fMin_1[2][5]);
   fOff_1[2][5] = fMin_1[2][5]*fScal_1[2][5]+1.;
   fMin_1[0][6] = -1;
   fMax_1[0][6] = 0.99951171875;
   fScal_1[0][6] = 2.0/(fMax_1[0][6]-fMin_1[0][6]);
   fOff_1[0][6] = fMin_1[0][6]*fScal_1[0][6]+1.;
   fMin_1[1][6] = -1;
   fMax_1[1][6] = 0.99951171875;
   fScal_1[1][6] = 2.0/(fMax_1[1][6]-fMin_1[1][6]);
   fOff_1[1][6] = fMin_1[1][6]*fScal_1[1][6]+1.;
   fMin_1[2][6] = -1;
   fMax_1[2][6] = 0.99951171875;
   fScal_1[2][6] = 2.0/(fMax_1[2][6]-fMin_1[2][6]);
   fOff_1[2][6] = fMin_1[2][6]*fScal_1[2][6]+1.;
   fMin_1[0][7] = -4.830078125;
   fMax_1[0][7] = 4.822265625;
   fScal_1[0][7] = 2.0/(fMax_1[0][7]-fMin_1[0][7]);
   fOff_1[0][7] = fMin_1[0][7]*fScal_1[0][7]+1.;
   fMin_1[1][7] = -4.76171875;
   fMax_1[1][7] = 4.83203125;
   fScal_1[1][7] = 2.0/(fMax_1[1][7]-fMin_1[1][7]);
   fOff_1[1][7] = fMin_1[1][7]*fScal_1[1][7]+1.;
   fMin_1[2][7] = -4.830078125;
   fMax_1[2][7] = 4.83203125;
   fScal_1[2][7] = 2.0/(fMax_1[2][7]-fMin_1[2][7]);
   fOff_1[2][7] = fMin_1[2][7]*fScal_1[2][7]+1.;
   fMin_1[0][8] = 50.0087356567;
   fMax_1[0][8] = 656.952087402;
   fScal_1[0][8] = 2.0/(fMax_1[0][8]-fMin_1[0][8]);
   fOff_1[0][8] = fMin_1[0][8]*fScal_1[0][8]+1.;
   fMin_1[1][8] = 50.0074539185;
   fMax_1[1][8] = 378.358673096;
   fScal_1[1][8] = 2.0/(fMax_1[1][8]-fMin_1[1][8]);
   fOff_1[1][8] = fMin_1[1][8]*fScal_1[1][8]+1.;
   fMin_1[2][8] = 50.0074539185;
   fMax_1[2][8] = 656.952087402;
   fScal_1[2][8] = 2.0/(fMax_1[2][8]-fMin_1[2][8]);
   fOff_1[2][8] = fMin_1[2][8]*fScal_1[2][8]+1.;
   fMin_1[0][9] = -1;
   fMax_1[0][9] = 0.99951171875;
   fScal_1[0][9] = 2.0/(fMax_1[0][9]-fMin_1[0][9]);
   fOff_1[0][9] = fMin_1[0][9]*fScal_1[0][9]+1.;
   fMin_1[1][9] = -1;
   fMax_1[1][9] = 0.99951171875;
   fScal_1[1][9] = 2.0/(fMax_1[1][9]-fMin_1[1][9]);
   fOff_1[1][9] = fMin_1[1][9]*fScal_1[1][9]+1.;
   fMin_1[2][9] = -1;
   fMax_1[2][9] = 0.99951171875;
   fScal_1[2][9] = 2.0/(fMax_1[2][9]-fMin_1[2][9]);
   fOff_1[2][9] = fMin_1[2][9]*fScal_1[2][9]+1.;
   fMin_1[0][10] = 2.50122070312;
   fMax_1[0][10] = 8.2470703125;
   fScal_1[0][10] = 2.0/(fMax_1[0][10]-fMin_1[0][10]);
   fOff_1[0][10] = fMin_1[0][10]*fScal_1[0][10]+1.;
   fMin_1[1][10] = 2.51300048828;
   fMax_1[1][10] = 7.6787109375;
   fScal_1[1][10] = 2.0/(fMax_1[1][10]-fMin_1[1][10]);
   fOff_1[1][10] = fMin_1[1][10]*fScal_1[1][10]+1.;
   fMin_1[2][10] = 2.50122070312;
   fMax_1[2][10] = 8.2470703125;
   fScal_1[2][10] = 2.0/(fMax_1[2][10]-fMin_1[2][10]);
   fOff_1[2][10] = fMin_1[2][10]*fScal_1[2][10]+1.;
   fMin_1[0][11] = -5.84900569916;
   fMax_1[0][11] = 6.13960266113;
   fScal_1[0][11] = 2.0/(fMax_1[0][11]-fMin_1[0][11]);
   fOff_1[0][11] = fMin_1[0][11]*fScal_1[0][11]+1.;
   fMin_1[1][11] = -4.75859832764;
   fMax_1[1][11] = 5.48850154877;
   fScal_1[1][11] = 2.0/(fMax_1[1][11]-fMin_1[1][11]);
   fOff_1[1][11] = fMin_1[1][11]*fScal_1[1][11]+1.;
   fMin_1[2][11] = -5.84900569916;
   fMax_1[2][11] = 6.13960266113;
   fScal_1[2][11] = 2.0/(fMax_1[2][11]-fMin_1[2][11]);
   fOff_1[2][11] = fMin_1[2][11]*fScal_1[2][11]+1.;
   fMin_1[0][12] = 500.611633301;
   fMax_1[0][12] = 7465.87548828;
   fScal_1[0][12] = 2.0/(fMax_1[0][12]-fMin_1[0][12]);
   fOff_1[0][12] = fMin_1[0][12]*fScal_1[0][12]+1.;
   fMin_1[1][12] = 500.211364746;
   fMax_1[1][12] = 4607.83740234;
   fScal_1[1][12] = 2.0/(fMax_1[1][12]-fMin_1[1][12]);
   fOff_1[1][12] = fMin_1[1][12]*fScal_1[1][12]+1.;
   fMin_1[2][12] = 500.211364746;
   fMax_1[2][12] = 7465.87548828;
   fScal_1[2][12] = 2.0/(fMax_1[2][12]-fMin_1[2][12]);
   fOff_1[2][12] = fMin_1[2][12]*fScal_1[2][12]+1.;
   fMin_1[0][13] = -3.64942932129;
   fMax_1[0][13] = 4.19094085693;
   fScal_1[0][13] = 2.0/(fMax_1[0][13]-fMin_1[0][13]);
   fOff_1[0][13] = fMin_1[0][13]*fScal_1[0][13]+1.;
   fMin_1[1][13] = -3.68803405762;
   fMax_1[1][13] = 3.68408203125;
   fScal_1[1][13] = 2.0/(fMax_1[1][13]-fMin_1[1][13]);
   fOff_1[1][13] = fMin_1[1][13]*fScal_1[1][13]+1.;
   fMin_1[2][13] = -3.68803405762;
   fMax_1[2][13] = 4.19094085693;
   fScal_1[2][13] = 2.0/(fMax_1[2][13]-fMin_1[2][13]);
   fOff_1[2][13] = fMin_1[2][13]*fScal_1[2][13]+1.;
   fMin_1[0][14] = -4.21001291275;
   fMax_1[0][14] = 4.69680309296;
   fScal_1[0][14] = 2.0/(fMax_1[0][14]-fMin_1[0][14]);
   fOff_1[0][14] = fMin_1[0][14]*fScal_1[0][14]+1.;
   fMin_1[1][14] = -4.53291130066;
   fMax_1[1][14] = 5.84013319016;
   fScal_1[1][14] = 2.0/(fMax_1[1][14]-fMin_1[1][14]);
   fOff_1[1][14] = fMin_1[1][14]*fScal_1[1][14]+1.;
   fMin_1[2][14] = -4.53291130066;
   fMax_1[2][14] = 5.84013319016;
   fScal_1[2][14] = 2.0/(fMax_1[2][14]-fMin_1[2][14]);
   fOff_1[2][14] = fMin_1[2][14]*fScal_1[2][14]+1.;
}

//_______________________________________________________________________
inline void ReadDNN_GPU::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 15;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) {
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
      indicesGet.push_back( 11);
      indicesGet.push_back( 12);
      indicesGet.push_back( 13);
      indicesGet.push_back( 14);
   }
   if ( indicesPut.empty() ) {
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
      indicesPut.push_back( 11);
      indicesPut.push_back( 12);
      indicesPut.push_back( 13);
      indicesPut.push_back( 14);
   }

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<15;ivar++) {
      double offset = fOff_1[cls][ivar];
      double scale  = fScal_1[cls][ivar];
      iv[indicesPut.at(ivar)] = scale*dv[ivar]-offset;
   }
}

//_______________________________________________________________________
inline void ReadDNN_GPU::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadDNN_GPU::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
