// Class: ReadMLPBFGS
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLPBFGS
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.26/06       [399878]
Creator        : markm
Date           : Wed Nov  2 10:49:56 2022
Host           : Linux kgizdov 5.19.4-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 25 Aug 2022 17:31:12 +0000 x86_64 GNU/Linux
Dir            : /home/markm/code/EAL
Training events: 509070
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TrainingMethod: "BFGS" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 15
bos_j1_AK4_eta                bos_j1_AK4_eta                bos_j1_AK4_eta                bos_j1_AK4_eta                                                  'F'    [-2.39990234375,2.39990234375]
bos_j2_AK4_eta                bos_j2_AK4_eta                bos_j2_AK4_eta                bos_j2_AK4_eta                                                  'F'    [-2.39990234375,2.39990234375]
bos_j1_AK4_pt                 bos_j1_AK4_pt                 bos_j1_AK4_pt                 bos_j1_AK4_pt                                                   'F'    [30.0006580353,1195.94262695]
bos_j2_AK4_pt                 bos_j2_AK4_pt                 bos_j2_AK4_pt                 bos_j2_AK4_pt                                                   'F'    [30.0000667572,231.128250122]
bos_AK4AK4_m                  bos_AK4AK4_m                  bos_AK4AK4_m                  bos_AK4AK4_m                                                    'F'    [65.0001831055,104.999771118]
lep1_eta                      lep1_eta                      lep1_eta                      lep1_eta                                                        'F'    [-2.5,2.49951171875]
vbf_eta                       vbf_eta                       vbf_eta                       vbf_eta                                                         'F'    [-10.3141937256,8.83829593658]
vbf1_AK4_qgid                 vbf1_AK4_qgid                 vbf1_AK4_qgid                 vbf1_AK4_qgid                                                   'F'    [5.29736280441e-06,1]
vbf2_AK4_eta                  vbf2_AK4_eta                  vbf2_AK4_eta                  vbf2_AK4_eta                                                    'F'    [-4.69921875,4.6982421875]
vbf2_AK4_qgid                 vbf2_AK4_qgid                 vbf2_AK4_qgid                 vbf2_AK4_qgid                                                   'F'    [1.86380930245e-07,1]
bos_j1_AK4_m                  bos_j1_AK4_m                  bos_j1_AK4_m                  bos_j1_AK4_m                                                    'F'    [-0.0176696777344,85.25]
bos_j2_AK4_m                  bos_j2_AK4_m                  bos_j2_AK4_m                  bos_j2_AK4_m                                                    'F'    [-3.0156224966e-06,31.8125]
vbf_deta                      vbf_deta                      vbf_deta                      vbf_deta                                                        'F'    [2.50006103516,9.203125]
vbf_m                         vbf_m                         vbf_m                         vbf_m                                                           'F'    [500.000946045,9701.84667969]
zeppLep                       zeppLep                       zeppLep                       zeppLep                                                         'F'    [-3.57376289368,3.79529452324]
NSpec 62
vbf1_AK4_eta                  vbf1_AK4_eta                  vbf1_AK4_eta                  F                                                               'F'    [-4.69140625,4.6796875]
nJet30f                       nJet30f                       nJet30f                       F                                                               'F'    [4,15]
MET                           MET                           MET                           F                                                               'F'    [30.0000190735,2257.62646484]
vbf1_AK4_pt                   vbf1_AK4_pt                   vbf1_AK4_pt                   F                                                               'F'    [50.0006828308,3909.90454102]
vbf2_AK4_pt                   vbf2_AK4_pt                   vbf2_AK4_pt                   F                                                               'F'    [50.000038147,1709.40551758]
lep1_pt                       lep1_pt                       lep1_pt                       F                                                               'F'    [25.0000286102,4278.88623047]
bos_PuppiAK8_eta              bos_PuppiAK8_eta              bos_PuppiAK8_eta              F                                                               'F'    [-999,-999]
bos_PuppiAK8_m_sd0_corr       bos_PuppiAK8_m_sd0_corr       bos_PuppiAK8_m_sd0_corr       F                                                               'F'    [-999,-999]
bos_PuppiAK8_tau2tau1         bos_PuppiAK8_tau2tau1         bos_PuppiAK8_tau2tau1         F                                                               'F'    [-999,-999]
AntiIsoInt                    AntiIsoInt                    AntiIsoInt                    I                                                               'F'    [0,0]
bos_AK4AK4_pt                 bos_AK4AK4_pt                 bos_AK4AK4_pt                 F                                                               'F'    [0.281953990459,1226.6204834]
bosCent                       bosCent                       bosCent                       F                                                               'F'    [2.38418579102e-07,4.35909748077]
dibos_m                       dibos_m                       dibos_m                       F                                                               'F'    [93.8686828613,3062.52148438]
bos_AK4AK4_eta                bos_AK4AK4_eta                bos_AK4AK4_eta                F                                                               'F'    [-4.23310136795,4.32719898224]
bos_PuppiAK8_m_sd0            bos_PuppiAK8_m_sd0            bos_PuppiAK8_m_sd0            F                                                               'F'    [-999,-999]
bos_PuppiAK8_phi              bos_PuppiAK8_phi              bos_PuppiAK8_phi              F                                                               'F'    [-999,-999]
bos_PuppiAK8_pt               bos_PuppiAK8_pt               bos_PuppiAK8_pt               F                                                               'F'    [-999,-999]
btagWeight_loose              btagWeight_loose              btagWeight_loose              F                                                               'F'    [0.476367205381,2.57436585426]
dibos_eta                     dibos_eta                     dibos_eta                     F                                                               'F'    [-7.51050662994,6.89371395111]
dibos_mt                      dibos_mt                      dibos_mt                      F                                                               'F'    [133.273742676,4536.5546875]
dibos_phi                     dibos_phi                     dibos_phi                     F                                                               'F'    [-3.14155912399,3.14158678055]
dibos_pt                      dibos_pt                      dibos_pt                      F                                                               'F'    [0.259168088436,4067.73413086]
dilep_eta                     dilep_eta                     dilep_eta                     F                                                               'F'    [-3.96839094162,4.45234680176]
dilep_m                       dilep_m                       dilep_m                       F                                                               'F'    [0.406403690577,1354.13037109]
dilep_mt                      dilep_mt                      dilep_mt                      F                                                               'F'    [55.472946167,4377.96923828]
dilep_phi                     dilep_phi                     dilep_phi                     F                                                               'F'    [-3.14158129692,3.14158773422]
dilep_pt                      dilep_pt                      dilep_pt                      F                                                               'F'    [1.27604925632,4186.30664062]
evt                           evt                           evt                           I                                                               'F'    [14,386715520]
genWeight                     genWeight                     genWeight                     F                                                               'F'    [-316.46875,316.46875]
gid                           gid                           gid                           I                                                               'F'    [1,15]
L1PFWeight                    L1PFWeight                    L1PFWeight                    F                                                               'F'    [0.0192610062659,1]
lep1_idEffWeight              lep1_idEffWeight              lep1_idEffWeight              F                                                               'F'    [0.867357492447,1.06021249294]
lep1_iso                      lep1_iso                      lep1_iso                      F                                                               'F'    [0,0.149985522032]
lep1_m                        lep1_m                        lep1_m                        F                                                               'F'    [0.000510999991093,0.105658374727]
lep1_phi                      lep1_phi                      lep1_phi                      F                                                               'F'    [-3.1416015625,3.1416015625]
lep1_q                        lep1_q                        lep1_q                        F                                                               'F'    [-1,1]
lep1_trigEffWeight            lep1_trigEffWeight            lep1_trigEffWeight            F                                                               'F'    [1,1]
lep2_eta                      lep2_eta                      lep2_eta                      F                                                               'F'    [-999,-999]
lep2_idEffWeight              lep2_idEffWeight              lep2_idEffWeight              F                                                               'F'    [1,1]
lep2_phi                      lep2_phi                      lep2_phi                      F                                                               'F'    [-999,-999]
lep2_pt                       lep2_pt                       lep2_pt                       F                                                               'F'    [-999,-999]
lep2_trigEffWeight            lep2_trigEffWeight            lep2_trigEffWeight            F                                                               'F'    [1,1]
lumin                         lumin                         lumin                         F                                                               'F'    [35867.0585938,59740]
mcWeight                      mcWeight                      mcWeight                      F                                                               'F'    [3.87841064819e-10,0.000135022753966]
MET_phi                       MET_phi                       MET_phi                       F                                                               'F'    [-3.14151477814,3.1415913105]
nBtag_loose                   nBtag_loose                   nBtag_loose                   I                                                               'F'    [0,0]
nBtag_medium                  nBtag_medium                  nBtag_medium                  I                                                               'F'    [0,0]
neu_pz_type0                  neu_pz_type0                  neu_pz_type0                  F                                                               'F'    [-999,-999]
nJet30                        nJet30                        nJet30                        I                                                               'F'    [4,15]
nJet50                        nJet50                        nJet50                        I                                                               'F'    [2,11]
nPV                           nPV                           nPV                           F                                                               'F'    [1,107]
puWeight                      puWeight                      puWeight                      F                                                               'F'    [0,46.9509277344]
run                           run                           run                           I                                                               'F'    [1,1]
vbf1_AK4_phi                  vbf1_AK4_phi                  vbf1_AK4_phi                  F                                                               'F'    [-3.1416015625,3.1416015625]
vbf2_AK4_phi                  vbf2_AK4_phi                  vbf2_AK4_phi                  F                                                               'F'    [-3.1416015625,3.1416015625]
vbf1_AK4_m                    vbf1_AK4_m                    vbf1_AK4_m                    F                                                               'F'    [0.9990234375,382]
vbf2_AK4_m                    vbf2_AK4_m                    vbf2_AK4_m                    F                                                               'F'    [1.0654296875,300.5]
vbf_pt                        vbf_pt                        vbf_pt                        F                                                               'F'    [0.0370486527681,3852.95385742]
vbf_phi                       vbf_phi                       vbf_phi                       F                                                               'F'    [-3.14158248901,3.14158940315]
year                          year                          year                          I                                                               'F'    [2016,2018]
class_id                      class_id                      class_id                      I                                                               'F'    [0,1]
zeppHad                       zeppHad                       zeppHad                       F                                                               'F'    [-3.8768427372,3.89899778366]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLPBFGS : public IClassifierReader {

 public:

   // constructor
   ReadMLPBFGS( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadMLPBFGS" ),
        fNvars( 15 )
   {
      // the training input variables
      const char* inputVars[] = { "bos_j1_AK4_eta", "bos_j2_AK4_eta", "bos_j1_AK4_pt", "bos_j2_AK4_pt", "bos_AK4AK4_m", "lep1_eta", "vbf_eta", "vbf1_AK4_qgid", "vbf2_AK4_eta", "vbf2_AK4_qgid", "bos_j1_AK4_m", "bos_j2_AK4_m", "vbf_deta", "vbf_m", "zeppLep" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;
      fVmin[11] = -1;
      fVmax[11] = 1;
      fVmin[12] = -1;
      fVmax[12] = 1;
      fVmin[13] = -1;
      fVmax[13] = 1;
      fVmin[14] = -1;
      fVmax[14] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLPBFGS() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fOff_1[3][15];
   double fScal_1[3][15];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[15];
   double fVmax[15];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[15];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   double fWeightMatrix0to1[21][16];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][21];   // weight matrix from layer 1 to 2

};

inline void ReadMLPBFGS::Initialize()
{
   // build network structure
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.0102156806411017;
   fWeightMatrix0to1[1][0] = 2.17680341888954;
   fWeightMatrix0to1[2][0] = -0.127889832147671;
   fWeightMatrix0to1[3][0] = 0.692352468266095;
   fWeightMatrix0to1[4][0] = -1.83318528322476;
   fWeightMatrix0to1[5][0] = -0.908083745114351;
   fWeightMatrix0to1[6][0] = -1.90744115741107;
   fWeightMatrix0to1[7][0] = 1.57885743722335;
   fWeightMatrix0to1[8][0] = -1.29202130091447;
   fWeightMatrix0to1[9][0] = -1.04179312867102;
   fWeightMatrix0to1[10][0] = -2.17915402564644;
   fWeightMatrix0to1[11][0] = -0.186074619014271;
   fWeightMatrix0to1[12][0] = -1.13651705892571;
   fWeightMatrix0to1[13][0] = -0.473041153446664;
   fWeightMatrix0to1[14][0] = -0.487511066031433;
   fWeightMatrix0to1[15][0] = 0.629510359896924;
   fWeightMatrix0to1[16][0] = -0.664237947676061;
   fWeightMatrix0to1[17][0] = 1.75329595362814;
   fWeightMatrix0to1[18][0] = -0.10102605713417;
   fWeightMatrix0to1[19][0] = 0.834744265292701;
   fWeightMatrix0to1[0][1] = 0.0503038373163972;
   fWeightMatrix0to1[1][1] = -2.54031612081997;
   fWeightMatrix0to1[2][1] = 0.0433243098517467;
   fWeightMatrix0to1[3][1] = -1.16522782201023;
   fWeightMatrix0to1[4][1] = -0.959866613457163;
   fWeightMatrix0to1[5][1] = 0.403468717669518;
   fWeightMatrix0to1[6][1] = 1.4812469393795;
   fWeightMatrix0to1[7][1] = -0.635615273368104;
   fWeightMatrix0to1[8][1] = -1.77840195568461;
   fWeightMatrix0to1[9][1] = 0.115619763794258;
   fWeightMatrix0to1[10][1] = 1.77428045117501;
   fWeightMatrix0to1[11][1] = 1.12035200579479;
   fWeightMatrix0to1[12][1] = -0.373568904612897;
   fWeightMatrix0to1[13][1] = -0.110584277396994;
   fWeightMatrix0to1[14][1] = 0.0448787576480471;
   fWeightMatrix0to1[15][1] = -0.401182589910781;
   fWeightMatrix0to1[16][1] = -1.5600273946544;
   fWeightMatrix0to1[17][1] = 1.64464396011248;
   fWeightMatrix0to1[18][1] = -0.300106229458517;
   fWeightMatrix0to1[19][1] = 0.652894884490479;
   fWeightMatrix0to1[0][2] = 1.14996643174877;
   fWeightMatrix0to1[1][2] = -0.376762178110007;
   fWeightMatrix0to1[2][2] = 3.47461723228285;
   fWeightMatrix0to1[3][2] = 1.98391296851786;
   fWeightMatrix0to1[4][2] = -0.685175126723753;
   fWeightMatrix0to1[5][2] = -2.2344336108935;
   fWeightMatrix0to1[6][2] = 0.518844673957895;
   fWeightMatrix0to1[7][2] = 1.05697364030609;
   fWeightMatrix0to1[8][2] = 1.76084963933785;
   fWeightMatrix0to1[9][2] = 2.30390319116536;
   fWeightMatrix0to1[10][2] = 1.18032081545779;
   fWeightMatrix0to1[11][2] = 2.00313213040193;
   fWeightMatrix0to1[12][2] = -2.27193750760569;
   fWeightMatrix0to1[13][2] = 0.196654325988894;
   fWeightMatrix0to1[14][2] = -1.81761581823825;
   fWeightMatrix0to1[15][2] = -0.989426514636239;
   fWeightMatrix0to1[16][2] = -1.28711066489549;
   fWeightMatrix0to1[17][2] = -1.85385479388176;
   fWeightMatrix0to1[18][2] = 1.71342967331003;
   fWeightMatrix0to1[19][2] = 0.673767868287224;
   fWeightMatrix0to1[0][3] = -1.7124547750352;
   fWeightMatrix0to1[1][3] = 0.0916916416170766;
   fWeightMatrix0to1[2][3] = 1.00319911658762;
   fWeightMatrix0to1[3][3] = 0.969597363641298;
   fWeightMatrix0to1[4][3] = 1.98211027693072;
   fWeightMatrix0to1[5][3] = -0.444674494111466;
   fWeightMatrix0to1[6][3] = 0.347853961998067;
   fWeightMatrix0to1[7][3] = -0.137455108736553;
   fWeightMatrix0to1[8][3] = 0.969282247794063;
   fWeightMatrix0to1[9][3] = 0.247045373604261;
   fWeightMatrix0to1[10][3] = -1.18386137494464;
   fWeightMatrix0to1[11][3] = -0.64029707298851;
   fWeightMatrix0to1[12][3] = -0.00203000129946845;
   fWeightMatrix0to1[13][3] = -0.140508546451304;
   fWeightMatrix0to1[14][3] = 1.67186853138494;
   fWeightMatrix0to1[15][3] = -0.329051108487156;
   fWeightMatrix0to1[16][3] = -1.84283537316214;
   fWeightMatrix0to1[17][3] = -1.89187444585046;
   fWeightMatrix0to1[18][3] = 1.6751054036632;
   fWeightMatrix0to1[19][3] = 0.586184375112603;
   fWeightMatrix0to1[0][4] = 1.57917918772392;
   fWeightMatrix0to1[1][4] = -0.163198496468528;
   fWeightMatrix0to1[2][4] = -0.121061909775634;
   fWeightMatrix0to1[3][4] = -0.709077934014199;
   fWeightMatrix0to1[4][4] = -0.83336949657809;
   fWeightMatrix0to1[5][4] = -0.193351645844346;
   fWeightMatrix0to1[6][4] = 0.714548131090982;
   fWeightMatrix0to1[7][4] = -0.0662880504155187;
   fWeightMatrix0to1[8][4] = -1.40177682484256;
   fWeightMatrix0to1[9][4] = -1.15075500379281;
   fWeightMatrix0to1[10][4] = -1.14167084376343;
   fWeightMatrix0to1[11][4] = 0.0669044959320683;
   fWeightMatrix0to1[12][4] = 1.13002693324593;
   fWeightMatrix0to1[13][4] = -1.11887420624317;
   fWeightMatrix0to1[14][4] = -0.0616781796259683;
   fWeightMatrix0to1[15][4] = 2.06885657260444;
   fWeightMatrix0to1[16][4] = -0.627341745312575;
   fWeightMatrix0to1[17][4] = -1.21015098527374;
   fWeightMatrix0to1[18][4] = -0.0175235284470346;
   fWeightMatrix0to1[19][4] = 0.152294161966115;
   fWeightMatrix0to1[0][5] = -2.08708333341316;
   fWeightMatrix0to1[1][5] = -1.0813951984455;
   fWeightMatrix0to1[2][5] = -0.24149869588644;
   fWeightMatrix0to1[3][5] = 2.08788317837323;
   fWeightMatrix0to1[4][5] = -1.10214090405884;
   fWeightMatrix0to1[5][5] = 0.763434008765907;
   fWeightMatrix0to1[6][5] = -0.670994640737713;
   fWeightMatrix0to1[7][5] = -1.36132210667723;
   fWeightMatrix0to1[8][5] = -0.0754641453396918;
   fWeightMatrix0to1[9][5] = -0.188896574420344;
   fWeightMatrix0to1[10][5] = -1.4670039702113;
   fWeightMatrix0to1[11][5] = -0.938699700029134;
   fWeightMatrix0to1[12][5] = 0.773352853975566;
   fWeightMatrix0to1[13][5] = 0.734516421147761;
   fWeightMatrix0to1[14][5] = -1.0446764179067;
   fWeightMatrix0to1[15][5] = 1.67532436650457;
   fWeightMatrix0to1[16][5] = 0.519958415413604;
   fWeightMatrix0to1[17][5] = -0.932222005521233;
   fWeightMatrix0to1[18][5] = -0.598312433356837;
   fWeightMatrix0to1[19][5] = -1.33076664319147;
   fWeightMatrix0to1[0][6] = -1.47397455536882;
   fWeightMatrix0to1[1][6] = 0.750463810796878;
   fWeightMatrix0to1[2][6] = 0.151474630291401;
   fWeightMatrix0to1[3][6] = -0.396514462111751;
   fWeightMatrix0to1[4][6] = 0.87253250803199;
   fWeightMatrix0to1[5][6] = 0.172638314863104;
   fWeightMatrix0to1[6][6] = 0.407940884247622;
   fWeightMatrix0to1[7][6] = 0.0612364570366133;
   fWeightMatrix0to1[8][6] = -1.77616588135434;
   fWeightMatrix0to1[9][6] = 1.02767642781893;
   fWeightMatrix0to1[10][6] = 0.919368664630791;
   fWeightMatrix0to1[11][6] = -1.81050119840722;
   fWeightMatrix0to1[12][6] = 0.582622452687766;
   fWeightMatrix0to1[13][6] = -1.3314525918528;
   fWeightMatrix0to1[14][6] = 0.0952514239781328;
   fWeightMatrix0to1[15][6] = 1.08763107739815;
   fWeightMatrix0to1[16][6] = 1.80701841569322;
   fWeightMatrix0to1[17][6] = -1.83420931582724;
   fWeightMatrix0to1[18][6] = 0.586023897325149;
   fWeightMatrix0to1[19][6] = 1.58236229212404;
   fWeightMatrix0to1[0][7] = 1.65028620816318;
   fWeightMatrix0to1[1][7] = -0.0188012712413151;
   fWeightMatrix0to1[2][7] = -0.00244155126889093;
   fWeightMatrix0to1[3][7] = -0.0511294339667924;
   fWeightMatrix0to1[4][7] = -1.2857613836221;
   fWeightMatrix0to1[5][7] = 2.13566781746891;
   fWeightMatrix0to1[6][7] = -0.216536231925142;
   fWeightMatrix0to1[7][7] = -0.540122809653762;
   fWeightMatrix0to1[8][7] = -0.25284753434549;
   fWeightMatrix0to1[9][7] = -0.254891477132446;
   fWeightMatrix0to1[10][7] = 0.027559338065744;
   fWeightMatrix0to1[11][7] = -0.100071063304261;
   fWeightMatrix0to1[12][7] = 1.66362925311404;
   fWeightMatrix0to1[13][7] = -0.0975684184280304;
   fWeightMatrix0to1[14][7] = 0.594969071715306;
   fWeightMatrix0to1[15][7] = 0.514551415449054;
   fWeightMatrix0to1[16][7] = 0.722957664687088;
   fWeightMatrix0to1[17][7] = 0.382214437476058;
   fWeightMatrix0to1[18][7] = 0.0479105098186271;
   fWeightMatrix0to1[19][7] = -1.33199471927346;
   fWeightMatrix0to1[0][8] = 1.79573876507869;
   fWeightMatrix0to1[1][8] = 0.355329468371046;
   fWeightMatrix0to1[2][8] = 0.0882853370672409;
   fWeightMatrix0to1[3][8] = -0.897925590019476;
   fWeightMatrix0to1[4][8] = 1.14695679537776;
   fWeightMatrix0to1[5][8] = 0.0644484897492553;
   fWeightMatrix0to1[6][8] = 0.335039161596744;
   fWeightMatrix0to1[7][8] = 1.05216932848635;
   fWeightMatrix0to1[8][8] = -0.702667744524263;
   fWeightMatrix0to1[9][8] = -0.109225813478819;
   fWeightMatrix0to1[10][8] = 0.253573252560235;
   fWeightMatrix0to1[11][8] = 1.14297220955657;
   fWeightMatrix0to1[12][8] = -0.664922921310962;
   fWeightMatrix0to1[13][8] = 1.09908581912004;
   fWeightMatrix0to1[14][8] = 2.2353290388738;
   fWeightMatrix0to1[15][8] = -1.70876859373728;
   fWeightMatrix0to1[16][8] = 0.345658537337992;
   fWeightMatrix0to1[17][8] = 0.393313310455198;
   fWeightMatrix0to1[18][8] = 0.136642875651918;
   fWeightMatrix0to1[19][8] = -1.70895201746913;
   fWeightMatrix0to1[0][9] = -1.1503959235155;
   fWeightMatrix0to1[1][9] = -0.0880537671545152;
   fWeightMatrix0to1[2][9] = 0.00200793714319498;
   fWeightMatrix0to1[3][9] = -0.344967615758822;
   fWeightMatrix0to1[4][9] = -0.0207634887073583;
   fWeightMatrix0to1[5][9] = -0.421637794918358;
   fWeightMatrix0to1[6][9] = -0.174043554091118;
   fWeightMatrix0to1[7][9] = 0.879679475094154;
   fWeightMatrix0to1[8][9] = -0.283581009838256;
   fWeightMatrix0to1[9][9] = -0.467270341782873;
   fWeightMatrix0to1[10][9] = -0.153873254599006;
   fWeightMatrix0to1[11][9] = 0.460135141312098;
   fWeightMatrix0to1[12][9] = 2.0526379097195;
   fWeightMatrix0to1[13][9] = 0.886583060413442;
   fWeightMatrix0to1[14][9] = -0.207994377871501;
   fWeightMatrix0to1[15][9] = -0.861050031013113;
   fWeightMatrix0to1[16][9] = -2.01064117976799;
   fWeightMatrix0to1[17][9] = 0.953605714931519;
   fWeightMatrix0to1[18][9] = 0.1700579107647;
   fWeightMatrix0to1[19][9] = -1.0565054917848;
   fWeightMatrix0to1[0][10] = -0.789249021008376;
   fWeightMatrix0to1[1][10] = 0.491244994571347;
   fWeightMatrix0to1[2][10] = -1.84045630044443;
   fWeightMatrix0to1[3][10] = -0.28749565432602;
   fWeightMatrix0to1[4][10] = 1.56919229726392;
   fWeightMatrix0to1[5][10] = -0.0221741426298295;
   fWeightMatrix0to1[6][10] = -0.503652058933684;
   fWeightMatrix0to1[7][10] = 0.338952046278501;
   fWeightMatrix0to1[8][10] = 1.88807304724865;
   fWeightMatrix0to1[9][10] = 1.54458905883896;
   fWeightMatrix0to1[10][10] = 1.19282983336606;
   fWeightMatrix0to1[11][10] = 0.0918670142815166;
   fWeightMatrix0to1[12][10] = -2.08123794166192;
   fWeightMatrix0to1[13][10] = -1.47570756446212;
   fWeightMatrix0to1[14][10] = 0.914169716428918;
   fWeightMatrix0to1[15][10] = 1.12146781689047;
   fWeightMatrix0to1[16][10] = 0.835186809184539;
   fWeightMatrix0to1[17][10] = 0.245086437756694;
   fWeightMatrix0to1[18][10] = -1.3946498471524;
   fWeightMatrix0to1[19][10] = -1.83779168439325;
   fWeightMatrix0to1[0][11] = -1.33026850377576;
   fWeightMatrix0to1[1][11] = 0.4786780107183;
   fWeightMatrix0to1[2][11] = -0.588181088282036;
   fWeightMatrix0to1[3][11] = 1.23435093827066;
   fWeightMatrix0to1[4][11] = 1.80618104606579;
   fWeightMatrix0to1[5][11] = -1.47753152837484;
   fWeightMatrix0to1[6][11] = 0.344282819882807;
   fWeightMatrix0to1[7][11] = 0.313825900911974;
   fWeightMatrix0to1[8][11] = -1.58287783192242;
   fWeightMatrix0to1[9][11] = -0.433067953367118;
   fWeightMatrix0to1[10][11] = 1.16789102327677;
   fWeightMatrix0to1[11][11] = 0.339508947280278;
   fWeightMatrix0to1[12][11] = 0.687054212051637;
   fWeightMatrix0to1[13][11] = -1.80977644838028;
   fWeightMatrix0to1[14][11] = 1.53547706122952;
   fWeightMatrix0to1[15][11] = -1.92048294398995;
   fWeightMatrix0to1[16][11] = 0.867134884993541;
   fWeightMatrix0to1[17][11] = 0.0561400220311759;
   fWeightMatrix0to1[18][11] = -0.900450519010562;
   fWeightMatrix0to1[19][11] = -1.30468129214487;
   fWeightMatrix0to1[0][12] = -2.1052818366238;
   fWeightMatrix0to1[1][12] = -0.473047060624814;
   fWeightMatrix0to1[2][12] = -1.49708188756958;
   fWeightMatrix0to1[3][12] = -1.97956016627784;
   fWeightMatrix0to1[4][12] = -1.83063858151651;
   fWeightMatrix0to1[5][12] = 0.456027795481537;
   fWeightMatrix0to1[6][12] = -0.621601422610925;
   fWeightMatrix0to1[7][12] = -0.964999050133021;
   fWeightMatrix0to1[8][12] = 1.24191685733641;
   fWeightMatrix0to1[9][12] = -0.194617665984099;
   fWeightMatrix0to1[10][12] = 0.0157908905772829;
   fWeightMatrix0to1[11][12] = -0.864936717169413;
   fWeightMatrix0to1[12][12] = -0.376280026535813;
   fWeightMatrix0to1[13][12] = 0.864665177370176;
   fWeightMatrix0to1[14][12] = 1.10925461172919;
   fWeightMatrix0to1[15][12] = -0.58681163634003;
   fWeightMatrix0to1[16][12] = -1.58888160482195;
   fWeightMatrix0to1[17][12] = -0.831046221524339;
   fWeightMatrix0to1[18][12] = 0.735257846691164;
   fWeightMatrix0to1[19][12] = -2.02069765616404;
   fWeightMatrix0to1[0][13] = 0.094490302186962;
   fWeightMatrix0to1[1][13] = -1.02476273167835;
   fWeightMatrix0to1[2][13] = 2.29525623864047;
   fWeightMatrix0to1[3][13] = -1.27101939260436;
   fWeightMatrix0to1[4][13] = 0.255714108200035;
   fWeightMatrix0to1[5][13] = 0.0371240890748944;
   fWeightMatrix0to1[6][13] = -1.87671745886052;
   fWeightMatrix0to1[7][13] = 2.3682124130373;
   fWeightMatrix0to1[8][13] = 1.14675445846302;
   fWeightMatrix0to1[9][13] = 0.23858588566926;
   fWeightMatrix0to1[10][13] = -1.40650104142483;
   fWeightMatrix0to1[11][13] = 1.49218080934667;
   fWeightMatrix0to1[12][13] = 0.243655355532955;
   fWeightMatrix0to1[13][13] = -0.965525057101839;
   fWeightMatrix0to1[14][13] = -0.0711940278563975;
   fWeightMatrix0to1[15][13] = 0.042717781402815;
   fWeightMatrix0to1[16][13] = 1.34511938614414;
   fWeightMatrix0to1[17][13] = 1.10454197503688;
   fWeightMatrix0to1[18][13] = 2.36832238371871;
   fWeightMatrix0to1[19][13] = -0.530940204784035;
   fWeightMatrix0to1[0][14] = 0.108898044368259;
   fWeightMatrix0to1[1][14] = -0.317600496508169;
   fWeightMatrix0to1[2][14] = 0.0278197052030488;
   fWeightMatrix0to1[3][14] = 0.488321026020384;
   fWeightMatrix0to1[4][14] = -1.76300241007392;
   fWeightMatrix0to1[5][14] = -1.95149582979417;
   fWeightMatrix0to1[6][14] = -1.01993253224988;
   fWeightMatrix0to1[7][14] = 1.44643971535464;
   fWeightMatrix0to1[8][14] = -1.91368410001002;
   fWeightMatrix0to1[9][14] = 1.31804083722918;
   fWeightMatrix0to1[10][14] = -0.881813406342643;
   fWeightMatrix0to1[11][14] = 0.526026707977984;
   fWeightMatrix0to1[12][14] = -0.848913932958239;
   fWeightMatrix0to1[13][14] = 0.585634026156114;
   fWeightMatrix0to1[14][14] = 1.49453229213365;
   fWeightMatrix0to1[15][14] = -1.97410370053971;
   fWeightMatrix0to1[16][14] = 0.38395080589353;
   fWeightMatrix0to1[17][14] = 0.384306754239002;
   fWeightMatrix0to1[18][14] = -0.478759563236484;
   fWeightMatrix0to1[19][14] = -1.55411905742781;
   fWeightMatrix0to1[0][15] = -1.55217642361266;
   fWeightMatrix0to1[1][15] = -2.29852976216745;
   fWeightMatrix0to1[2][15] = 4.28678330253244;
   fWeightMatrix0to1[3][15] = -1.50060499461869;
   fWeightMatrix0to1[4][15] = 0.102979213675513;
   fWeightMatrix0to1[5][15] = -0.143805394550245;
   fWeightMatrix0to1[6][15] = -2.44596479102347;
   fWeightMatrix0to1[7][15] = -2.6045401191062;
   fWeightMatrix0to1[8][15] = -1.27588144050383;
   fWeightMatrix0to1[9][15] = -2.58952167830749;
   fWeightMatrix0to1[10][15] = -1.31750365678772;
   fWeightMatrix0to1[11][15] = -1.95511973432646;
   fWeightMatrix0to1[12][15] = -0.617154697170884;
   fWeightMatrix0to1[13][15] = 3.05748402296679;
   fWeightMatrix0to1[14][15] = 1.12476138236486;
   fWeightMatrix0to1[15][15] = -0.380132130920875;
   fWeightMatrix0to1[16][15] = 1.85033062759053;
   fWeightMatrix0to1[17][15] = -1.9840949804642;
   fWeightMatrix0to1[18][15] = 4.30155623761247;
   fWeightMatrix0to1[19][15] = 1.07769117584826;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.1665606788839;
   fWeightMatrix1to2[0][1] = -1.57207611245939;
   fWeightMatrix1to2[0][2] = 2.6035680709003;
   fWeightMatrix1to2[0][3] = -0.743829742436489;
   fWeightMatrix1to2[0][4] = 0.0362448457016128;
   fWeightMatrix1to2[0][5] = 0.587213639024705;
   fWeightMatrix1to2[0][6] = -1.16693911898771;
   fWeightMatrix1to2[0][7] = 2.23076666324782;
   fWeightMatrix1to2[0][8] = -0.00555689535445726;
   fWeightMatrix1to2[0][9] = 1.96146074763206;
   fWeightMatrix1to2[0][10] = -0.857273588973598;
   fWeightMatrix1to2[0][11] = 1.72502289765971;
   fWeightMatrix1to2[0][12] = -0.00106974548804481;
   fWeightMatrix1to2[0][13] = -0.968685485456967;
   fWeightMatrix1to2[0][14] = 0.00507506928180367;
   fWeightMatrix1to2[0][15] = 0.107432077183931;
   fWeightMatrix1to2[0][16] = -0.196890205857157;
   fWeightMatrix1to2[0][17] = 0.00851386967689244;
   fWeightMatrix1to2[0][18] = 1.75497819011209;
   fWeightMatrix1to2[0][19] = 0.100980526035723;
   fWeightMatrix1to2[0][20] = -2.89505858865483;
}

inline double ReadMLPBFGS::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)15) {
      std::cout << "Input vector needs to be of size " << 15 << std::endl;
      return 0;
   }

   std::array<double, 21> fWeights1 {{}};
   std::array<double, 1> fWeights2 {{}};
   fWeights1.back() = 1.;

   // layer 0 to 1
   for (int o=0; o<20; o++) {
      std::array<double, 16> buffer; // no need to initialise
      for (int i = 0; i<16 - 1; i++) {
         buffer[i] = fWeightMatrix0to1[o][i] * inputValues[i];
      } // loop over i
      buffer.back() = fWeightMatrix0to1[o][15];
      for (int i=0; i<16; i++) {
         fWeights1[o] += buffer[i];
      } // loop over i
    } // loop over o
   for (int o=0; o<20; o++) {
      fWeights1[o] = ActivationFnc(fWeights1[o]);
   } // loop over o
   // layer 1 to 2
   for (int o=0; o<1; o++) {
      std::array<double, 21> buffer; // no need to initialise
      for (int i=0; i<21; i++) {
         buffer[i] = fWeightMatrix1to2[o][i] * fWeights1[i];
      } // loop over i
      for (int i=0; i<21; i++) {
         fWeights2[o] += buffer[i];
      } // loop over i
    } // loop over o
   for (int o=0; o<1; o++) {
      fWeights2[o] = OutputActivationFnc(fWeights2[o]);
   } // loop over o

   return fWeights2[0];
}

double ReadMLPBFGS::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLPBFGS::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}

// Clean up
inline void ReadMLPBFGS::Clear()
{
}
inline double ReadMLPBFGS::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         std::vector<double> iV(inputValues);
         Transform( iV, -1 );
         retval = GetMvaValue__( iV );
   }

   return retval;
}

//_______________________________________________________________________
inline void ReadMLPBFGS::InitTransform_1()
{
   double fMin_1[3][15];
   double fMax_1[3][15];
   // Normalization transformation, initialisation
   fMin_1[0][0] = -2.3994140625;
   fMax_1[0][0] = 2.39990234375;
   fScal_1[0][0] = 2.0/(fMax_1[0][0]-fMin_1[0][0]);
   fOff_1[0][0] = fMin_1[0][0]*fScal_1[0][0]+1.;
   fMin_1[1][0] = -2.39990234375;
   fMax_1[1][0] = 2.39990234375;
   fScal_1[1][0] = 2.0/(fMax_1[1][0]-fMin_1[1][0]);
   fOff_1[1][0] = fMin_1[1][0]*fScal_1[1][0]+1.;
   fMin_1[2][0] = -2.39990234375;
   fMax_1[2][0] = 2.39990234375;
   fScal_1[2][0] = 2.0/(fMax_1[2][0]-fMin_1[2][0]);
   fOff_1[2][0] = fMin_1[2][0]*fScal_1[2][0]+1.;
   fMin_1[0][1] = -2.39990234375;
   fMax_1[0][1] = 2.39990234375;
   fScal_1[0][1] = 2.0/(fMax_1[0][1]-fMin_1[0][1]);
   fOff_1[0][1] = fMin_1[0][1]*fScal_1[0][1]+1.;
   fMin_1[1][1] = -2.39990234375;
   fMax_1[1][1] = 2.39990234375;
   fScal_1[1][1] = 2.0/(fMax_1[1][1]-fMin_1[1][1]);
   fOff_1[1][1] = fMin_1[1][1]*fScal_1[1][1]+1.;
   fMin_1[2][1] = -2.39990234375;
   fMax_1[2][1] = 2.39990234375;
   fScal_1[2][1] = 2.0/(fMax_1[2][1]-fMin_1[2][1]);
   fOff_1[2][1] = fMin_1[2][1]*fScal_1[2][1]+1.;
   fMin_1[0][2] = 30.0015525818;
   fMax_1[0][2] = 953.988952637;
   fScal_1[0][2] = 2.0/(fMax_1[0][2]-fMin_1[0][2]);
   fOff_1[0][2] = fMin_1[0][2]*fScal_1[0][2]+1.;
   fMin_1[1][2] = 30.0006580353;
   fMax_1[1][2] = 1195.94262695;
   fScal_1[1][2] = 2.0/(fMax_1[1][2]-fMin_1[1][2]);
   fOff_1[1][2] = fMin_1[1][2]*fScal_1[1][2]+1.;
   fMin_1[2][2] = 30.0006580353;
   fMax_1[2][2] = 1195.94262695;
   fScal_1[2][2] = 2.0/(fMax_1[2][2]-fMin_1[2][2]);
   fOff_1[2][2] = fMin_1[2][2]*fScal_1[2][2]+1.;
   fMin_1[0][3] = 30.0001525879;
   fMax_1[0][3] = 192.93812561;
   fScal_1[0][3] = 2.0/(fMax_1[0][3]-fMin_1[0][3]);
   fOff_1[0][3] = fMin_1[0][3]*fScal_1[0][3]+1.;
   fMin_1[1][3] = 30.0000667572;
   fMax_1[1][3] = 231.128250122;
   fScal_1[1][3] = 2.0/(fMax_1[1][3]-fMin_1[1][3]);
   fOff_1[1][3] = fMin_1[1][3]*fScal_1[1][3]+1.;
   fMin_1[2][3] = 30.0000667572;
   fMax_1[2][3] = 231.128250122;
   fScal_1[2][3] = 2.0/(fMax_1[2][3]-fMin_1[2][3]);
   fOff_1[2][3] = fMin_1[2][3]*fScal_1[2][3]+1.;
   fMin_1[0][4] = 65.0023269653;
   fMax_1[0][4] = 104.999137878;
   fScal_1[0][4] = 2.0/(fMax_1[0][4]-fMin_1[0][4]);
   fOff_1[0][4] = fMin_1[0][4]*fScal_1[0][4]+1.;
   fMin_1[1][4] = 65.0001831055;
   fMax_1[1][4] = 104.999771118;
   fScal_1[1][4] = 2.0/(fMax_1[1][4]-fMin_1[1][4]);
   fOff_1[1][4] = fMin_1[1][4]*fScal_1[1][4]+1.;
   fMin_1[2][4] = 65.0001831055;
   fMax_1[2][4] = 104.999771118;
   fScal_1[2][4] = 2.0/(fMax_1[2][4]-fMin_1[2][4]);
   fOff_1[2][4] = fMin_1[2][4]*fScal_1[2][4]+1.;
   fMin_1[0][5] = -2.49853515625;
   fMax_1[0][5] = 2.49951171875;
   fScal_1[0][5] = 2.0/(fMax_1[0][5]-fMin_1[0][5]);
   fOff_1[0][5] = fMin_1[0][5]*fScal_1[0][5]+1.;
   fMin_1[1][5] = -2.5;
   fMax_1[1][5] = 2.49951171875;
   fScal_1[1][5] = 2.0/(fMax_1[1][5]-fMin_1[1][5]);
   fOff_1[1][5] = fMin_1[1][5]*fScal_1[1][5]+1.;
   fMin_1[2][5] = -2.5;
   fMax_1[2][5] = 2.49951171875;
   fScal_1[2][5] = 2.0/(fMax_1[2][5]-fMin_1[2][5]);
   fOff_1[2][5] = fMin_1[2][5]*fScal_1[2][5]+1.;
   fMin_1[0][6] = -7.26252365112;
   fMax_1[0][6] = 8.83829593658;
   fScal_1[0][6] = 2.0/(fMax_1[0][6]-fMin_1[0][6]);
   fOff_1[0][6] = fMin_1[0][6]*fScal_1[0][6]+1.;
   fMin_1[1][6] = -10.3141937256;
   fMax_1[1][6] = 8.32720184326;
   fScal_1[1][6] = 2.0/(fMax_1[1][6]-fMin_1[1][6]);
   fOff_1[1][6] = fMin_1[1][6]*fScal_1[1][6]+1.;
   fMin_1[2][6] = -10.3141937256;
   fMax_1[2][6] = 8.83829593658;
   fScal_1[2][6] = 2.0/(fMax_1[2][6]-fMin_1[2][6]);
   fOff_1[2][6] = fMin_1[2][6]*fScal_1[2][6]+1.;
   fMin_1[0][7] = 0.000404357910156;
   fMax_1[0][7] = 1;
   fScal_1[0][7] = 2.0/(fMax_1[0][7]-fMin_1[0][7]);
   fOff_1[0][7] = fMin_1[0][7]*fScal_1[0][7]+1.;
   fMin_1[1][7] = 5.29736280441e-06;
   fMax_1[1][7] = 1;
   fScal_1[1][7] = 2.0/(fMax_1[1][7]-fMin_1[1][7]);
   fOff_1[1][7] = fMin_1[1][7]*fScal_1[1][7]+1.;
   fMin_1[2][7] = 5.29736280441e-06;
   fMax_1[2][7] = 1;
   fScal_1[2][7] = 2.0/(fMax_1[2][7]-fMin_1[2][7]);
   fOff_1[2][7] = fMin_1[2][7]*fScal_1[2][7]+1.;
   fMin_1[0][8] = -4.6962890625;
   fMax_1[0][8] = 4.6982421875;
   fScal_1[0][8] = 2.0/(fMax_1[0][8]-fMin_1[0][8]);
   fOff_1[0][8] = fMin_1[0][8]*fScal_1[0][8]+1.;
   fMin_1[1][8] = -4.69921875;
   fMax_1[1][8] = 4.6982421875;
   fScal_1[1][8] = 2.0/(fMax_1[1][8]-fMin_1[1][8]);
   fOff_1[1][8] = fMin_1[1][8]*fScal_1[1][8]+1.;
   fMin_1[2][8] = -4.69921875;
   fMax_1[2][8] = 4.6982421875;
   fScal_1[2][8] = 2.0/(fMax_1[2][8]-fMin_1[2][8]);
   fOff_1[2][8] = fMin_1[2][8]*fScal_1[2][8]+1.;
   fMin_1[0][9] = 3.55998054147e-07;
   fMax_1[0][9] = 1;
   fScal_1[0][9] = 2.0/(fMax_1[0][9]-fMin_1[0][9]);
   fOff_1[0][9] = fMin_1[0][9]*fScal_1[0][9]+1.;
   fMin_1[1][9] = 1.86380930245e-07;
   fMax_1[1][9] = 1;
   fScal_1[1][9] = 2.0/(fMax_1[1][9]-fMin_1[1][9]);
   fOff_1[1][9] = fMin_1[1][9]*fScal_1[1][9]+1.;
   fMin_1[2][9] = 1.86380930245e-07;
   fMax_1[2][9] = 1;
   fScal_1[2][9] = 2.0/(fMax_1[2][9]-fMin_1[2][9]);
   fOff_1[2][9] = fMin_1[2][9]*fScal_1[2][9]+1.;
   fMin_1[0][10] = 9.685754776e-07;
   fMax_1[0][10] = 75.25;
   fScal_1[0][10] = 2.0/(fMax_1[0][10]-fMin_1[0][10]);
   fOff_1[0][10] = fMin_1[0][10]*fScal_1[0][10]+1.;
   fMin_1[1][10] = -0.0176696777344;
   fMax_1[1][10] = 85.25;
   fScal_1[1][10] = 2.0/(fMax_1[1][10]-fMin_1[1][10]);
   fOff_1[1][10] = fMin_1[1][10]*fScal_1[1][10]+1.;
   fMin_1[2][10] = -0.0176696777344;
   fMax_1[2][10] = 85.25;
   fScal_1[2][10] = 2.0/(fMax_1[2][10]-fMin_1[2][10]);
   fOff_1[2][10] = fMin_1[2][10]*fScal_1[2][10]+1.;
   fMin_1[0][11] = -1.07940286398e-06;
   fMax_1[0][11] = 31.203125;
   fScal_1[0][11] = 2.0/(fMax_1[0][11]-fMin_1[0][11]);
   fOff_1[0][11] = fMin_1[0][11]*fScal_1[0][11]+1.;
   fMin_1[1][11] = -3.0156224966e-06;
   fMax_1[1][11] = 31.8125;
   fScal_1[1][11] = 2.0/(fMax_1[1][11]-fMin_1[1][11]);
   fOff_1[1][11] = fMin_1[1][11]*fScal_1[1][11]+1.;
   fMin_1[2][11] = -3.0156224966e-06;
   fMax_1[2][11] = 31.8125;
   fScal_1[2][11] = 2.0/(fMax_1[2][11]-fMin_1[2][11]);
   fOff_1[2][11] = fMin_1[2][11]*fScal_1[2][11]+1.;
   fMin_1[0][12] = 2.50028204918;
   fMax_1[0][12] = 9.203125;
   fScal_1[0][12] = 2.0/(fMax_1[0][12]-fMin_1[0][12]);
   fOff_1[0][12] = fMin_1[0][12]*fScal_1[0][12]+1.;
   fMin_1[1][12] = 2.50006103516;
   fMax_1[1][12] = 9.1044921875;
   fScal_1[1][12] = 2.0/(fMax_1[1][12]-fMin_1[1][12]);
   fOff_1[1][12] = fMin_1[1][12]*fScal_1[1][12]+1.;
   fMin_1[2][12] = 2.50006103516;
   fMax_1[2][12] = 9.203125;
   fScal_1[2][12] = 2.0/(fMax_1[2][12]-fMin_1[2][12]);
   fOff_1[2][12] = fMin_1[2][12]*fScal_1[2][12]+1.;
   fMin_1[0][13] = 500.050567627;
   fMax_1[0][13] = 9701.84667969;
   fScal_1[0][13] = 2.0/(fMax_1[0][13]-fMin_1[0][13]);
   fOff_1[0][13] = fMin_1[0][13]*fScal_1[0][13]+1.;
   fMin_1[1][13] = 500.000946045;
   fMax_1[1][13] = 7972.87207031;
   fScal_1[1][13] = 2.0/(fMax_1[1][13]-fMin_1[1][13]);
   fOff_1[1][13] = fMin_1[1][13]*fScal_1[1][13]+1.;
   fMin_1[2][13] = 500.000946045;
   fMax_1[2][13] = 9701.84667969;
   fScal_1[2][13] = 2.0/(fMax_1[2][13]-fMin_1[2][13]);
   fOff_1[2][13] = fMin_1[2][13]*fScal_1[2][13]+1.;
   fMin_1[0][14] = -3.57376289368;
   fMax_1[0][14] = 3.79529452324;
   fScal_1[0][14] = 2.0/(fMax_1[0][14]-fMin_1[0][14]);
   fOff_1[0][14] = fMin_1[0][14]*fScal_1[0][14]+1.;
   fMin_1[1][14] = -3.52589964867;
   fMax_1[1][14] = 3.58281874657;
   fScal_1[1][14] = 2.0/(fMax_1[1][14]-fMin_1[1][14]);
   fOff_1[1][14] = fMin_1[1][14]*fScal_1[1][14]+1.;
   fMin_1[2][14] = -3.57376289368;
   fMax_1[2][14] = 3.79529452324;
   fScal_1[2][14] = 2.0/(fMax_1[2][14]-fMin_1[2][14]);
   fOff_1[2][14] = fMin_1[2][14]*fScal_1[2][14]+1.;
}

//_______________________________________________________________________
inline void ReadMLPBFGS::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 15;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) {
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
      indicesGet.push_back( 11);
      indicesGet.push_back( 12);
      indicesGet.push_back( 13);
      indicesGet.push_back( 14);
   }
   if ( indicesPut.empty() ) {
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
      indicesPut.push_back( 11);
      indicesPut.push_back( 12);
      indicesPut.push_back( 13);
      indicesPut.push_back( 14);
   }

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<15;ivar++) {
      double offset = fOff_1[cls][ivar];
      double scale  = fScal_1[cls][ivar];
      iv[indicesPut.at(ivar)] = scale*dv[ivar]-offset;
   }
}

//_______________________________________________________________________
inline void ReadMLPBFGS::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLPBFGS::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
