// Class: ReadDNN_GPU4
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : DL::DNN_GPU4
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.26/06       [399878]
Creator        : markm
Date           : Tue Nov  1 21:01:12 2022
Host           : Linux kgizdov 5.19.4-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 25 Aug 2022 17:31:12 +0000 x86_64 GNU/Linux
Dir            : /home/markm/code/EAL
Training events: 176323
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "True" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
Layout: "TANH|64,TANH|64,TANH|32,LINEAR" [Layout of the network.]
ErrorStrategy: "CROSSENTROPY" [Loss function: Mean squared error (regression) or cross entropy (binary classification).]
WeightInitialization: "XAVIERUNIFORM" [Weight initialization strategy]
Architecture: "GPU" [Which architecture to perform the training on.]
# Default:
VerbosityLevel: "Verbose" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
InputLayout: "0|0|0" [The Layout of the input]
BatchLayout: "0|0|0" [The Layout of the batch]
RandomSeed: "0" [Random seed used for weight initialization and batch shuffling]
ValidationSize: "20%" [Part of the training data to use for validation. Specify as 0.2 or 20% to use a fifth of the data set as validation set. Specify as 100 to use exactly 100 events. (Default: 20%)]
TrainingStrategy: "LearningRate=1e-3,Momentum=0.0,ConvergenceSteps=100,MaxEpochs=2000,Optimizer=ADAM,BatchSize=30,TestRepetitions=1,WeightDecay=0.0,Regularization=None,DropConfig=0.0" [Defines the training strategies.]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 15
bos_PuppiAK8_eta              bos_PuppiAK8_eta              bos_PuppiAK8_eta              bos_PuppiAK8_eta                                                'F'    [-2.39990234375,2.39990234375]
bos_PuppiAK8_m_sd0_corr       bos_PuppiAK8_m_sd0_corr       bos_PuppiAK8_m_sd0_corr       bos_PuppiAK8_m_sd0_corr                                         'F'    [65.0625,104.9375]
bos_PuppiAK8_tau2tau1         bos_PuppiAK8_tau2tau1         bos_PuppiAK8_tau2tau1         bos_PuppiAK8_tau2tau1                                           'F'    [0.0140449441969,0.549973011017]
dibos_m                       dibos_m                       dibos_m                       dibos_m                                                         'F'    [128.920578003,5915.05126953]
lep1_eta                      lep1_eta                      lep1_eta                      lep1_eta                                                        'F'    [-2.5,2.4990234375]
nJet30f                       nJet30f                       nJet30f                       nJet30f                                                         'F'    [2,13]
vbf1_AK4_eta                  vbf1_AK4_eta                  vbf1_AK4_eta                  vbf1_AK4_eta                                                    'F'    [-4.66796875,4.658203125]
vbf1_AK4_qgid                 vbf1_AK4_qgid                 vbf1_AK4_qgid                 vbf1_AK4_qgid                                                   'F'    [3.32947820425e-08,1]
vbf2_AK4_eta                  vbf2_AK4_eta                  vbf2_AK4_eta                  vbf2_AK4_eta                                                    'F'    [-4.6845703125,4.6904296875]
vbf2_AK4_qgid                 vbf2_AK4_qgid                 vbf2_AK4_qgid                 vbf2_AK4_qgid                                                   'F'    [1.21165066957e-06,1]
vbf_deta                      vbf_deta                      vbf_deta                      vbf_deta                                                        'F'    [2.50012207031,8.8505859375]
vbf_eta                       vbf_eta                       vbf_eta                       vbf_eta                                                         'F'    [-8.29465293884,7.37775659561]
vbf_m                         vbf_m                         vbf_m                         vbf_m                                                           'F'    [500.000274658,8482.47265625]
zeppHad                       zeppHad                       zeppHad                       zeppHad                                                         'F'    [-3.21459960938,3.27465820312]
zeppLep                       zeppLep                       zeppLep                       zeppLep                                                         'F'    [-3.48477864265,3.39856219292]
NSpec 60
AntiIsoInt                    AntiIsoInt                    AntiIsoInt                    I                                                               'F'    [0,0]
bos_AK4AK4_eta                bos_AK4AK4_eta                bos_AK4AK4_eta                F                                                               'F'    [-999,-999]
bos_AK4AK4_m                  bos_AK4AK4_m                  bos_AK4AK4_m                  F                                                               'F'    [-999,-999]
bos_AK4AK4_pt                 bos_AK4AK4_pt                 bos_AK4AK4_pt                 F                                                               'F'    [-999,-999]
bosCent                       bosCent                       bosCent                       F                                                               'F'    [1.11022302463e-16,4.13032436371]
bos_j1_AK4_eta                bos_j1_AK4_eta                bos_j1_AK4_eta                F                                                               'F'    [-999,-999]
bos_j1_AK4_pt                 bos_j1_AK4_pt                 bos_j1_AK4_pt                 F                                                               'F'    [-999,-999]
bos_j2_AK4_eta                bos_j2_AK4_eta                bos_j2_AK4_eta                F                                                               'F'    [-999,-999]
bos_j2_AK4_pt                 bos_j2_AK4_pt                 bos_j2_AK4_pt                 F                                                               'F'    [-999,-999]
bos_PuppiAK8_m_sd0            bos_PuppiAK8_m_sd0            bos_PuppiAK8_m_sd0            F                                                               'F'    [65.0625,104.9375]
bos_PuppiAK8_phi              bos_PuppiAK8_phi              bos_PuppiAK8_phi              F                                                               'F'    [-3.1416015625,3.1416015625]
bos_PuppiAK8_pt               bos_PuppiAK8_pt               bos_PuppiAK8_pt               F                                                               'F'    [200.125,2856]
btagWeight_loose              btagWeight_loose              btagWeight_loose              F                                                               'F'    [0.447307109833,2.71326112747]
dibos_eta                     dibos_eta                     dibos_eta                     F                                                               'F'    [-6.48222923279,6.77470207214]
dibos_mt                      dibos_mt                      dibos_mt                      F                                                               'F'    [278.43560791,5918.08154297]
dibos_phi                     dibos_phi                     dibos_phi                     F                                                               'F'    [-3.14156889915,3.14154934883]
dibos_pt                      dibos_pt                      dibos_pt                      F                                                               'F'    [0.717565894127,2805.05175781]
dilep_eta                     dilep_eta                     dilep_eta                     F                                                               'F'    [-4.05583238602,3.8250477314]
dilep_m                       dilep_m                       dilep_m                       F                                                               'F'    [0.425420492887,1856.91162109]
dilep_mt                      dilep_mt                      dilep_mt                      F                                                               'F'    [55.7104530334,2937.40771484]
dilep_phi                     dilep_phi                     dilep_phi                     F                                                               'F'    [-3.14158678055,3.1415708065]
dilep_pt                      dilep_pt                      dilep_pt                      F                                                               'F'    [0.852797448635,2916.78808594]
evt                           evt                           evt                           I                                                               'F'    [32,354417984]
genWeight                     genWeight                     genWeight                     F                                                               'F'    [-303.359375,316.46875]
gid                           gid                           gid                           I                                                               'F'    [1,15]
L1PFWeight                    L1PFWeight                    L1PFWeight                    F                                                               'F'    [0.0342070013285,1]
lep1_idEffWeight              lep1_idEffWeight              lep1_idEffWeight              F                                                               'F'    [0.867357492447,1.06021249294]
lep1_iso                      lep1_iso                      lep1_iso                      F                                                               'F'    [0,0.149991750717]
lep1_m                        lep1_m                        lep1_m                        F                                                               'F'    [0.000510999991093,0.105658374727]
lep1_phi                      lep1_phi                      lep1_phi                      F                                                               'F'    [-3.1416015625,3.1416015625]
lep1_pt                       lep1_pt                       lep1_pt                       F                                                               'F'    [25.0003795624,2507.39941406]
lep1_q                        lep1_q                        lep1_q                        F                                                               'F'    [-1,1]
lep1_trigEffWeight            lep1_trigEffWeight            lep1_trigEffWeight            F                                                               'F'    [1,1]
lep2_eta                      lep2_eta                      lep2_eta                      F                                                               'F'    [-999,-999]
lep2_idEffWeight              lep2_idEffWeight              lep2_idEffWeight              F                                                               'F'    [1,1]
lep2_phi                      lep2_phi                      lep2_phi                      F                                                               'F'    [-999,-999]
lep2_pt                       lep2_pt                       lep2_pt                       F                                                               'F'    [-999,-999]
lep2_trigEffWeight            lep2_trigEffWeight            lep2_trigEffWeight            F                                                               'F'    [1,1]
lumin                         lumin                         lumin                         F                                                               'F'    [35867.0585938,59740]
mcWeight                      mcWeight                      mcWeight                      F                                                               'F'    [3.87841064819e-10,4.60524570371e-05]
MET                           MET                           MET                           F                                                               'F'    [30.0006599426,2713.93383789]
MET_phi                       MET_phi                       MET_phi                       F                                                               'F'    [-3.14159035683,3.14156794548]
nBtag_loose                   nBtag_loose                   nBtag_loose                   I                                                               'F'    [0,0]
nBtag_medium                  nBtag_medium                  nBtag_medium                  I                                                               'F'    [0,0]
neu_pz_type0                  neu_pz_type0                  neu_pz_type0                  F                                                               'F'    [-999,-999]
nJet30                        nJet30                        nJet30                        I                                                               'F'    [2,13]
nJet50                        nJet50                        nJet50                        I                                                               'F'    [2,11]
nPV                           nPV                           nPV                           F                                                               'F'    [1,91]
puWeight                      puWeight                      puWeight                      F                                                               'F'    [0,46.9509277344]
run                           run                           run                           I                                                               'F'    [1,1]
vbf1_AK4_m                    vbf1_AK4_m                    vbf1_AK4_m                    F                                                               'F'    [2.63671875,387]
vbf1_AK4_phi                  vbf1_AK4_phi                  vbf1_AK4_phi                  F                                                               'F'    [-3.1416015625,3.1416015625]
vbf1_AK4_pt                   vbf1_AK4_pt                   vbf1_AK4_pt                   F                                                               'F'    [50.007068634,2701.88964844]
vbf2_AK4_m                    vbf2_AK4_m                    vbf2_AK4_m                    F                                                               'F'    [1.4384765625,233.5]
vbf2_AK4_phi                  vbf2_AK4_phi                  vbf2_AK4_phi                  F                                                               'F'    [-3.1416015625,3.1416015625]
vbf2_AK4_pt                   vbf2_AK4_pt                   vbf2_AK4_pt                   F                                                               'F'    [50.000164032,1591.55004883]
vbf_phi                       vbf_phi                       vbf_phi                       F                                                               'F'    [-3.14157366753,3.14157915115]
vbf_pt                        vbf_pt                        vbf_pt                        F                                                               'F'    [0.437140285969,2741.69897461]
year                          year                          year                          I                                                               'F'    [2016,2018]
class_id                      class_id                      class_id                      I                                                               'F'    [0,1]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadDNN_GPU4 : public IClassifierReader {

 public:

   // constructor
   ReadDNN_GPU4( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadDNN_GPU4" ),
        fNvars( 15 )
   {
      // the training input variables
      const char* inputVars[] = { "bos_PuppiAK8_eta", "bos_PuppiAK8_m_sd0_corr", "bos_PuppiAK8_tau2tau1", "dibos_m", "lep1_eta", "nJet30f", "vbf1_AK4_eta", "vbf1_AK4_qgid", "vbf2_AK4_eta", "vbf2_AK4_qgid", "vbf_deta", "vbf_eta", "vbf_m", "zeppHad", "zeppLep" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 0.99999988079071;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;
      fVmin[11] = -1;
      fVmax[11] = 1;
      fVmin[12] = -1;
      fVmax[12] = 0.99999988079071;
      fVmin[13] = -1;
      fVmax[13] = 0.99999988079071;
      fVmin[14] = -1;
      fVmax[14] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadDNN_GPU4() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fOff_1[3][15];
   double fScal_1[3][15];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[15];
   double fVmax[15];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[15];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
inline double ReadDNN_GPU4::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         std::vector<double> iV(inputValues);
         Transform( iV, -1 );
         retval = GetMvaValue__( iV );
   }

   return retval;
}

//_______________________________________________________________________
inline void ReadDNN_GPU4::InitTransform_1()
{
   double fMin_1[3][15];
   double fMax_1[3][15];
   // Normalization transformation, initialisation
   fMin_1[0][0] = -2.3994140625;
   fMax_1[0][0] = 2.3994140625;
   fScal_1[0][0] = 2.0/(fMax_1[0][0]-fMin_1[0][0]);
   fOff_1[0][0] = fMin_1[0][0]*fScal_1[0][0]+1.;
   fMin_1[1][0] = -2.39990234375;
   fMax_1[1][0] = 2.39990234375;
   fScal_1[1][0] = 2.0/(fMax_1[1][0]-fMin_1[1][0]);
   fOff_1[1][0] = fMin_1[1][0]*fScal_1[1][0]+1.;
   fMin_1[2][0] = -2.39990234375;
   fMax_1[2][0] = 2.39990234375;
   fScal_1[2][0] = 2.0/(fMax_1[2][0]-fMin_1[2][0]);
   fOff_1[2][0] = fMin_1[2][0]*fScal_1[2][0]+1.;
   fMin_1[0][1] = 65.0625;
   fMax_1[0][1] = 104.9375;
   fScal_1[0][1] = 2.0/(fMax_1[0][1]-fMin_1[0][1]);
   fOff_1[0][1] = fMin_1[0][1]*fScal_1[0][1]+1.;
   fMin_1[1][1] = 65.0625;
   fMax_1[1][1] = 104.9375;
   fScal_1[1][1] = 2.0/(fMax_1[1][1]-fMin_1[1][1]);
   fOff_1[1][1] = fMin_1[1][1]*fScal_1[1][1]+1.;
   fMin_1[2][1] = 65.0625;
   fMax_1[2][1] = 104.9375;
   fScal_1[2][1] = 2.0/(fMax_1[2][1]-fMin_1[2][1]);
   fOff_1[2][1] = fMin_1[2][1]*fScal_1[2][1]+1.;
   fMin_1[0][2] = 0.0504441633821;
   fMax_1[0][2] = 0.549803435802;
   fScal_1[0][2] = 2.0/(fMax_1[0][2]-fMin_1[0][2]);
   fOff_1[0][2] = fMin_1[0][2]*fScal_1[0][2]+1.;
   fMin_1[1][2] = 0.0140449441969;
   fMax_1[1][2] = 0.549973011017;
   fScal_1[1][2] = 2.0/(fMax_1[1][2]-fMin_1[1][2]);
   fOff_1[1][2] = fMin_1[1][2]*fScal_1[1][2]+1.;
   fMin_1[2][2] = 0.0140449441969;
   fMax_1[2][2] = 0.549973011017;
   fScal_1[2][2] = 2.0/(fMax_1[2][2]-fMin_1[2][2]);
   fOff_1[2][2] = fMin_1[2][2]*fScal_1[2][2]+1.;
   fMin_1[0][3] = 139.903167725;
   fMax_1[0][3] = 3637.36865234;
   fScal_1[0][3] = 2.0/(fMax_1[0][3]-fMin_1[0][3]);
   fOff_1[0][3] = fMin_1[0][3]*fScal_1[0][3]+1.;
   fMin_1[1][3] = 128.920578003;
   fMax_1[1][3] = 5915.05126953;
   fScal_1[1][3] = 2.0/(fMax_1[1][3]-fMin_1[1][3]);
   fOff_1[1][3] = fMin_1[1][3]*fScal_1[1][3]+1.;
   fMin_1[2][3] = 128.920578003;
   fMax_1[2][3] = 5915.05126953;
   fScal_1[2][3] = 2.0/(fMax_1[2][3]-fMin_1[2][3]);
   fOff_1[2][3] = fMin_1[2][3]*fScal_1[2][3]+1.;
   fMin_1[0][4] = -2.49560546875;
   fMax_1[0][4] = 2.4931640625;
   fScal_1[0][4] = 2.0/(fMax_1[0][4]-fMin_1[0][4]);
   fOff_1[0][4] = fMin_1[0][4]*fScal_1[0][4]+1.;
   fMin_1[1][4] = -2.5;
   fMax_1[1][4] = 2.4990234375;
   fScal_1[1][4] = 2.0/(fMax_1[1][4]-fMin_1[1][4]);
   fOff_1[1][4] = fMin_1[1][4]*fScal_1[1][4]+1.;
   fMin_1[2][4] = -2.5;
   fMax_1[2][4] = 2.4990234375;
   fScal_1[2][4] = 2.0/(fMax_1[2][4]-fMin_1[2][4]);
   fOff_1[2][4] = fMin_1[2][4]*fScal_1[2][4]+1.;
   fMin_1[0][5] = 2;
   fMax_1[0][5] = 9;
   fScal_1[0][5] = 2.0/(fMax_1[0][5]-fMin_1[0][5]);
   fOff_1[0][5] = fMin_1[0][5]*fScal_1[0][5]+1.;
   fMin_1[1][5] = 2;
   fMax_1[1][5] = 13;
   fScal_1[1][5] = 2.0/(fMax_1[1][5]-fMin_1[1][5]);
   fOff_1[1][5] = fMin_1[1][5]*fScal_1[1][5]+1.;
   fMin_1[2][5] = 2;
   fMax_1[2][5] = 13;
   fScal_1[2][5] = 2.0/(fMax_1[2][5]-fMin_1[2][5]);
   fOff_1[2][5] = fMin_1[2][5]*fScal_1[2][5]+1.;
   fMin_1[0][6] = -4.6376953125;
   fMax_1[0][6] = 4.623046875;
   fScal_1[0][6] = 2.0/(fMax_1[0][6]-fMin_1[0][6]);
   fOff_1[0][6] = fMin_1[0][6]*fScal_1[0][6]+1.;
   fMin_1[1][6] = -4.66796875;
   fMax_1[1][6] = 4.658203125;
   fScal_1[1][6] = 2.0/(fMax_1[1][6]-fMin_1[1][6]);
   fOff_1[1][6] = fMin_1[1][6]*fScal_1[1][6]+1.;
   fMin_1[2][6] = -4.66796875;
   fMax_1[2][6] = 4.658203125;
   fScal_1[2][6] = 2.0/(fMax_1[2][6]-fMin_1[2][6]);
   fOff_1[2][6] = fMin_1[2][6]*fScal_1[2][6]+1.;
   fMin_1[0][7] = 0.000640392303467;
   fMax_1[0][7] = 1;
   fScal_1[0][7] = 2.0/(fMax_1[0][7]-fMin_1[0][7]);
   fOff_1[0][7] = fMin_1[0][7]*fScal_1[0][7]+1.;
   fMin_1[1][7] = 3.32947820425e-08;
   fMax_1[1][7] = 1;
   fScal_1[1][7] = 2.0/(fMax_1[1][7]-fMin_1[1][7]);
   fOff_1[1][7] = fMin_1[1][7]*fScal_1[1][7]+1.;
   fMin_1[2][7] = 3.32947820425e-08;
   fMax_1[2][7] = 1;
   fScal_1[2][7] = 2.0/(fMax_1[2][7]-fMin_1[2][7]);
   fOff_1[2][7] = fMin_1[2][7]*fScal_1[2][7]+1.;
   fMin_1[0][8] = -4.6708984375;
   fMax_1[0][8] = 4.6611328125;
   fScal_1[0][8] = 2.0/(fMax_1[0][8]-fMin_1[0][8]);
   fOff_1[0][8] = fMin_1[0][8]*fScal_1[0][8]+1.;
   fMin_1[1][8] = -4.6845703125;
   fMax_1[1][8] = 4.6904296875;
   fScal_1[1][8] = 2.0/(fMax_1[1][8]-fMin_1[1][8]);
   fOff_1[1][8] = fMin_1[1][8]*fScal_1[1][8]+1.;
   fMin_1[2][8] = -4.6845703125;
   fMax_1[2][8] = 4.6904296875;
   fScal_1[2][8] = 2.0/(fMax_1[2][8]-fMin_1[2][8]);
   fOff_1[2][8] = fMin_1[2][8]*fScal_1[2][8]+1.;
   fMin_1[0][9] = 0.000254392623901;
   fMax_1[0][9] = 1;
   fScal_1[0][9] = 2.0/(fMax_1[0][9]-fMin_1[0][9]);
   fOff_1[0][9] = fMin_1[0][9]*fScal_1[0][9]+1.;
   fMin_1[1][9] = 1.21165066957e-06;
   fMax_1[1][9] = 1;
   fScal_1[1][9] = 2.0/(fMax_1[1][9]-fMin_1[1][9]);
   fOff_1[1][9] = fMin_1[1][9]*fScal_1[1][9]+1.;
   fMin_1[2][9] = 1.21165066957e-06;
   fMax_1[2][9] = 1;
   fScal_1[2][9] = 2.0/(fMax_1[2][9]-fMin_1[2][9]);
   fOff_1[2][9] = fMin_1[2][9]*fScal_1[2][9]+1.;
   fMin_1[0][10] = 2.501953125;
   fMax_1[0][10] = 8.7978515625;
   fScal_1[0][10] = 2.0/(fMax_1[0][10]-fMin_1[0][10]);
   fOff_1[0][10] = fMin_1[0][10]*fScal_1[0][10]+1.;
   fMin_1[1][10] = 2.50012207031;
   fMax_1[1][10] = 8.8505859375;
   fScal_1[1][10] = 2.0/(fMax_1[1][10]-fMin_1[1][10]);
   fOff_1[1][10] = fMin_1[1][10]*fScal_1[1][10]+1.;
   fMin_1[2][10] = 2.50012207031;
   fMax_1[2][10] = 8.8505859375;
   fScal_1[2][10] = 2.0/(fMax_1[2][10]-fMin_1[2][10]);
   fOff_1[2][10] = fMin_1[2][10]*fScal_1[2][10]+1.;
   fMin_1[0][11] = -6.85506057739;
   fMax_1[0][11] = 7.02127408981;
   fScal_1[0][11] = 2.0/(fMax_1[0][11]-fMin_1[0][11]);
   fOff_1[0][11] = fMin_1[0][11]*fScal_1[0][11]+1.;
   fMin_1[1][11] = -8.29465293884;
   fMax_1[1][11] = 7.37775659561;
   fScal_1[1][11] = 2.0/(fMax_1[1][11]-fMin_1[1][11]);
   fOff_1[1][11] = fMin_1[1][11]*fScal_1[1][11]+1.;
   fMin_1[2][11] = -8.29465293884;
   fMax_1[2][11] = 7.37775659561;
   fScal_1[2][11] = 2.0/(fMax_1[2][11]-fMin_1[2][11]);
   fOff_1[2][11] = fMin_1[2][11]*fScal_1[2][11]+1.;
   fMin_1[0][12] = 500.162658691;
   fMax_1[0][12] = 8482.47265625;
   fScal_1[0][12] = 2.0/(fMax_1[0][12]-fMin_1[0][12]);
   fOff_1[0][12] = fMin_1[0][12]*fScal_1[0][12]+1.;
   fMin_1[1][12] = 500.000274658;
   fMax_1[1][12] = 7719.96875;
   fScal_1[1][12] = 2.0/(fMax_1[1][12]-fMin_1[1][12]);
   fOff_1[1][12] = fMin_1[1][12]*fScal_1[1][12]+1.;
   fMin_1[2][12] = 500.000274658;
   fMax_1[2][12] = 8482.47265625;
   fScal_1[2][12] = 2.0/(fMax_1[2][12]-fMin_1[2][12]);
   fOff_1[2][12] = fMin_1[2][12]*fScal_1[2][12]+1.;
   fMin_1[0][13] = -3.11181640625;
   fMax_1[0][13] = 3.1474609375;
   fScal_1[0][13] = 2.0/(fMax_1[0][13]-fMin_1[0][13]);
   fOff_1[0][13] = fMin_1[0][13]*fScal_1[0][13]+1.;
   fMin_1[1][13] = -3.21459960938;
   fMax_1[1][13] = 3.27465820312;
   fScal_1[1][13] = 2.0/(fMax_1[1][13]-fMin_1[1][13]);
   fOff_1[1][13] = fMin_1[1][13]*fScal_1[1][13]+1.;
   fMin_1[2][13] = -3.21459960938;
   fMax_1[2][13] = 3.27465820312;
   fScal_1[2][13] = 2.0/(fMax_1[2][13]-fMin_1[2][13]);
   fOff_1[2][13] = fMin_1[2][13]*fScal_1[2][13]+1.;
   fMin_1[0][14] = -3.36388087273;
   fMax_1[0][14] = 3.24051856995;
   fScal_1[0][14] = 2.0/(fMax_1[0][14]-fMin_1[0][14]);
   fOff_1[0][14] = fMin_1[0][14]*fScal_1[0][14]+1.;
   fMin_1[1][14] = -3.48477864265;
   fMax_1[1][14] = 3.39856219292;
   fScal_1[1][14] = 2.0/(fMax_1[1][14]-fMin_1[1][14]);
   fOff_1[1][14] = fMin_1[1][14]*fScal_1[1][14]+1.;
   fMin_1[2][14] = -3.48477864265;
   fMax_1[2][14] = 3.39856219292;
   fScal_1[2][14] = 2.0/(fMax_1[2][14]-fMin_1[2][14]);
   fOff_1[2][14] = fMin_1[2][14]*fScal_1[2][14]+1.;
}

//_______________________________________________________________________
inline void ReadDNN_GPU4::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 15;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) {
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
      indicesGet.push_back( 11);
      indicesGet.push_back( 12);
      indicesGet.push_back( 13);
      indicesGet.push_back( 14);
   }
   if ( indicesPut.empty() ) {
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
      indicesPut.push_back( 11);
      indicesPut.push_back( 12);
      indicesPut.push_back( 13);
      indicesPut.push_back( 14);
   }

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<15;ivar++) {
      double offset = fOff_1[cls][ivar];
      double scale  = fScal_1[cls][ivar];
      iv[indicesPut.at(ivar)] = scale*dv[ivar]-offset;
   }
}

//_______________________________________________________________________
inline void ReadDNN_GPU4::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadDNN_GPU4::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
